

INCLUDEPATH += $$PWD/DependLibs/ffmpeg
INCLUDEPATH += $$PWD/DependLibs/ffmpeg/libavfilter
INCLUDEPATH += $$PWD/DependLibs/libcurl/include
INCLUDEPATH += $$PWD/DependLibs/libcurl/lib

HEADERS += 	$$PWD/DependLibs/ffmpeg/libavfilter/af_afir.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_volume.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/audio.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_showcqt.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/avfilter.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/avfilter_internal.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/avfiltergraph.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/bbox.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/blend.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/bufferqueue.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/buffersink.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/buffersrc.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/bwdif.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/colorspacedsp.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/deshake.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/deshake_opencl.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/deshake_opencl_kernel.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/drawutils.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/ebur128.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/filters.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/formats.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/framepool.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/framequeue.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/framesync.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/generate_wave_table.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/gradfun.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/hermite.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/interlace.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/lavfutils.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/limiter.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/lswsutils.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/maskedmerge.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/motion_estimation.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/opencl_allkernels.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/psnr.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/removegrain.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/scale.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/signature.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/ssim.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/stereo3d.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/thread.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/tinterlace.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/transform.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/unsharp.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/unsharp_opencl.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/unsharp_opencl_kernel.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/version.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_eq.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_fspp.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hqdn3d.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_idet.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_noise.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_pp7.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_pullup.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_spp.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/video.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vidstabutils.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/vmaf_motion.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/w3fdif.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/window_func.h \
    $$PWD/DependLibs/ffmpeg/libavfilter/yadif.h \
    $$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvTargetOsConfig.h

SOURCES += 	$$PWD/DependLibs/ffmpeg/libavfilter/aeval.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_acontrast.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_acopy.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_acrusher.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_adelay.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_aecho.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_aemphasis.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_afade.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_afftfilt.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_afir.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_aformat.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_agate.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_alimiter.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_amerge.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_amix.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_anequalizer.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_anull.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_apad.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_aphaser.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_apulsator.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_aresample.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_asetnsamples.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_asetrate.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_ashowinfo.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_astats.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_atempo.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_biquads.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_bs2b.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_channelmap.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_channelsplit.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_chorus.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_compand.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_compensationdelay.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_crossfeed.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_crystalizer.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_dcshift.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_dynaudnorm.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_earwax.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_extrastereo.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_firequalizer.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_flanger.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_haas.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_hdcd.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_headphone.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_join.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_ladspa.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_loudnorm.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_pan.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_replaygain.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_resample.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_rubberband.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_sidechaincompress.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_silencedetect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_silenceremove.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_sofalizer.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_stereotools.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_stereowiden.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_superequalizer.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_surround.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_tremolo.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_vibrato.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_volume.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/af_volumedetect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/allfilters.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/asink_anullsink.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/asrc_anoisesrc.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/asrc_anullsrc.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/asrc_flite.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/asrc_sine.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/audio.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_abitscope.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_ahistogram.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_aphasemeter.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_avectorscope.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_concat.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_showcqt.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_showfreqs.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_showspectrum.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_showvolume.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avf_showwaves.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avfilter.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/avfiltergraph.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/bbox.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/buffersink.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/buffersrc.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/colorspacedsp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/colorspacedsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/colorspacedsp_yuv2yuv_template.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/deshake_opencl.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/drawutils.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/ebur128.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_bench.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_drawgraph.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_ebur128.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_interleave.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_loop.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_metadata.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_perms.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_realtime.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_reverse.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_select.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_sendcmd.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_sidedata.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_streamselect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/f_zmq.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/fifo.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/formats.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/framepool.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/framequeue.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/framesync.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/generate_wave_table.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/graphdump.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/graphparser.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/lavfutils.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/log2_tab.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/lswsutils.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/motion_estimation.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/opencl_allkernels.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/pthread.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/scale.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/setpts.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/settb.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/signature_lookup.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/split.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/src_movie.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/transform.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/trim.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/unsharp_opencl.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vaf_spectrumsynth.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_alphamerge.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_aspect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_atadenoise.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_avgblur.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_bbox.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_bitplanenoise.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_blackdetect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_blackframe.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_blend.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_boxblur.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_bwdif.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_chromakey.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_ciescope.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_codecview.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_colorbalance.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_colorchannelmixer.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_colorkey.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_colorlevels.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_colormatrix.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_colorspace.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_convolution.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_convolve.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_copy.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_cover_rect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_crop.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_cropdetect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_curves.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_datascope.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_dctdnoiz.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_deband.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_decimate.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_deflicker.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_deinterlace_qsv.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_deinterlace_vaapi.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_dejudder.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_delogo.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_deshake.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_despill.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_detelecine.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_displace.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_drawbox.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_drawtext.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_edgedetect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_elbg.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_eq.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_extractplanes.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_fade.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_fftfilt.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_field.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_fieldhint.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_fieldmatch.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_fieldorder.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_find_rect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_floodfill.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_format.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_fps.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_framepack.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_framerate.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_framestep.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_frei0r.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_fspp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_gblur.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_geq.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_gradfun.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hflip.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_histeq.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_histogram.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hqdn3d.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hqx.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hue.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hwdownload.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hwmap.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hwupload.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hwupload_cuda.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_hysteresis.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_idet.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_il.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_interlace.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_kerndeint.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_lenscorrection.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_libopencv.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_libvmaf.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_limiter.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_lumakey.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_lut.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_lut2.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_lut3d.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_maskedclamp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_maskedmerge.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_mcdeint.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_mergeplanes.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_mestimate.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_midequalizer.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_minterpolate.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_mpdecimate.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_neighbor.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_nlmeans.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_nnedi.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_noise.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_null.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_ocr.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_overlay.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_owdenoise.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_pad.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_palettegen.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_paletteuse.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_perspective.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_phase.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_pixdesctest.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_pp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_pp7.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_premultiply.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_pseudocolor.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_psnr.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_pullup.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_qp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_random.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_readeia608.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_readvitc.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_remap.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_removegrain.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_removelogo.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_repeatfields.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_rotate.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_sab.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_scale.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_scale_cuda.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_scale_npp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_scale_qsv.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_scale_vaapi.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_selectivecolor.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_separatefields.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_setfield.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_setparams.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_showinfo.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_showpalette.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_shuffleframes.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_shuffleplanes.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_signalstats.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_signature.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_smartblur.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_spp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_ssim.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_stack.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_stereo3d.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_subtitles.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_super2xsai.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_swaprect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_swapuv.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_telecine.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_threshold.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_thumbnail.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_thumbnail_cuda.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_tile.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_tinterlace.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_tonemap.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_transpose.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_unsharp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_uspp.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_vaguedenoiser.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_vectorscope.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_vflip.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_vidstabdetect.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_vidstabtransform.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_vignette.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_vmafmotion.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_w3fdif.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_waveform.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_weave.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_xbr.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_yadif.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_zoompan.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vf_zscale.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/video.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vidstabutils.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vsink_nullsink.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vsrc_cellauto.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vsrc_life.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vsrc_mandelbrot.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vsrc_mptestsrc.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/vsrc_testsrc.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/window_func.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/af_volume_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/avf_showcqt_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/colorspacedsp_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_blend_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_bwdif_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_fspp_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_gradfun_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_hqdn3d_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_idet_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_interlace_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_maskedmerge_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_noise_x86.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_pp7_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_psnr_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_pullup_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_removegrain_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_spp_x86.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_ssim_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_stereo3d_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_tinterlace_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_w3fdif_init.c \
    $$PWD/DependLibs/ffmpeg/libavfilter/x86/vf_yadif_init.c

