

INCLUDEPATH += $$PWD/DependLibs/ffmpeg/libavformat
INCLUDEPATH += $$PWD/DependLibs/ffmpeg
INCLUDEPATH += $$PWD/DependLibs/libcurl/include
INCLUDEPATH += $$PWD/DependLibs/libcurl/lib


HEADERS += 	$$PWD/DependLibs/ffmpeg/libavformat/aiff.h \
    $$PWD/DependLibs/ffmpeg/libavformat/apetag.h \
    $$PWD/DependLibs/ffmpeg/libavformat/asf.h \
    $$PWD/DependLibs/ffmpeg/libavformat/asfcrypt.h \
    $$PWD/DependLibs/ffmpeg/libavformat/ast.h \
    $$PWD/DependLibs/ffmpeg/libavformat/audiointerleave.h \
    $$PWD/DependLibs/ffmpeg/libavformat/avc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/avformat.h \
    $$PWD/DependLibs/ffmpeg/libavformat/avformat_internal.h \
    $$PWD/DependLibs/ffmpeg/libavformat/avi.h \
    $$PWD/DependLibs/ffmpeg/libavformat/avio.h \
    $$PWD/DependLibs/ffmpeg/libavformat/avio_internal.h \
    $$PWD/DependLibs/ffmpeg/libavformat/avlanguage.h \
    $$PWD/DependLibs/ffmpeg/libavformat/caf.h \
    $$PWD/DependLibs/ffmpeg/libavformat/dv.h \
    $$PWD/DependLibs/ffmpeg/libavformat/ffm.h \
    $$PWD/DependLibs/ffmpeg/libavformat/ffmeta.h \
    $$PWD/DependLibs/ffmpeg/libavformat/flac_picture.h \
    $$PWD/DependLibs/ffmpeg/libavformat/flacenc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/flv.h \
    $$PWD/DependLibs/ffmpeg/libavformat/gxf.h \
    $$PWD/DependLibs/ffmpeg/libavformat/hevc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/http.h \
    $$PWD/DependLibs/ffmpeg/libavformat/httpauth.h \
    $$PWD/DependLibs/ffmpeg/libavformat/id3v1.h \
    $$PWD/DependLibs/ffmpeg/libavformat/id3v2.h \
    $$PWD/DependLibs/ffmpeg/libavformat/img2.h \
    $$PWD/DependLibs/ffmpeg/libavformat/ircam.h \
    $$PWD/DependLibs/ffmpeg/libavformat/isom.h \
    $$PWD/DependLibs/ffmpeg/libavformat/lrc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/matroska.h \
    $$PWD/DependLibs/ffmpeg/libavformat/metadata.h \
    $$PWD/DependLibs/ffmpeg/libavformat/mms.h \
    $$PWD/DependLibs/ffmpeg/libavformat/mov_chan.h \
    $$PWD/DependLibs/ffmpeg/libavformat/movenc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/movenccenc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/mpeg.h \
    $$PWD/DependLibs/ffmpeg/libavformat/mpegts.h \
    $$PWD/DependLibs/ffmpeg/libavformat/mxf.h \
    $$PWD/DependLibs/ffmpeg/libavformat/network.h \
    $$PWD/DependLibs/ffmpeg/libavformat/nut.h \
    $$PWD/DependLibs/ffmpeg/libavformat/oggdec.h \
    $$PWD/DependLibs/ffmpeg/libavformat/oma.h \
    $$PWD/DependLibs/ffmpeg/libavformat/options_table.h \
    $$PWD/DependLibs/ffmpeg/libavformat/os_support.h \
    $$PWD/DependLibs/ffmpeg/libavformat/pcm.h \
    $$PWD/DependLibs/ffmpeg/libavformat/qtpalette.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rawdec.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rawenc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rdt.h \
    $$PWD/DependLibs/ffmpeg/libavformat/replaygain.h \
    $$PWD/DependLibs/ffmpeg/libavformat/riff.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rm.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rmsipr.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rso.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmp.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmpcrypt.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmpdh.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmppkt.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtp.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_formats.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_chain.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpproto.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtsp.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtspcodes.h \
    $$PWD/DependLibs/ffmpeg/libavformat/sauce.h \
    $$PWD/DependLibs/ffmpeg/libavformat/smjpeg.h \
    $$PWD/DependLibs/ffmpeg/libavformat/sox.h \
    $$PWD/DependLibs/ffmpeg/libavformat/spdif.h \
    $$PWD/DependLibs/ffmpeg/libavformat/srtp.h \
    $$PWD/DependLibs/ffmpeg/libavformat/subtitles.h \
    $$PWD/DependLibs/ffmpeg/libavformat/swf.h \
    $$PWD/DependLibs/ffmpeg/libavformat/tls.h \
    $$PWD/DependLibs/ffmpeg/libavformat/url.h \
    $$PWD/DependLibs/ffmpeg/libavformat/urldecode.h \
    $$PWD/DependLibs/ffmpeg/libavformat/version.h \
    $$PWD/DependLibs/ffmpeg/libavformat/voc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/vorbiscomment.h \
    $$PWD/DependLibs/ffmpeg/libavformat/vpcc.h \
    $$PWD/DependLibs/ffmpeg/libavformat/w64.h \
    $$PWD/DependLibs/ffmpeg/libavformat/wtv.h \
    $$PWD/DependLibs/ffmpeg/libavformat/wv.h \
    $$PWD/DependLibs/ffmpeg/libavformat/yuv4mpeg.h \
    $$PWD/DependLibs/ffmpeg/libavformat/tee_common.h \
    $$PWD/DependLibs/ffmpeg/libavformat/hlsplaylist.h \
    $$PWD/DependLibs/ffmpeg/libavformat/avformatres.rc \
    $$PWD/DependLibs/ffmpeg/libavformat/dash.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmp_avformat.h \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmp_log_avformat.h \
    $$PWD/DependLibs/ffmpeg/config_ffmpeg.h \
    $$PWD/GoTvAppConfig.h \
    $$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvTargetOsConfig.h

SOURCES += 	$$PWD/DependLibs/ffmpeg/libavformat/3dostr.c \
    $$PWD/DependLibs/ffmpeg/libavformat/4xm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/a64.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aacdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aadec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ac3dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/acm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/act.c \
    $$PWD/DependLibs/ffmpeg/libavformat/adp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ads.c \
    $$PWD/DependLibs/ffmpeg/libavformat/adtsenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/adxdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aea.c \
    $$PWD/DependLibs/ffmpeg/libavformat/afc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aiffdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aiffenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aixdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/allformats.c \
    $$PWD/DependLibs/ffmpeg/libavformat/amr.c \
    $$PWD/DependLibs/ffmpeg/libavformat/anm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/apc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ape.c \
    $$PWD/DependLibs/ffmpeg/libavformat/apetag.c \
    $$PWD/DependLibs/ffmpeg/libavformat/apngdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/apngenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aqtitledec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/asf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/asfcrypt.c \
    $$PWD/DependLibs/ffmpeg/libavformat/asfdec_f.c \
    $$PWD/DependLibs/ffmpeg/libavformat/asfdec_o.c \
    $$PWD/DependLibs/ffmpeg/libavformat/asfenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/assdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/assenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ast.c \
    $$PWD/DependLibs/ffmpeg/libavformat/astdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/astenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/async.c \
    $$PWD/DependLibs/ffmpeg/libavformat/au.c \
    $$PWD/DependLibs/ffmpeg/libavformat/audiointerleave.c \
    $$PWD/DependLibs/ffmpeg/libavformat/avc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/avidec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/avienc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/avio.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aviobuf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/avisynth.c \
    $$PWD/DependLibs/ffmpeg/libavformat/avlanguage.c \
    $$PWD/DependLibs/ffmpeg/libavformat/avr.c \
    $$PWD/DependLibs/ffmpeg/libavformat/avs.c \
    $$PWD/DependLibs/ffmpeg/libavformat/bethsoftvid.c \
    $$PWD/DependLibs/ffmpeg/libavformat/bfi.c \
    $$PWD/DependLibs/ffmpeg/libavformat/bink.c \
    $$PWD/DependLibs/ffmpeg/libavformat/bintext.c \
    $$PWD/DependLibs/ffmpeg/libavformat/bit.c \
    $$PWD/DependLibs/ffmpeg/libavformat/bluray.c \
    $$PWD/DependLibs/ffmpeg/libavformat/bmv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/boadec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/brstm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/c93.c \
    $$PWD/DependLibs/ffmpeg/libavformat/cache.c \
    $$PWD/DependLibs/ffmpeg/libavformat/caf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/cafdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/cafenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/cavsvideodec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/cdg.c \
    $$PWD/DependLibs/ffmpeg/libavformat/cdxl.c \
    $$PWD/DependLibs/ffmpeg/libavformat/chromaprint.c \
    $$PWD/DependLibs/ffmpeg/libavformat/cinedec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/concat.c \
    $$PWD/DependLibs/ffmpeg/libavformat/concatdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/crcenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/crypto.c \
    $$PWD/DependLibs/ffmpeg/libavformat/cutils.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dashenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/data_uri.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dauddec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/daudenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dcstr.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dfa.c \
    $$PWD/DependLibs/ffmpeg/libavformat/diracdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dnxhddec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dsfdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dsicin.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dss.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dtsdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dtshddec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dump.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dvbsub.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dvbtxt.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dvenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dxa.c \
    $$PWD/DependLibs/ffmpeg/libavformat/eacdata.c \
    $$PWD/DependLibs/ffmpeg/libavformat/electronicarts.c \
    $$PWD/DependLibs/ffmpeg/libavformat/epafdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ffmdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ffmenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ffmetadec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ffmetaenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/file.c \
    $$PWD/DependLibs/ffmpeg/libavformat/file_open.c \
    $$PWD/DependLibs/ffmpeg/libavformat/filmstripdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/filmstripenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/flac_picture.c \
    $$PWD/DependLibs/ffmpeg/libavformat/flacdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/flacenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/flacenc_header.c \
    $$PWD/DependLibs/ffmpeg/libavformat/flic.c \
    $$PWD/DependLibs/ffmpeg/libavformat/flvdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/flvenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/format.c \
    $$PWD/DependLibs/ffmpeg/libavformat/framecrcenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/framehash.c \
    $$PWD/DependLibs/ffmpeg/libavformat/frmdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/fsb.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ftp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/g722.c \
    $$PWD/DependLibs/ffmpeg/libavformat/g723_1.c \
    $$PWD/DependLibs/ffmpeg/libavformat/g729dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/genh.c \
    $$PWD/DependLibs/ffmpeg/libavformat/gif.c \
    $$PWD/DependLibs/ffmpeg/libavformat/gifdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/golomb_tab.c \
    $$PWD/DependLibs/ffmpeg/libavformat/gopher.c \
    $$PWD/DependLibs/ffmpeg/libavformat/gsmdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/gxf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/gxfenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/h261dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/h263dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/h264dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hashenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hdsenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hevc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hevcdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hls.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hlsenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hlsproto.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hnm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/http.c \
    $$PWD/DependLibs/ffmpeg/libavformat/httpauth.c \
    $$PWD/DependLibs/ffmpeg/libavformat/icecast.c \
    $$PWD/DependLibs/ffmpeg/libavformat/icodec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/icoenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/id3v1.c \
    $$PWD/DependLibs/ffmpeg/libavformat/id3v2.c \
    $$PWD/DependLibs/ffmpeg/libavformat/id3v2enc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/idcin.c \
    $$PWD/DependLibs/ffmpeg/libavformat/idroqdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/idroqenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/iff.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ilbc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/img2.c \
    $$PWD/DependLibs/ffmpeg/libavformat/img2_alias_pix.c \
    $$PWD/DependLibs/ffmpeg/libavformat/img2_brender_pix.c \
    $$PWD/DependLibs/ffmpeg/libavformat/img2dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/img2enc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ingenientdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ipmovie.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ircam.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ircamdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ircamenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/isom.c \
    $$PWD/DependLibs/ffmpeg/libavformat/iss.c \
    $$PWD/DependLibs/ffmpeg/libavformat/iv8.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ivfdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ivfenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/jacosubdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/jacosubenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/jvdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/latmenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/libgme.c \
    $$PWD/DependLibs/ffmpeg/libavformat/libmodplug.c \
    $$PWD/DependLibs/ffmpeg/libavformat/libnut.c \
    $$PWD/DependLibs/ffmpeg/libavformat/librtmp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/libsmbclient.c \
    $$PWD/DependLibs/ffmpeg/libavformat/libssh.c \
    $$PWD/DependLibs/ffmpeg/libavformat/lmlm4.c \
    $$PWD/DependLibs/ffmpeg/libavformat/loasdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/log2_tab.c \
    $$PWD/DependLibs/ffmpeg/libavformat/lrc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/lrcdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/lrcenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/lvfdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/lxfdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/m4vdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/matroska.c \
    $$PWD/DependLibs/ffmpeg/libavformat/matroskadec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/matroskaenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/md5proto.c \
    $$PWD/DependLibs/ffmpeg/libavformat/metadata.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mgsts.c \
    $$PWD/DependLibs/ffmpeg/libavformat/microdvddec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/microdvdenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mkvtimestamp_v2.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mlpdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mlvdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mmf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mms.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mmsh.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mmst.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mov.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mov_chan.c \
    $$PWD/DependLibs/ffmpeg/libavformat/movenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/movenccenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/movenchint.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mp3dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mp3enc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpc8.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpeg.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpegenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpegts.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpegtsenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpegvideodec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpjpeg.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpjpegdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpl2dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mpsubdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/msf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/msnwc_tcp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mtaf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mtv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/musx.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mux.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mvdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mvi.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mxf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mxfdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mxfenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mxg.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ncdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/network.c \
    $$PWD/DependLibs/ffmpeg/libavformat/nistspheredec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/nsvdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/nullenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/nut.c \
    $$PWD/DependLibs/ffmpeg/libavformat/nutdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/nutenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/nuv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparsecelt.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparsedaala.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparsedirac.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparseflac.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparseogm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparseopus.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparseskeleton.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparsespeex.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparsetheora.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparsevorbis.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oggparsevp8.c \
    $$PWD/DependLibs/ffmpeg/libavformat/oma.c \
    $$PWD/DependLibs/ffmpeg/libavformat/omadec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/omaenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/options.c \
    $$PWD/DependLibs/ffmpeg/libavformat/os_support.c \
    $$PWD/DependLibs/ffmpeg/libavformat/paf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/pcm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/pcmdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/pcmenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/pjsdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/pmpdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/protocol_list.c \
    $$PWD/DependLibs/ffmpeg/libavformat/protocols.c \
    $$PWD/DependLibs/ffmpeg/libavformat/psxstr.c \
    $$PWD/DependLibs/ffmpeg/libavformat/pva.c \
    $$PWD/DependLibs/ffmpeg/libavformat/pvfdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/qcp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/qtpalette.c \
    $$PWD/DependLibs/ffmpeg/libavformat/r3d.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rawdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rawenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rawutils.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rawvideodec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rdt.c \
    $$PWD/DependLibs/ffmpeg/libavformat/realtextdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/redspark.c \
    $$PWD/DependLibs/ffmpeg/libavformat/replaygain.c \
    $$PWD/DependLibs/ffmpeg/libavformat/riff.c \
    $$PWD/DependLibs/ffmpeg/libavformat/riffdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/riffenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rl2.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rmdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rmenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rmsipr.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rpl.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rsd.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rso.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rsodec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rsoenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmpcrypt.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmpdh.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmphttp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmppkt.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmpproto.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_ac3.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_amr.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_asf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_dv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_g726.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_h261.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_h263.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_h263_rfc2190.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_h264.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_hevc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_ilbc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_jpeg.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_latm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_mpa_robust.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_mpeg12.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_mpeg4.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_mpegts.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_qcelp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_qdm2.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_qt.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_svq3.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_vc2hq.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_vp8.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_vp9.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_xiph.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_aac.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_amr.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_chain.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_h261.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_h263.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_h263_rfc2190.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_h264_hevc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_jpeg.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_latm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_mpegts.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_mpv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_vc2hq.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_vp8.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_vp9.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpenc_xiph.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpproto.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtsp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtspdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtspenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/samidec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sapdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sapenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sauce.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sbgdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sctp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sdp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sdr2.c \
    $$PWD/DependLibs/ffmpeg/libavformat/segafilm.c \
    $$PWD/DependLibs/ffmpeg/libavformat/segment.c \
    $$PWD/DependLibs/ffmpeg/libavformat/shortendec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sierravmd.c \
    $$PWD/DependLibs/ffmpeg/libavformat/siff.c \
    $$PWD/DependLibs/ffmpeg/libavformat/smacker.c \
    $$PWD/DependLibs/ffmpeg/libavformat/smjpeg.c \
    $$PWD/DependLibs/ffmpeg/libavformat/smjpegdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/smjpegenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/smoothstreamingenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/smush.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sol.c \
    $$PWD/DependLibs/ffmpeg/libavformat/soxdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/soxenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/spdif.c \
    $$PWD/DependLibs/ffmpeg/libavformat/spdifdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/spdifenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/srtdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/srtenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/srtp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/srtpproto.c \
    $$PWD/DependLibs/ffmpeg/libavformat/stldec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/subfile.c \
    $$PWD/DependLibs/ffmpeg/libavformat/subtitles.c \
    $$PWD/DependLibs/ffmpeg/libavformat/subviewer1dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/subviewerdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/supdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/svag.c \
    $$PWD/DependLibs/ffmpeg/libavformat/swf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/swfdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/swfenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/takdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tcp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tedcaptionsdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tee.c \
    $$PWD/DependLibs/ffmpeg/libavformat/thp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tiertexseq.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tls.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tls_gnutls.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tls_openssl.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tls_schannel.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tls_securetransport.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tmv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tta.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tty.c \
    $$PWD/DependLibs/ffmpeg/libavformat/txd.c \
    $$PWD/DependLibs/ffmpeg/libavformat/udp.c \
    $$PWD/DependLibs/ffmpeg/libavformat/uncodedframecrcenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/unix.c \
    $$PWD/DependLibs/ffmpeg/libavformat/url.c \
    $$PWD/DependLibs/ffmpeg/libavformat/urldecode.c \
    $$PWD/DependLibs/ffmpeg/libavformat/utils.c \
    $$PWD/DependLibs/ffmpeg/libavformat/v210.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vag.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vc1dec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vc1test.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vc1testenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vivo.c \
    $$PWD/DependLibs/ffmpeg/libavformat/voc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/voc_packet.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vocdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vocenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vorbiscomment.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vpcc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vpk.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vplayerdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/vqf.c \
    $$PWD/DependLibs/ffmpeg/libavformat/w64.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wavdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wavenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wc3movie.c \
    $$PWD/DependLibs/ffmpeg/libavformat/webm_chunk.c \
    $$PWD/DependLibs/ffmpeg/libavformat/webmdashenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/webpenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/webvttdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/webvttenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/westwood_aud.c \
    $$PWD/DependLibs/ffmpeg/libavformat/westwood_vqa.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wsddec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wtv_common.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wtvdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wtvenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wvdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wvedec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/wvenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/xa.c \
    $$PWD/DependLibs/ffmpeg/libavformat/xmv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/xvag.c \
    $$PWD/DependLibs/ffmpeg/libavformat/xwma.c \
    $$PWD/DependLibs/ffmpeg/libavformat/yop.c \
    $$PWD/DependLibs/ffmpeg/libavformat/yuv4mpegdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/yuv4mpegenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtpdec_rfc4175.c \
    $$PWD/DependLibs/ffmpeg/libavformat/tee_common.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mov_esds.c \
    $$PWD/DependLibs/ffmpeg/libavformat/muxer_list.c \
    $$PWD/DependLibs/ffmpeg/libavformat/hlsplaylist.c \
    $$PWD/DependLibs/ffmpeg/libavformat/aptxdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/codec2.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dash.c \
    $$PWD/DependLibs/ffmpeg/libavformat/dashdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/demuxer_list.c \
    $$PWD/DependLibs/ffmpeg/libavformat/fifo.c \
    $$PWD/DependLibs/ffmpeg/libavformat/fifo_test.c \
    $$PWD/DependLibs/ffmpeg/libavformat/fitsdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/fitsenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/g726.c \
    $$PWD/DependLibs/ffmpeg/libavformat/gdv.c \
    $$PWD/DependLibs/ffmpeg/libavformat/libopenmpt.c \
    $$PWD/DependLibs/ffmpeg/libavformat/mj2kdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/nspdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/prompeg.c \
    $$PWD/DependLibs/ffmpeg/libavformat/rtmpdigest.c \
    $$PWD/DependLibs/ffmpeg/libavformat/s337m.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sbcdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sccdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sccenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sdsdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/sdxdec.c \
    $$PWD/DependLibs/ffmpeg/libavformat/segafilmenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/supenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/teeproto.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ttaenc.c \
    $$PWD/DependLibs/ffmpeg/libavformat/ty.c

DISTFILES += \
    $$PWD/DependLibs/ffmpeg/libavformat/Makefile \
    $$PWD/DependLibs/ffmpeg/libavformat/libavformat.v

