
INCLUDEPATH += $$PWD/DependLibs/libcurl/include
INCLUDEPATH += $$PWD/DependLibs/libcurl/lib
INCLUDEPATH += $$PWD/DependLibs/ffmpeg

$$PWD/DependLibs/ffmpeg/libavcodec/

HEADERS += 	$$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/DependLibs/ffmpeg/config_ffmpeg.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/a64colors.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/a64tables.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aac.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aac_ac3_parser.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aac_defines.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aaccoder_trellis.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aaccoder_twoloop.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacdectab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_is.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_ltp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_pred.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_quantization.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_quantization_misc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_tns.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_utils.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenctab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps_fixed_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacpsdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacsbr.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacsbr_fixed_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacsbr_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacsbr_tablegen_common.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacsbrdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aactab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/aandcttab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3_parser.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3dec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3dec_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3enc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3tab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/acelp_filters.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/acelp_pitch_delay.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/acelp_vectors.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/adpcm.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/adpcm_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/adx.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/alac_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/alacdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/amr.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/amrnbdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/amrwbdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/apng.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ass.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ass_split.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/asv.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac1data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac3data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac3plus.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac3plus_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/audio_frame_queue.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/audiodsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/avcodec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/avcodec_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/avdct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/avfft.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/bethsoftvideo.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/bgmc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/binkdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/binkdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/bintext.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/blockdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/bmp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/bsf.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/bswapdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/bytestream.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cabac.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cabac_functions.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/canopus.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cavs.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cavsdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cbrt_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cbrt_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/celp_filters.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/celp_math.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cfhd.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cga_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cookdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/copy_block.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/cos_table.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/d3d11va.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_core.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_exss.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_lbr.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_syncwords.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_xll.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcaadpcm.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcadata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcadct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcadec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcadsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcaenc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcahuff.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcamath.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dct32.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dctref.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/decode.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac_arith.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac_dwt.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac_vlc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/diracdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/diractab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dnxhddata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dnxhdenc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dolby_e.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dsd.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dsd_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dv.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dv_profile.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dv_profile_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dv_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvaudio.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvbtxt.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxva2.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxva2_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/eac3_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/eac3enc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/eaidct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/elbg.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/elsdec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/error_resilience.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/evrcdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/exif.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/exrdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/faandct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/faanidct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/faxcompr.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/fdctdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffjni.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/fft-internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/fft.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/fft_table.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffv1.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/fits.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/flac.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/flacdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/flacdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/flv.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/fmtconvert.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/frame_thread_encoder.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/g722.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/g722dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/g723_1.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/g729.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/g729data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/g729postfilter.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/get_bits.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/gif.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/golomb.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/gsm.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/gsmdec_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h261.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263_parser.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h2645_parse.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_mvpred.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_parse.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_ps.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_sei.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264chroma.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264dec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264idct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264pred.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264qpel.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hap.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_parse.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_ps.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_sei.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevcdec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevcdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevcpred.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hpeldsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hq_hqa.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hq_hqadsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hqx.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hqxdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/htmlsubtitles.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffman.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffyuv.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffyuvdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffyuvencdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/hwaccel.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/idctdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/iirfilter.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/imcdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/imdct15.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/indeo2data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/indeo3data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/indeo4data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/indeo5data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/intrax8.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/intrax8dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/intrax8huf.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ivi.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ivi_dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/jacosub.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/jni.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeg2000.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeg2000dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeg2000dwt.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpegls.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeglsdec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpegtables.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/kbdwin.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lagarithrac.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lcl.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopenh264.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopus.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/libschroedinger.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/libvpx.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/libwebpenc_common.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/libxvid.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lossless_audiodsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lossless_videodsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lossless_videoencdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lpc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lzf.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/lzw.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mathops.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mdct15.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/me_cmp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodec_surface.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodec_sw_buffer.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodec_wrapper.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodecdec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodecdec_common.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/metasound_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpeg.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegdec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegenc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegenc_common.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegenc_huffman.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlp_parser.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlpdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlz.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/motion_est.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/motionpixels_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpc7data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpc8data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpc8huff.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpcdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg12.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg12data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg12vlc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4audio.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4video.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4video_parser.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg_er.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudio.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudio_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodecheader.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodectab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiotab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegpicture.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegutils.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideo.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideodata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideodsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideoencdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mqc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/msgsmdec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/msmpeg4.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/msmpeg4data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/msrledec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss12.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss2dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss34dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/nellymoser.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/nvenc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/on2avcdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/options_table.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus_celt.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus_pvq.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus_rc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/opusenc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/opusenc_psy.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/opusenc_utils.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/opustab.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/paf.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/parser.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/pcm_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/pixblockdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/pixels.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/png.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/pngdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/pnm.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/profiles.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresdec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/psymodel.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/pthread_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/put_bits.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qcelpdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qdm2_tabels.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qdm2_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qdm2data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qpeldsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsv.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsv_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvdec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvenc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ra144.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ra288.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ralfdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rangecoder.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ratecontrol.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/raw.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rdft.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rectangle.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rl.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rle.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rnd_avg.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/roqvideo.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rtjpeg.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv10.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv30data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv34.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv34data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv34dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv34vlc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv40data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv40vlc2.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbr.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbrdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sgi.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/simple_idct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sinewin.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sinewin_tablegen.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sinwin_table.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sipr.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sipr16kdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/siprdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/snappy.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/snow.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/snow_dwt.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/snowdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sp5x.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/startcode.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/sunrast.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq1.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq1_cb.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq1_vlc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq1enc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq1enc_cb.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/synth_filter.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/tableprint.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/tableprint_vlc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/tak.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/takdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/targa.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/texturedsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/thread.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/tiff.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/tiff_common.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/tiff_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/tpeldsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/truemotion1data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/truespeech_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/tscc2data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ttadata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ttadsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ttaencdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/twinvq.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/twinvq_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/ulti_cb.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/unary.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/utvideo.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/utvideodsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/v210dec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/v210enc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_buffers.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_context.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_fmt.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_m2m.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_decode.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode_h26x.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1_common.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1_pred.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1acdata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc2enc_dwt.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vda.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vda_vt_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau_compat.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/version.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/videodsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/videotoolbox.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vlc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbis_enc_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbis_parser.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbis_parser_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbisdsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp3data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp3dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp56.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp56data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp56dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp5data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp6data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp8.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp8data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp8dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9dec.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9shared.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wavpack.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wavpackenc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wma.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wma_common.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wma_freqs.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmadata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmaprodata.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmavoice_data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmv2.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmv2data.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmv2dsp.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/xface.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/xiph.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/xvididct.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/xvmc.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/xvmc_internal.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/xwd.h \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbis_avcodec.h

# only used if generate tables which makes program larger but faster
#    $$PWD/DependLibs/ffmpeg/libavcodec/aacps_tables.h \
#    $$PWD/DependLibs/ffmpeg/libavcodec/cbrt_tables.h \
#    $$PWD/DependLibs/ffmpeg/libavcodec/dv_tables.h \
#    $$PWD/DependLibs/ffmpeg/libavcodec/motionpixels_tables.h \
#    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudio_tables.h \
#    $$PWD/DependLibs/ffmpeg/libavcodec/pcm_tables.h \

SOURCES += 	\
    $$PWD/DependLibs/ffmpeg/libavcodec/012v.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/4xm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/8bps.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/8svx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/a64multienc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aac_ac3_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aac_adtstoasc_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aac_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aaccoder.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacdec_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacdec_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacdec_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_is.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_ltp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_pred.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenc_tns.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacenctab.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps_fixed_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacps_tablegen_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacpsdata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacpsdsp_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacpsdsp_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacpsdsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacpsy.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacsbr.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacsbr_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aacsbr_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aactab.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aandcttab.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aasc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3dec_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3dec_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3dec_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3enc_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3enc_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3enc_opts_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3enc_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ac3tab.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/acelp_filters.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/acelp_pitch_delay.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/acelp_vectors.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adpcm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adpcm_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adpcmenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adts_header.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adts_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adx_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adxdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/adxenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aic.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/alac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/alac_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/alacdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/alacenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aliaspixdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aliaspixenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/allcodecs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/alsdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/amrnbdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/amrwbdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/anm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ansi.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/apedec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aptx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ass.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ass_split.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/assdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/assenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/asv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/asvdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/asvenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac3.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac3plus.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac3plusdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/atrac3plusdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/audio_frame_queue.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/audiodsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/audiotoolboxdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/audiotoolboxenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/aura.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/avdct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/avfft.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/avpacket.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/avpicture.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/avrndec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/avs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/avuidec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/avuienc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bethsoftvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bfi.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bgmc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bink.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/binkaudio.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/binkdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bintext.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bit_depth_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bitpacked.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bitstream.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bitstream_filter.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bitstream_filters.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/blockdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bmp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bmp_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bmpenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bmvaudio.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bmvvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/brenderpix.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bsf_list.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/bswapdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/c93.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cabac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/canopus.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cavs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cavs_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cavsdata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cavsdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cavsdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cbrt_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cbrt_data_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cbrt_fixed_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cbrt_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cbrt_tablegen_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ccaption_dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cdgraphics.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cdxl.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/celp_filters.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/celp_math.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cfhd.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cfhddata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cga_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/chomp_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cinepak.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cinepakenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/clearvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cljrdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cljrenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cllc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cngdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cngenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/codec2utils.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/codec_desc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/codec_list.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cook.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cook_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cos_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cpia.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/crystalhd.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cscd.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cuvid.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/cyuv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/d3d11va.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_core.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_core_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_exss.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_lbr.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dca_xll.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcaadpcm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcadata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcadct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcadec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcadsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcaenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dcahuff.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dct32_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dct32_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dct32_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dctref.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dds.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/decode.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dfa.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac_arith.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac_dwt.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac_dwt_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dirac_vlc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/diracdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/diracdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/diractab.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dnxhd_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dnxhddata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dnxhddec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dnxhdenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dolby_e.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dpcm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dpx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dpx_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dpxenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dsd.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dsddec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dsicinaudio.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dsicinvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dss_sp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dstdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dump_extradata_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dv_profile.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dv_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvaudio_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvaudiodec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvbsub.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvbsub_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvbsubdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvd_nav_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvdata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvdsub_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvdsubdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvdsubenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dvenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxa.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxtory.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxva2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxva2_h264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxva2_hevc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxva2_mpeg2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxva2_vc1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/dxva2_vp9.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eac3_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eac3dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eac3enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eacmv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eaidct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eamad.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eatgq.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eatgv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/eatqi.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/elbg.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/elsdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/encode.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/error_resilience.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/escape124.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/escape130.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/evrcdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/exif.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/exr.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/exrdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/extract_extradata_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/faandct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/faanidct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/faxcompr.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fdctdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffjni.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fft_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fft_fixed_32.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fft_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fft_init_table.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fft_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffv1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffv1_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffv1dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffv1dec_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffv1enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffv1enc_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ffwavesynth.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fic.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/file_open.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fits.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fitsdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fitsenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flac_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flacdata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flacdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flacdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flacdsp_lpc_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flacdsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flacenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flashsv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flashsv2enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flashsvenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flicvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flvdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/flvenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fmtconvert.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fmvc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/frame_thread_encoder.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/fraps.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/frwu.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g2meet.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g722.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g722dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g722dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g722enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g723_1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g723_1dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g723_1enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g726.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g729_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g729dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/g729postfilter.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/gdv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/gif.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/gifdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/golomb.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/gsm_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/gsmdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/gsmdec_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/gsmdec_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h261.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h261_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h261data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h261dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h261enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h263dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h2645_parse.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_cabac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_cavlc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_direct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_loopfilter.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_mb.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_mb_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_mc_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_mp4toannexb_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_parse.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_picture.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_ps.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_refs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_sei.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264_slice.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264addpx_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264chroma.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264chroma_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264dsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264idct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264idct_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264pred.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264pred_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264qpel.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/h264qpel_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hap.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hapdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hapenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_cabac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_filter.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_mp4toannexb_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_mvs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_parse.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_ps.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_ps_enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_refs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevc_sei.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevcdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevcdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevcdsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevcpred.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hevcpred_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hnm4video.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hpel_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hpeldsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hq_hqa.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hq_hqadata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hq_hqadsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hqx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hqxdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/hqxvlc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/htmlsubtitles.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffman.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffyuv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffyuvdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffyuvdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffyuvenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/huffyuvencdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/idcinvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/idctdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/iff.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/iirfilter.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/imc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/imdct15.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/imgconvert.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/imx_dump_header_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/indeo2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/indeo3.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/indeo4.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/indeo5.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/intelh263dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/interplayacm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/interplayvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/intrax8.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/intrax8dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ituh263dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ituh263enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ivi.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ivi_dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/j2kenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jacosubdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jfdctfst.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jfdctint.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jfdctint_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jni.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeg2000.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeg2000dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeg2000dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeg2000dwt.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpegls.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeglsdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpeglsenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jpegtables.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jrevdct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/jvdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/kbdwin.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/kgv1dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/kmvc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lagarith.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lagarithrac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/latm_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lcldec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lclenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libcelt_dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libfaac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libfdk-aacdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libfdk-aacenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libgsmdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libgsmenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libilbc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libkvazaar.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libmp3lame.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopencore-amr.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopenh264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopenh264dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopenh264enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopenjpegdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopenjpegenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopus.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopusdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libopusenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/librsvgdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libschroedinger.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libschroedingerdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libschroedingerenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libshine.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libspeexdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libspeexenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libtheoraenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libtwolame.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libvo-amrwbenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libvorbisdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libvorbisenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libvpx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libvpxdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libvpxenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libwavpackenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libwebpenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libwebpenc_animencoder.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libwebpenc_common.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libx264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libx265.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libxavs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libxvid.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libxvid_rc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/libzvbi-teletextdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ljpegenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/loco.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/log2_tab.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lossless_audiodsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lossless_videodsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lossless_videoencdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lpc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lzf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lzw.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/lzwenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/m101.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mace.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/magicyuv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/magicyuvenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mathtables.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mdct15.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mdct_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mdct_fixed_32.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mdct_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mdct_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/me_cmp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodec_surface.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodec_sw_buffer.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodec_wrapper.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodecdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodecdec_common.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mediacodecdec_h264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/metasound.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/metasound_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/microdvddec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mimic.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpeg2jpeg_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpeg_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpega_dump_header_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegbdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegenc_common.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mjpegenc_huffman.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlp_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlpdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlpdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlpenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mlz.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mmaldec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mmvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/motion_est.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/motion_est_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/motionpixels.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/motionpixels_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/movsub_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/movtextdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/movtextenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mp3_header_decompress_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpc7.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpc8.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg12.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg12data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg12dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg12enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg12framerate.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4_unpack_bframes_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4audio.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4video.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4video_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4videodec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg4videoenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpeg_er.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudio.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudio_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudio_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodec_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodec_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodec_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodecheader.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodsp_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodsp_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodsp_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudiodsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudioenc_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudioenc_float.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegaudioenc_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegpicture.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegutils.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideo_enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideo_motion.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideo_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideo_xvmc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideodata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideodsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpegvideoencdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mpl2dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mqc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mqcdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mqcenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mscc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msgsmdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msmpeg4.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msmpeg4data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msmpeg4dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msmpeg4enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msrle.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msrledec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss12.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss2dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss3.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss34dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mss4.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msvideo1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/msvideo1enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mvcdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/mxpegdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/nellymoser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/nellymoserdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/nellymoserenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/noise_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/null_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/nuv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/nvenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/nvenc_h264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/nvenc_hevc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/omx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/on2avc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/on2avcdata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/options.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus_celt.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus_pvq.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus_rc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opus_silk.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opusdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opusenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opusenc_psy.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/opustab.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pafaudio.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pafvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pamenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pcm-bluray.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pcm-dvd.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pcm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pcm_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pcx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pcxenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pel_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pgssubdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pictordec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pixblockdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pixlet.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/png.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/png_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pngdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pngdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pngenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pnm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pnm_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pnmdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pnmenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/profiles.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresdata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresdec2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresdec_lgpl.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresenc_anatoliy.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/proresenc_kostya.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/psd.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/psymodel.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pthread.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pthread_frame.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/pthread_slice.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ptx.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qcelpdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qdm2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qdm2_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qdmc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qdrw.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qpeg.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qpel_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qpeldsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsv_api.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvdec_h2645.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvdec_mpeg2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvdec_other.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvdec_vc1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvenc_h264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvenc_hevc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qsvenc_mpeg2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qtrle.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/qtrleenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/r210dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/r210enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ra144.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ra144dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ra144enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ra288.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ralf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rangecoder.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ratecontrol.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/raw.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rawdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rawenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rdft.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/realtextdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/remove_extradata_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/reverse.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rkmppdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rl.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rl2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rle.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/roqaudioenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/roqvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/roqvideodec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/roqvideoenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rpza.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rscc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rtjpeg.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv10.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv10enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv20enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv30.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv30dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv34.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv34_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv34dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv40.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/rv40dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/s302m.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/s302menc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/samidec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sanm.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbc_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbcdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbcdec_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbcdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbcdsp_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbcenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbrdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbrdsp_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sbrdsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/scpr.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/screenpresso.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sgidec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sgienc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sgirledec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sheervideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/shorten.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/simple_idct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/simple_idct_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sinewin.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sinewin_fixed.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sinewin_fixed_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sinewin_tablegen.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sinewin_tablegen_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sipr.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sipr16k.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sipr_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/smacker.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/smc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/smvjpegdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/snappy.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/snow.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/snow_dwt.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/snowdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/snowenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sonic.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sp5xdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/speedhq.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/srtdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/srtenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/startcode.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/subviewerdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sunrast.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/sunrastenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq13.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq1dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq1enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/svq3.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/synth_filter.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tak.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tak_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/takdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/takdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/targa.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/targa_y216dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/targaenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tdsc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/textdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/texturedsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/texturedspenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tiertexseqv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tiff.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tiff_common.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tiff_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tiffenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tmv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tpeldsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/truemotion1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/truemotion2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/truemotion2rt.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/truespeech.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tscc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tscc2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/tta.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ttadata.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ttadsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ttaenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ttaencdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/twinvq.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/twinvqdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/txd.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ulti.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/utils.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/utvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/utvideodec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/utvideodsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/utvideoenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v210dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v210enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v210x.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v308dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v308enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v408dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v408enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v410dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v410enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_buffers.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_context.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_fmt.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_m2m.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_m2m_dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/v4l2_m2m_enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_decode.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode_h264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode_h265.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode_h26x.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode_mjpeg.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode_mpeg2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode_vp8.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_encode_vp9.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_h264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_hevc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_mpeg2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_mpeg4.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_vc1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vaapi_vp9.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vb.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vble.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1_block.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1_loopfilter.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1_mc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1_pred.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc1dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc2enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vc2enc_dwt.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vcr1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vda.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vda_h264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vda_h264_dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau_h264.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau_hevc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau_mpeg12.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau_mpeg4.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vdpau_vc1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/videodsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/videodsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/videotoolbox.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/videotoolboxenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vima.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vmdaudio.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vmdvideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vmnc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbis.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbis_data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbis_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbisdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbisdsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vorbisenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp3.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp3_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp3dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp5.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp56.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp56data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp56dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp56rac.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp6.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp6dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp8.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp8_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp8dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9_mc_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9_raw_reorder_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9_superframe_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9_superframe_split_bsf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9block.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9dsp_10bpp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9dsp_12bpp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9dsp_8bpp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9dsp_template.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9lpf.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9mvs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9prob.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vp9recon.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/vqavideo.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wavpack.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wavpackenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/webp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/webvttdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/webvttenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wma.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wma_common.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wma_freqs.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmadec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmaenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmalosslessdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmaprodec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmavoice.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmv2.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmv2data.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmv2dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmv2dsp.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wmv2enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wnv1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/wrapped_avframe.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ws-snd1.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xan.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xbmdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xbmenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xface.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xfacedec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xfaceenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xiph.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xl.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xma_parser.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xpmdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xsubdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xsubenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xvididct.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xwddec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xwdenc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/xxan.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/y41pdec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/y41penc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/ylc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/yop.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/yuv4dec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/yuv4enc.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/zerocodec.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/zmbv.c \
    $$PWD/DependLibs/ffmpeg/libavcodec/zmbvenc.c
