INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libSYS/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libPCMutils/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libAACenc/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libMpegTPDec/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libSBRenc/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libSBRdec/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libFDK/include
INCLUDEPATH += $$PWD/DependLibs/libfdk-aac/libFDK/src

HEADERS += 	$$PWD/DependLibs/libfdk-aac/include/aacdecoder_lib.h \
    $$PWD/DependLibs/libfdk-aac/include/config_fdk-aac.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aac_ram.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aac_rom.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_drc.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_drc_types.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_hcr.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_hcr_bit.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_hcr_types.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_hcrs.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_pns.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_tns.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdecoder.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/block.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/channel.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/channelinfo.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/conceal.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/conceal_types.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/debug.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/ldfiltbank.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/overlapadd.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/pulsedata.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/rvlc.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/rvlc_info.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/rvlcbit.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/rvlcconceal.h \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/stereo.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/FDK_archdef.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/FDK_bitbuffer.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/FDK_bitstream.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/FDK_core.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/FDK_crc.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/FDK_hybrid.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/FDK_tools_rom.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/FDK_trigFcts.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/aarch64/clz_aarch64.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/aarch64/fixmul_aarch64.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/abs.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/arm/clz_arm.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/arm/cplx_mul.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/arm/fixmadd_arm.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/arm/fixmul_arm.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/arm/scale.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/arm/scramble.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/autocorr2nd.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/clz.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/common_fix.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/cplx_mul.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/dct.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/fft.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/fft_rad2.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/fixmadd.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/fixminmax.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/fixmul.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/fixpoint_math.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/mdct.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/mips/abs_mips.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/mips/clz_mips.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/mips/cplx_mul.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/mips/fixmadd_mips.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/mips/fixmul_mips.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/mips/scale.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/mips/scramble.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/ppc/clz_ppc.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/ppc/fixmul_ppc.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/qmf.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/scale.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/scramble.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/x86/abs_x86.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/x86/clz_x86.h \
    $$PWD/DependLibs/libfdk-aac/libFDK/include/x86/fixmul_x86.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/include/mpegFileRead.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/include/tp_data.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/include/tpdec_lib.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/mpegFileFormat.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_adif.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_adts.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_drm.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_latm.h \
    $$PWD/DependLibs/libfdk-aac/libPCMutils/include/limiter.h \
    $$PWD/DependLibs/libfdk-aac/libPCMutils/include/pcmutils_lib.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/include/sbrdecoder.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/env_calc.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/env_dec.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/env_extr.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/huff_dec.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/lpp_tran.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/psbitdec.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/psdec.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/psdec_hybrid.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_crc.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_deb.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_dec.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_ram_fdk_dec.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_rom_fdk_dec.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_scale.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbrdec_drc.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbrdec_freq_sca.h \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/transcendent.h \
    $$PWD/DependLibs/libfdk-aac/libSYS/include/FDK_audio.h \
    $$PWD/DependLibs/libfdk-aac/libSYS/include/audio.h \
    $$PWD/DependLibs/libfdk-aac/libSYS/include/cmdl_parser.h \
    $$PWD/DependLibs/libfdk-aac/libSYS/include/conv_string.h \
    $$PWD/DependLibs/libfdk-aac/libSYS/include/genericStds.h \
    $$PWD/DependLibs/libfdk-aac/libSYS/include/machine_type.h \
    $$PWD/DependLibs/libfdk-aac/libSYS/include/wav_file.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacenc.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacenc_pns.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacEnc_ram.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacEnc_rom.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacenc_tns.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/adj_thr.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/adj_thr_data.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/band_nrg.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/bandwidth.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/bit_cnt.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/bitenc.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/block_switch.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/channel_map.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/chaosmeasure.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/dyn_bits.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/grp_data.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/intensity.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/interface.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/line_pe.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/metadata_compressor.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/metadata_main.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/ms_stereo.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/noisedet.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/pns_func.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/pnsparam.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/pre_echo_control.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/psy_configuration.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/psy_const.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/psy_data.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/psy_main.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/qc_data.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/qc_main.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/quantize.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/sf_estim.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/spreading.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/tns_func.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/tonality.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/transform.h \
    $$PWD/DependLibs/libfdk-aac/libAACenc/include/aacenc_lib.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_adif.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_adts.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_asc.h \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_latm.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/include/sbr_encoder.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/bit_sbr.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/cmondata.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/code_env.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/env_bit.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/env_est.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/fram_gen.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/invf_est.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/mh_det.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/nf_est.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ps_bitenc.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ps_const.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ps_encode.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ps_main.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/resampler.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr_def.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbrenc_freq_sca.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr_misc.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr_ram_fdk_enc.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr_rom_fdk_enc.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ton_corr.h \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/tran_det.h

SOURCES += 	$$PWD/DependLibs/libfdk-aac/libAACdec/src/aac_ram.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aac_rom.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_drc.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_hcr.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_hcr_bit.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_hcrs.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_pns.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdec_tns.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdecoder.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/aacdecoder_lib.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/arm/block_arm.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/block.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/channel.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/channelinfo.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/conceal.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/ldfiltbank.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/pulsedata.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/rvlc.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/rvlcbit.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/rvlcconceal.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACdec/src/stereo.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/FDK_bitbuffer.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/FDK_core.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/FDK_crc.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/FDK_hybrid.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/FDK_tools_rom.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/FDK_trigFcts.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/arm/autocorr2nd_arm.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/arm/dct_arm.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/arm/fft_rad2_arm.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/arm/qmf_arm.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/arm/scale_arm.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/autocorr2nd_generic.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/dct.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/fft.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/fft_rad2.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/fixpoint_math.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/mdct.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/mips/fft_rad2_mips.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/mips/mips_fft_twiddles.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/mips/scale_mips.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/qmf.cpp \
    $$PWD/DependLibs/libfdk-aac/libFDK/src/scale_generic.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_adif.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_adts.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_asc.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_drm.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_latm.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPDec/src/tpdec_lib.cpp \
    $$PWD/DependLibs/libfdk-aac/libPCMutils/src/limiter.cpp \
    $$PWD/DependLibs/libfdk-aac/libPCMutils/src/pcmutils_lib.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/arm/env_calc_arm.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/arm/lpp_tran_arm.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/env_calc.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/env_dec.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/env_extr.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/huff_dec.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/lpp_tran.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/psbitdec.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/psdec.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/psdec_hybrid.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_crc.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_deb.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_dec.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_ram_fdk_dec.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbr_rom_fdk_dec.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbrdec_drc.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbrdec_freq_sca.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRdec/src/sbrdecoder.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacenc_lib.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacenc.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacenc_pns.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacEnc_ram.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacEnc_rom.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/aacenc_tns.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/adj_thr.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/band_nrg.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/bandwidth.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/bit_cnt.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/bitenc.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/block_switch.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/channel_map.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/chaosmeasure.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/dyn_bits.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/grp_data.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/intensity.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/line_pe.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/metadata_compressor.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/metadata_main.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/ms_stereo.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/noisedet.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/pnsparam.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/pre_echo_control.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/psy_configuration.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/psy_main.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/qc_main.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/quantize.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/sf_estim.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/spreading.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/tonality.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_adif.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_adts.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_asc.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_latm.cpp \
    $$PWD/DependLibs/libfdk-aac/libMpegTPEnc/src/tpenc_lib.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/bit_sbr.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/code_env.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/env_bit.cpp \
    $$PWD/DependLibs/libfdk-aac/libAACenc/src/transform_libffk_enc.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/wav_file_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/genericStds_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/conv_string_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/cmdl_parser_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/mips/genericStds_mips_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/linux/uart_linux_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/linux/genericStds_linux_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/linux/FDK_stackload_linux_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/linux/coresup_linux_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSYS/src/linux/audio_linux_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/tran_det_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ton_corr_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbrenc_freq_sca_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr_rom_fdk_enc_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr_ram_fdk_enc_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr_misc_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/sbr_encoder_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/resampler_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ps_main_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ps_encode_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/ps_bitenc_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/nf_est_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/mh_det_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/invf_est_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/fram_gen_fdkaac.cpp \
    $$PWD/DependLibs/libfdk-aac/libSBRenc/src/env_est_fdkaac.cpp

