

HEADERS += 	$$PWD/DependLibs/libfreetype/include/freetype/config/ftconfig.h \
    $$PWD/DependLibs/libfreetype/include/freetype/config/ftconfig_android.h \
    $$PWD/DependLibs/libfreetype/include/freetype/config/ftconfig_linux.h \
    $$PWD/DependLibs/libfreetype/include/freetype/config/ftconfig_windows.h \
    $$PWD/DependLibs/libfreetype/include/freetype/config/ftheader.h \
    $$PWD/DependLibs/libfreetype/include/freetype/config/ftmodule.h \
    $$PWD/DependLibs/libfreetype/include/freetype/config/ftoption.h \
    $$PWD/DependLibs/libfreetype/include/freetype/config/ftstdlib.h \
    $$PWD/DependLibs/libfreetype/include/freetype/freetype.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftadvanc.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftbbox.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftbdf.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftbitmap.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftbzip2.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftcache.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftchapters.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftcid.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftdriver.h \
    $$PWD/DependLibs/libfreetype/include/freetype/fterrdef.h \
    $$PWD/DependLibs/libfreetype/include/freetype/fterrors.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftfntfmt.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftgasp.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftglyph.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftgxval.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftgzip.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftimage.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftincrem.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftlcdfil.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftlist.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftlzw.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftmac.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftmm.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftmodapi.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftmoderr.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftotval.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftoutln.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftparams.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftpfr.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftrender.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftsizes.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftsnames.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftstroke.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftsynth.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftsystem.h \
    $$PWD/DependLibs/libfreetype/include/freetype/fttrigon.h \
    $$PWD/DependLibs/libfreetype/include/freetype/fttypes.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftwinfnt.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ftxf86.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/autohint.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/cffotypes.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/cfftypes.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftcalc.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftdebug.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftdriver.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftdrv.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftgloadr.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/fthash.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftmemory.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftobjs.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftpic.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftpsprop.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftrfork.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftserv.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftstream.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/fttrace.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/ftvalid.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/internal.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/pcftypes.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/psaux.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/pshints.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svbdf.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svcfftl.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svcid.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svfntfmt.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svgldict.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svgxval.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svkern.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svmetric.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svmm.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svotval.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svpfr.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svpostnm.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svprop.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svpscmap.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svpsinfo.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svsfnt.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svttcmap.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svtteng.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svttglyf.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svwinfnt.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/services/svxf86nm.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/sfnt.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/t1types.h \
    $$PWD/DependLibs/libfreetype/include/freetype/internal/tttypes.h \
    $$PWD/DependLibs/libfreetype/include/freetype/t1tables.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ttnameid.h \
    $$PWD/DependLibs/libfreetype/include/freetype/tttables.h \
    $$PWD/DependLibs/libfreetype/include/freetype/tttags.h \
    $$PWD/DependLibs/libfreetype/include/freetype/ttunpat.h \
    $$PWD/DependLibs/libfreetype/include/ft2build.h \
    $$PWD/DependLibs/libfreetype/src/cache/ftccache.h \
    $$PWD/DependLibs/libfreetype/src/cache/ftccback.h \
    $$PWD/DependLibs/libfreetype/src/cache/ftcerror.h \
    $$PWD/DependLibs/libfreetype/src/cache/ftcglyph.h \
    $$PWD/DependLibs/libfreetype/src/cache/ftcimage.h \
    $$PWD/DependLibs/libfreetype/src/cache/ftcmanag.h \
    $$PWD/DependLibs/libfreetype/src/cache/ftcmru.h \
    $$PWD/DependLibs/libfreetype/src/cache/ftcsbits.h



SOURCES += 	$$PWD/DependLibs/libfreetype/src/autofit/autofit.c \
    $$PWD/DependLibs/libfreetype/src/base/ftbase.c \
    $$PWD/DependLibs/libfreetype/src/base/ftbbox.c \
    $$PWD/DependLibs/libfreetype/src/base/ftbitmap.c \
    $$PWD/DependLibs/libfreetype/src/base/ftgasp.c \
    $$PWD/DependLibs/libfreetype/src/base/ftglyph.c \
    $$PWD/DependLibs/libfreetype/src/base/ftinit.c \
    $$PWD/DependLibs/libfreetype/src/base/ftmm.c \
    $$PWD/DependLibs/libfreetype/src/base/ftobjs.c \
    $$PWD/DependLibs/libfreetype/src/base/ftpfr.c \
    $$PWD/DependLibs/libfreetype/src/base/ftstroke.c \
    $$PWD/DependLibs/libfreetype/src/base/ftsynth.c \
    $$PWD/DependLibs/libfreetype/src/base/ftsystem.c \
    $$PWD/DependLibs/libfreetype/src/base/fttype1.c \
    $$PWD/DependLibs/libfreetype/src/base/ftwinfnt.c \
    $$PWD/DependLibs/libfreetype/src/bdf/bdf.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftcache.c \
    $$PWD/DependLibs/libfreetype/src/cff/cff.c \
    $$PWD/DependLibs/libfreetype/src/cid/type1cid.c \
    $$PWD/DependLibs/libfreetype/src/gzip/ftgzip.c \
    $$PWD/DependLibs/libfreetype/src/lzw/ftlzw.c \
    $$PWD/DependLibs/libfreetype/src/pcf/pcf.c \
    $$PWD/DependLibs/libfreetype/src/pfr/pfr.c \
    $$PWD/DependLibs/libfreetype/src/psaux/psaux.c \
    $$PWD/DependLibs/libfreetype/src/pshinter/pshinter.c \
    $$PWD/DependLibs/libfreetype/src/psnames/psmodule.c \
    $$PWD/DependLibs/libfreetype/src/raster/raster.c \
    $$PWD/DependLibs/libfreetype/src/sfnt/sfnt.c \
    $$PWD/DependLibs/libfreetype/src/smooth/smooth.c \
    $$PWD/DependLibs/libfreetype/src/truetype/truetype.c \
    $$PWD/DependLibs/libfreetype/src/type1/type1.c \
    $$PWD/DependLibs/libfreetype/src/type42/type42.c \
    $$PWD/DependLibs/libfreetype/src/winfonts/winfnt.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftcbasic.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftccache.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftccmap.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftcglyph.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftcimage.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftcmanag.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftcmru.c \
    $$PWD/DependLibs/libfreetype/src/cache/ftcsbits.c \
    $$PWD/DependLibs/libfreetype/src/ftlinux.c

