DEFINES += GLIB_COMPILATION _MBCS __need_nettle_getopt

INCLUDEPATH += $$PWD/DependLibs/libgnu

HEADERS += 	$$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvTargetOsConfig.h \
    $$PWD/DependLibs/libgnu/abstract_gnu.h \
    $$PWD/DependLibs/libgnu/accelerated/accelerated.h \
    $$PWD/DependLibs/libgnu/accelerated/cryptodev.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-aead.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-padlock.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-x86.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/sha-padlock.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/sha-x86.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/x86-common.h \
    $$PWD/DependLibs/libgnu/algorithms.h \
    $$PWD/DependLibs/libgnu/alignof.h \
    $$PWD/DependLibs/libgnu/alloca.in.h \
    $$PWD/DependLibs/libgnu/alloca_gnu.h \
    $$PWD/DependLibs/libgnu/alloca_gnu.in.h \
    $$PWD/DependLibs/libgnu/allocator.h \
    $$PWD/DependLibs/libgnu/areadlink.h \
    $$PWD/DependLibs/libgnu/arg-nonnull.h \
    $$PWD/DependLibs/libgnu/atfork.h \
    $$PWD/DependLibs/libgnu/ath.h \
    $$PWD/DependLibs/libgnu/auth/anon.h \
    $$PWD/DependLibs/libgnu/auth/cert.h \
    $$PWD/DependLibs/libgnu/auth/dh_common.h \
    $$PWD/DependLibs/libgnu/auth/ecdhe.h \
    $$PWD/DependLibs/libgnu/auth/psk.h \
    $$PWD/DependLibs/libgnu/auth/psk_passwd.h \
    $$PWD/DependLibs/libgnu/auth/rsa_common.h \
    $$PWD/DependLibs/libgnu/auth/srp_auth.h \
    $$PWD/DependLibs/libgnu/auth/srp_passwd.h \
    $$PWD/DependLibs/libgnu/base64_gnu.h \
    $$PWD/DependLibs/libgnu/basename.h \
    $$PWD/DependLibs/libgnu/binary-io.h \
    $$PWD/DependLibs/libgnu/bitrotate.h \
    $$PWD/DependLibs/libgnu/c++defs.h \
    $$PWD/DependLibs/libgnu/c-ctype.h \
    $$PWD/DependLibs/libgnu/c-strcase.h \
    $$PWD/DependLibs/libgnu/c-strcaseeq.h \
    $$PWD/DependLibs/libgnu/c-strstr.h \
    $$PWD/DependLibs/libgnu/careadlinkat.h \
    $$PWD/DependLibs/libgnu/cipher-proto.h \
    $$PWD/DependLibs/libgnu/cipher.h \
    $$PWD/DependLibs/libgnu/cipher/bithelp.h \
    $$PWD/DependLibs/libgnu/cipher/bufhelp.h \
    $$PWD/DependLibs/libgnu/cipher/camellia.h \
    $$PWD/DependLibs/libgnu/cipher/cipher-internal.h \
    $$PWD/DependLibs/libgnu/cipher/cipher-selftest.h \
    $$PWD/DependLibs/libgnu/cipher/ecc-common.h \
    $$PWD/DependLibs/libgnu/cipher/gost.h \
    $$PWD/DependLibs/libgnu/cipher/hash-common.h \
    $$PWD/DependLibs/libgnu/cipher/kdf-internal.h \
    $$PWD/DependLibs/libgnu/cipher/mac-internal.h \
    $$PWD/DependLibs/libgnu/cipher/pubkey-internal.h \
    $$PWD/DependLibs/libgnu/cipher/rijndael-tables.h \
    $$PWD/DependLibs/libgnu/cipher/rmd.h \
    $$PWD/DependLibs/libgnu/cldr-plural-exp.h \
    $$PWD/DependLibs/libgnu/cldr-plural.h \
    $$PWD/DependLibs/libgnu/clean-temp.h \
    $$PWD/DependLibs/libgnu/closeout.h \
    $$PWD/DependLibs/libgnu/code-from-errno.h \
    $$PWD/DependLibs/libgnu/code-to-errno.h \
    $$PWD/DependLibs/libgnu/color.h \
    $$PWD/DependLibs/libgnu/common_gnu.h \
    $$PWD/DependLibs/libgnu/compat.h \
    $$PWD/DependLibs/libgnu/compat/libcompat.h \
    $$PWD/DependLibs/libgnu/concat-filename.h \
    $$PWD/DependLibs/libgnu/config_libgnu.h \
    $$PWD/DependLibs/libgnu/context.h \
    $$PWD/DependLibs/libgnu/copy-file.h \
    $$PWD/DependLibs/libgnu/crypto-backend.h \
    $$PWD/DependLibs/libgnu/crypto.h \
    $$PWD/DependLibs/libgnu/csharpcomp.h \
    $$PWD/DependLibs/libgnu/csharpexec.h \
    $$PWD/DependLibs/libgnu/debug.h \
    $$PWD/DependLibs/libgnu/diffseq.h \
    $$PWD/DependLibs/libgnu/dir-list.h \
    $$PWD/DependLibs/libgnu/dirname.h \
    $$PWD/DependLibs/libgnu/djgpp/djpwd.h \
    $$PWD/DependLibs/libgnu/djgpp/ioctl_gnu.h \
    $$PWD/DependLibs/libgnu/dosname.h \
    $$PWD/DependLibs/libgnu/dtls.h \
    $$PWD/DependLibs/libgnu/ec-context.h \
    $$PWD/DependLibs/libgnu/element.h \
    $$PWD/DependLibs/libgnu/err-codes-sym.h \
    $$PWD/DependLibs/libgnu/err-codes.h \
    $$PWD/DependLibs/libgnu/err-sources-sym.h \
    $$PWD/DependLibs/libgnu/err-sources.h \
    $$PWD/DependLibs/libgnu/errno.in.h \
    $$PWD/DependLibs/libgnu/errnos-sym.h \
    $$PWD/DependLibs/libgnu/error-progname.h \
    $$PWD/DependLibs/libgnu/error.h \
    $$PWD/DependLibs/libgnu/estream-printf.h \
    $$PWD/DependLibs/libgnu/eval-plural.h \
    $$PWD/DependLibs/libgnu/exitfail.h \
    $$PWD/DependLibs/libgnu/export.h \
    $$PWD/DependLibs/libgnu/ext/alpn.h \
    $$PWD/DependLibs/libgnu/ext/cert_type.h \
    $$PWD/DependLibs/libgnu/ext/dumbfw.h \
    $$PWD/DependLibs/libgnu/ext/ecc_ext.h \
    $$PWD/DependLibs/libgnu/ext/etm.h \
    $$PWD/DependLibs/libgnu/ext/ext_master_secret.h \
    $$PWD/DependLibs/libgnu/ext/heartbeat.h \
    $$PWD/DependLibs/libgnu/ext/max_record.h \
    $$PWD/DependLibs/libgnu/ext/safe_renegotiation.h \
    $$PWD/DependLibs/libgnu/ext/server_name.h \
    $$PWD/DependLibs/libgnu/ext/session_ticket.h \
    $$PWD/DependLibs/libgnu/ext/signature.h \
    $$PWD/DependLibs/libgnu/ext/srp_wrapper.h \
    $$PWD/DependLibs/libgnu/ext/srtp.h \
    $$PWD/DependLibs/libgnu/ext/status_request.h \
    $$PWD/DependLibs/libgnu/extras/hex.h \
    $$PWD/DependLibs/libgnu/extras/randomart.h \
    $$PWD/DependLibs/libgnu/fatal-signal.h \
    $$PWD/DependLibs/libgnu/fcntl.in.h \
    $$PWD/DependLibs/libgnu/fd-hook.h \
    $$PWD/DependLibs/libgnu/file-list.h \
    $$PWD/DependLibs/libgnu/file-ostream.h \
    $$PWD/DependLibs/libgnu/file-ostream.oo.h \
    $$PWD/DependLibs/libgnu/file_ostream.priv.h \
    $$PWD/DependLibs/libgnu/file_ostream.vt.h \
    $$PWD/DependLibs/libgnu/filename.h \
    $$PWD/DependLibs/libgnu/filters.h \
    $$PWD/DependLibs/libgnu/fips.h \
    $$PWD/DependLibs/libgnu/float+.h \
    $$PWD/DependLibs/libgnu/float_gnu.h \
    $$PWD/DependLibs/libgnu/fnmatch.h \
    $$PWD/DependLibs/libgnu/format-c-parse.h \
    $$PWD/DependLibs/libgnu/format-invalid.h \
    $$PWD/DependLibs/libgnu/format.h \
    $$PWD/DependLibs/libgnu/fstrcmp.h \
    $$PWD/DependLibs/libgnu/fwriteerror.h \
    $$PWD/DependLibs/libgnu/g-gnulib.h \
    $$PWD/DependLibs/libgnu/g10lib.h \
    $$PWD/DependLibs/libgnu/gcd.h \
    $$PWD/DependLibs/libgnu/gcrypt-int.h \
    $$PWD/DependLibs/libgnu/gcrypt.h \
    $$PWD/DependLibs/libgnu/getopt.h \
    $$PWD/DependLibs/libgnu/getopt.in.h \
    $$PWD/DependLibs/libgnu/getopt_int.h \
    $$PWD/DependLibs/libgnu/gettext-po.h \
    $$PWD/DependLibs/libgnu/gettext-po.in.h \
    $$PWD/DependLibs/libgnu/gettext.h \
    $$PWD/DependLibs/libgnu/gettextP.h \
    $$PWD/DependLibs/libgnu/ghash.h \
    $$PWD/DependLibs/libgnu/gl_anylinked_list1.h \
    $$PWD/DependLibs/libgnu/gl_anylinked_list2.h \
    $$PWD/DependLibs/libgnu/gl_linked_list.h \
    $$PWD/DependLibs/libgnu/gl_list.h \
    $$PWD/DependLibs/libgnu/gl_xlist.h \
    $$PWD/DependLibs/libgnu/glib.h \
    $$PWD/DependLibs/libgnu/glist.h \
    $$PWD/DependLibs/libgnu/gmo.h \
    $$PWD/DependLibs/libgnu/gnutls.h \
    $$PWD/DependLibs/libgnu/gnutls_auth.h \
    $$PWD/DependLibs/libgnu/gnutls_buffers.h \
    $$PWD/DependLibs/libgnu/gnutls_cipher.h \
    $$PWD/DependLibs/libgnu/gnutls_cipher_int.h \
    $$PWD/DependLibs/libgnu/gnutls_compress.h \
    $$PWD/DependLibs/libgnu/gnutls_constate.h \
    $$PWD/DependLibs/libgnu/gnutls_crypto.h \
    $$PWD/DependLibs/libgnu/gnutls_datum.h \
    $$PWD/DependLibs/libgnu/gnutls_db.h \
    $$PWD/DependLibs/libgnu/gnutls_dh.h \
    $$PWD/DependLibs/libgnu/gnutls_dtls.h \
    $$PWD/DependLibs/libgnu/gnutls_ecc.h \
    $$PWD/DependLibs/libgnu/gnutls_errors.h \
    $$PWD/DependLibs/libgnu/gnutls_extensions.h \
    $$PWD/DependLibs/libgnu/gnutls_global.h \
    $$PWD/DependLibs/libgnu/gnutls_handshake.h \
    $$PWD/DependLibs/libgnu/gnutls_hash_int.h \
    $$PWD/DependLibs/libgnu/gnutls_helper.h \
    $$PWD/DependLibs/libgnu/gnutls_int.h \
    $$PWD/DependLibs/libgnu/gnutls_kx.h \
    $$PWD/DependLibs/libgnu/gnutls_mbuffers.h \
    $$PWD/DependLibs/libgnu/gnutls_mem.h \
    $$PWD/DependLibs/libgnu/gnutls_mpi.h \
    $$PWD/DependLibs/libgnu/gnutls_num.h \
    $$PWD/DependLibs/libgnu/gnutls_pk.h \
    $$PWD/DependLibs/libgnu/gnutls_random.h \
    $$PWD/DependLibs/libgnu/gnutls_record.h \
    $$PWD/DependLibs/libgnu/gnutls_session_pack.h \
    $$PWD/DependLibs/libgnu/gnutls_sig.h \
    $$PWD/DependLibs/libgnu/gnutls_srp.h \
    $$PWD/DependLibs/libgnu/gnutls_state.h \
    $$PWD/DependLibs/libgnu/gnutls_str.h \
    $$PWD/DependLibs/libgnu/gnutls_str_array.h \
    $$PWD/DependLibs/libgnu/gnutls_supplemental.h \
    $$PWD/DependLibs/libgnu/gnutls_urls.h \
    $$PWD/DependLibs/libgnu/gnutls_v2_compat.h \
    $$PWD/DependLibs/libgnu/gnutls_x509.h \
    $$PWD/DependLibs/libgnu/gnutlsxx.h \
    $$PWD/DependLibs/libgnu/gpg-error.h \
    $$PWD/DependLibs/libgnu/gpgrt-int.h \
    $$PWD/DependLibs/libgnu/gprimes.h \
    $$PWD/DependLibs/libgnu/gstr.h \
    $$PWD/DependLibs/libgnu/gstrfuncs.h \
    $$PWD/DependLibs/libgnu/gstring.h \
    $$PWD/DependLibs/libgnu/gtypes.h \
    $$PWD/DependLibs/libgnu/hard-locale.h \
    $$PWD/DependLibs/libgnu/hash-pjw-bare.h \
    $$PWD/DependLibs/libgnu/hash-pjw.h \
    $$PWD/DependLibs/libgnu/hash-string.h \
    $$PWD/DependLibs/libgnu/hash-triple.h \
    $$PWD/DependLibs/libgnu/hash.h \
    $$PWD/DependLibs/libgnu/hash_gnu.h \
    $$PWD/DependLibs/libgnu/hmac.h \
    $$PWD/DependLibs/libgnu/hmac256.h \
    $$PWD/DependLibs/libgnu/hwf-common.h \
    $$PWD/DependLibs/libgnu/iconv.h \
    $$PWD/DependLibs/libgnu/iconv.in.h \
    $$PWD/DependLibs/libgnu/iconv_gnu.h \
    $$PWD/DependLibs/libgnu/iconv_open-aix.h \
    $$PWD/DependLibs/libgnu/iconv_open-hpux.h \
    $$PWD/DependLibs/libgnu/iconv_open-irix.h \
    $$PWD/DependLibs/libgnu/iconv_open-osf.h \
    $$PWD/DependLibs/libgnu/iconv_open-solaris.h \
    $$PWD/DependLibs/libgnu/iconveh.h \
    $$PWD/DependLibs/libgnu/init_gnu.h \
    $$PWD/DependLibs/libgnu/intprops.h \
    $$PWD/DependLibs/libgnu/its.h \
    $$PWD/DependLibs/libgnu/javacomp.h \
    $$PWD/DependLibs/libgnu/javaexec.h \
    $$PWD/DependLibs/libgnu/javaversion.h \
    $$PWD/DependLibs/libgnu/kwset.h \
    $$PWD/DependLibs/libgnu/lang-table.h \
    $$PWD/DependLibs/libgnu/langinfo.h \
    $$PWD/DependLibs/libgnu/langinfo.in.h \
    $$PWD/DependLibs/libgnu/libcharset.h \
    $$PWD/DependLibs/libgnu/libgnuintl.h \
    $$PWD/DependLibs/libgnu/libgnuintl.in.h \
    $$PWD/DependLibs/libgnu/libgrep.h \
    $$PWD/DependLibs/libgnu/libintl.h \
    $$PWD/DependLibs/libgnu/libtasn1.h \
    $$PWD/DependLibs/libgnu/loadinfo.h \
    $$PWD/DependLibs/libgnu/localcharset.h \
    $$PWD/DependLibs/libgnu/locale_gnu.h \
    $$PWD/DependLibs/libgnu/locale_gnu.in.h \
    $$PWD/DependLibs/libgnu/localename.h \
    $$PWD/DependLibs/libgnu/locating-rule.h \
    $$PWD/DependLibs/libgnu/lock_gnu.h \
    $$PWD/DependLibs/libgnu/locks.h \
    $$PWD/DependLibs/libgnu/malloca.h \
    $$PWD/DependLibs/libgnu/markup.h \
    $$PWD/DependLibs/libgnu/mbchar.h \
    $$PWD/DependLibs/libgnu/mbiter.h \
    $$PWD/DependLibs/libgnu/mbswidth.h \
    $$PWD/DependLibs/libgnu/mbtowc-impl.h \
    $$PWD/DependLibs/libgnu/mbuiter.h \
    $$PWD/DependLibs/libgnu/message.h \
    $$PWD/DependLibs/libgnu/minmax.h \
    $$PWD/DependLibs/libgnu/mkerrcodes.h \
    $$PWD/DependLibs/libgnu/mman_w32.h \
    $$PWD/DependLibs/libgnu/moo.h \
    $$PWD/DependLibs/libgnu/mpi.h \
    $$PWD/DependLibs/libgnu/mpi/asm-syntax.h \
    $$PWD/DependLibs/libgnu/mpi/ec-internal.h \
    $$PWD/DependLibs/libgnu/mpi/generic/mpi-asm-defs.h \
    $$PWD/DependLibs/libgnu/mpi/longlong.h \
    $$PWD/DependLibs/libgnu/mpi/mod-source-info.h \
    $$PWD/DependLibs/libgnu/mpi/mpi-inline.h \
    $$PWD/DependLibs/libgnu/mpi/mpi-internal.h \
    $$PWD/DependLibs/libgnu/mpi/sysdep.h \
    $$PWD/DependLibs/libgnu/msgfmt.h \
    $$PWD/DependLibs/libgnu/msgl-ascii.h \
    $$PWD/DependLibs/libgnu/msgl-cat.h \
    $$PWD/DependLibs/libgnu/msgl-charset.h \
    $$PWD/DependLibs/libgnu/msgl-check.h \
    $$PWD/DependLibs/libgnu/msgl-english.h \
    $$PWD/DependLibs/libgnu/msgl-equal.h \
    $$PWD/DependLibs/libgnu/msgl-fsearch.h \
    $$PWD/DependLibs/libgnu/msgl-header.h \
    $$PWD/DependLibs/libgnu/msgl-iconv.h \
    $$PWD/DependLibs/libgnu/msgunfmt.h \
    $$PWD/DependLibs/libgnu/msvc-inval.h \
    $$PWD/DependLibs/libgnu/msvc-nothrow.h \
    $$PWD/DependLibs/libgnu/nettle/config_nettle.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-stdint.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-types.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-write.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_arcfour.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_arctwo.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_asn1.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_base16.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_bignum.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_blowfish.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_buffer.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_cast128.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_cast128_sboxes.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_cbc.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-poly1305.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_config.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ctr.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_curve25519.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_des-compat.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_des.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_desCode.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_desinfo.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_drbg-aes.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-compat.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-fips.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_eax.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-192.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-224.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-25519.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-256.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-384.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-521.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-curve.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecdsa.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_egd.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_fat-setup.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_getopt.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_getopt_int.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_gmp-glue.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_gnettle.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_gosthash94.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_keymap.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_knuth-lfib.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_macros.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_md2.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_md4.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5-compat.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_memxor-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_memxor.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_mini-gmp.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_pbkdf2.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_pgp.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_poly1305.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_realloc.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ripemd160.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_rnd-common.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_rotors.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-fips.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha1.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha2.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_twofish.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_version.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_yarrow.h \
    $$PWD/DependLibs/libgnu/obstack.h \
    $$PWD/DependLibs/libgnu/ocsp.h \
    $$PWD/DependLibs/libgnu/open-catalog.h \
    $$PWD/DependLibs/libgnu/opencdk/context.h \
    $$PWD/DependLibs/libgnu/opencdk/filters.h \
    $$PWD/DependLibs/libgnu/opencdk/keydb.h \
    $$PWD/DependLibs/libgnu/opencdk/main.h \
    $$PWD/DependLibs/libgnu/opencdk/opencdk.h \
    $$PWD/DependLibs/libgnu/opencdk/packet.h \
    $$PWD/DependLibs/libgnu/opencdk/stream.h \
    $$PWD/DependLibs/libgnu/opencdk/types.h \
    $$PWD/DependLibs/libgnu/openpgp.h \
    $$PWD/DependLibs/libgnu/openpgp/gnutls_openpgp.h \
    $$PWD/DependLibs/libgnu/openpgp/openpgp_int.h \
    $$PWD/DependLibs/libgnu/os2compat.h \
    $$PWD/DependLibs/libgnu/ostream.h \
    $$PWD/DependLibs/libgnu/ostream.oo.h \
    $$PWD/DependLibs/libgnu/ostream.priv.h \
    $$PWD/DependLibs/libgnu/ostream.vt.h \
    $$PWD/DependLibs/libgnu/parser_aux.h \
    $$PWD/DependLibs/libgnu/pathmax.h \
    $$PWD/DependLibs/libgnu/pin.h \
    $$PWD/DependLibs/libgnu/pkcs11.h \
    $$PWD/DependLibs/libgnu/pkcs11_int.h \
    $$PWD/DependLibs/libgnu/pkcs11x.h \
    $$PWD/DependLibs/libgnu/pkcs12.h \
    $$PWD/DependLibs/libgnu/pkcs7.h \
    $$PWD/DependLibs/libgnu/plural-count.h \
    $$PWD/DependLibs/libgnu/plural-distrib.h \
    $$PWD/DependLibs/libgnu/plural-eval.h \
    $$PWD/DependLibs/libgnu/plural-exp.h \
    $$PWD/DependLibs/libgnu/plural-table.h \
    $$PWD/DependLibs/libgnu/po-charset.h \
    $$PWD/DependLibs/libgnu/po-error.h \
    $$PWD/DependLibs/libgnu/po-gram-gen.h \
    $$PWD/DependLibs/libgnu/po-gram-gen2.h \
    $$PWD/DependLibs/libgnu/po-gram.h \
    $$PWD/DependLibs/libgnu/po-lex.h \
    $$PWD/DependLibs/libgnu/po-time.h \
    $$PWD/DependLibs/libgnu/po-xerror.h \
    $$PWD/DependLibs/libgnu/pos.h \
    $$PWD/DependLibs/libgnu/posix-lock-obj.h \
    $$PWD/DependLibs/libgnu/printf-args.h \
    $$PWD/DependLibs/libgnu/printf-parse.h \
    $$PWD/DependLibs/libgnu/printf.h \
    $$PWD/DependLibs/libgnu/priority_options.h \
    $$PWD/DependLibs/libgnu/progname.h \
    $$PWD/DependLibs/libgnu/propername.h \
    $$PWD/DependLibs/libgnu/quote.h \
    $$PWD/DependLibs/libgnu/rand-internal.h \
    $$PWD/DependLibs/libgnu/random_gnu.h \
    $$PWD/DependLibs/libgnu/read-catalog-abstract.h \
    $$PWD/DependLibs/libgnu/read-catalog.h \
    $$PWD/DependLibs/libgnu/read-csharp.h \
    $$PWD/DependLibs/libgnu/read-desktop.h \
    $$PWD/DependLibs/libgnu/read-file.h \
    $$PWD/DependLibs/libgnu/read-java.h \
    $$PWD/DependLibs/libgnu/read-mo.h \
    $$PWD/DependLibs/libgnu/read-po.h \
    $$PWD/DependLibs/libgnu/read-properties.h \
    $$PWD/DependLibs/libgnu/read-resources.h \
    $$PWD/DependLibs/libgnu/read-stringtable.h \
    $$PWD/DependLibs/libgnu/read-tcl.h \
    $$PWD/DependLibs/libgnu/regex.h \
    $$PWD/DependLibs/libgnu/regex_internal.h \
    $$PWD/DependLibs/libgnu/relocatable.h \
    $$PWD/DependLibs/libgnu/same-inode.h \
    $$PWD/DependLibs/libgnu/same.h \
    $$PWD/DependLibs/libgnu/search-path.h \
    $$PWD/DependLibs/libgnu/secmem_gnu.h \
    $$PWD/DependLibs/libgnu/self-test.h \
    $$PWD/DependLibs/libgnu/sentence.h \
    $$PWD/DependLibs/libgnu/signal.in.h \
    $$PWD/DependLibs/libgnu/signal_gnu.h \
    $$PWD/DependLibs/libgnu/signal_gnu.in.h \
    $$PWD/DependLibs/libgnu/size_max.h \
    $$PWD/DependLibs/libgnu/stdalign.h \
    $$PWD/DependLibs/libgnu/stdarg.in.h \
    $$PWD/DependLibs/libgnu/stdbool.in.h \
    $$PWD/DependLibs/libgnu/stddef.in.h \
    $$PWD/DependLibs/libgnu/stddef_gnu.h \
    $$PWD/DependLibs/libgnu/stddef_gnu.in.h \
    $$PWD/DependLibs/libgnu/stdint.in.h \
    $$PWD/DependLibs/libgnu/stdio.in.h \
    $$PWD/DependLibs/libgnu/stdio_gnu.h \
    $$PWD/DependLibs/libgnu/stdio_gnu.in.h \
    $$PWD/DependLibs/libgnu/stdlib.in.h \
    $$PWD/DependLibs/libgnu/stdlib_gnu.h \
    $$PWD/DependLibs/libgnu/stdlib_gnu.in.h \
    $$PWD/DependLibs/libgnu/stdmem.h \
    $$PWD/DependLibs/libgnu/str-kmp.h \
    $$PWD/DependLibs/libgnu/str-list.h \
    $$PWD/DependLibs/libgnu/str-two-way.h \
    $$PWD/DependLibs/libgnu/streq.h \
    $$PWD/DependLibs/libgnu/strerror-override.h \
    $$PWD/DependLibs/libgnu/striconv.h \
    $$PWD/DependLibs/libgnu/striconveh.h \
    $$PWD/DependLibs/libgnu/striconveha.h \
    $$PWD/DependLibs/libgnu/string.in.h \
    $$PWD/DependLibs/libgnu/string_gnu.h \
    $$PWD/DependLibs/libgnu/string_gnu.in.h \
    $$PWD/DependLibs/libgnu/strnlen1.h \
    $$PWD/DependLibs/libgnu/structure.h \
    $$PWD/DependLibs/libgnu/styled-ostream.h \
    $$PWD/DependLibs/libgnu/styled-ostream.oo.h \
    $$PWD/DependLibs/libgnu/styled_ostream.priv.h \
    $$PWD/DependLibs/libgnu/styled_ostream.vt.h \
    $$PWD/DependLibs/libgnu/sys/stat_gnu.h \
    $$PWD/DependLibs/libgnu/sys/time_gnu.h \
    $$PWD/DependLibs/libgnu/sys/types_gnu.h \
    $$PWD/DependLibs/libgnu/sys_select.in.h \
    $$PWD/DependLibs/libgnu/sys_stat.in.h \
    $$PWD/DependLibs/libgnu/sys_time.in.h \
    $$PWD/DependLibs/libgnu/sys_types.in.h \
    $$PWD/DependLibs/libgnu/sys_wait.in.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.aarch64-apple-darwin.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.aarch64-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.alpha-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.arm-apple-darwin.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.arm-unknown-linux-androideabi.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.arm-unknown-linux-gnueabi.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.arm-unknown-linux-gnueabihf.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.hppa-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.i486-pc-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.i486-pc-kfreebsd-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.i686-pc-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.linux-android.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.m68k-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.mingw32.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.mips-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.mips64el-unknown-linux-gnuabi64.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.mipsel-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.or1k-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.powerpc-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.powerpc64-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.powerpc64le-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.s390x-ibm-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.sh4-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.sparc-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.sparc64-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.x86_64-pc-kfreebsd-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.x86_64-pc-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.x86_64-pc-linux-gnux32.h \
    $$PWD/DependLibs/libgnu/system-keys.h \
    $$PWD/DependLibs/libgnu/system.h \
    $$PWD/DependLibs/libgnu/thread.h \
    $$PWD/DependLibs/libgnu/time.in.h \
    $$PWD/DependLibs/libgnu/time_gnu.h \
    $$PWD/DependLibs/libgnu/time_gnu.in.h \
    $$PWD/DependLibs/libgnu/tls.h \
    $$PWD/DependLibs/libgnu/tmpdir.h \
    $$PWD/DependLibs/libgnu/tpm.h \
    $$PWD/DependLibs/libgnu/trim.h \
    $$PWD/DependLibs/libgnu/tsearch.h \
    $$PWD/DependLibs/libgnu/types_gnu.h \
    $$PWD/DependLibs/libgnu/u64.h \
    $$PWD/DependLibs/libgnu/uniconv.in.h \
    $$PWD/DependLibs/libgnu/unictype.h \
    $$PWD/DependLibs/libgnu/unictype/bitmap.h \
    $$PWD/DependLibs/libgnu/unictype/ctype_alpha.h \
    $$PWD/DependLibs/libgnu/unictype/ctype_space.h \
    $$PWD/DependLibs/libgnu/unilbrk.h \
    $$PWD/DependLibs/libgnu/unilbrk.in.h \
    $$PWD/DependLibs/libgnu/uniname.h \
    $$PWD/DependLibs/libgnu/unistd.in.h \
    $$PWD/DependLibs/libgnu/unistd_gnu.h \
    $$PWD/DependLibs/libgnu/unistd_gnu.in.h \
    $$PWD/DependLibs/libgnu/unistr.h \
    $$PWD/DependLibs/libgnu/unistr.in.h \
    $$PWD/DependLibs/libgnu/unitypes.h \
    $$PWD/DependLibs/libgnu/unitypes.in.h \
    $$PWD/DependLibs/libgnu/uniwidth.h \
    $$PWD/DependLibs/libgnu/uniwidth.in.h \
    $$PWD/DependLibs/libgnu/uniwidth/cjk.h \
    $$PWD/DependLibs/libgnu/unlocked-io.h \
    $$PWD/DependLibs/libgnu/unused-parameter.h \
    $$PWD/DependLibs/libgnu/urls.h \
    $$PWD/DependLibs/libgnu/vasnprintf.h \
    $$PWD/DependLibs/libgnu/vasnwprintf.h \
    $$PWD/DependLibs/libgnu/vasprintf.h \
    $$PWD/DependLibs/libgnu/verify.h \
    $$PWD/DependLibs/libgnu/visibility_gnu.h \
    $$PWD/DependLibs/libgnu/w32-add.h \
    $$PWD/DependLibs/libgnu/w32-lock-obj.h \
    $$PWD/DependLibs/libgnu/w32ce-add.h \
    $$PWD/DependLibs/libgnu/warn-on-use.h \
    $$PWD/DependLibs/libgnu/wchar.in.h \
    $$PWD/DependLibs/libgnu/wchar_gnu.h \
    $$PWD/DependLibs/libgnu/wchar_gnu.in.h \
    $$PWD/DependLibs/libgnu/wctype.in.h \
    $$PWD/DependLibs/libgnu/wctype_gnu.h \
    $$PWD/DependLibs/libgnu/wprintf-parse.h \
    $$PWD/DependLibs/libgnu/write-catalog.h \
    $$PWD/DependLibs/libgnu/write-csharp.h \
    $$PWD/DependLibs/libgnu/write-desktop.h \
    $$PWD/DependLibs/libgnu/write-java.h \
    $$PWD/DependLibs/libgnu/write-mo.h \
    $$PWD/DependLibs/libgnu/write-po.h \
    $$PWD/DependLibs/libgnu/write-properties.h \
    $$PWD/DependLibs/libgnu/write-qt.h \
    $$PWD/DependLibs/libgnu/write-resources.h \
    $$PWD/DependLibs/libgnu/write-stringtable.h \
    $$PWD/DependLibs/libgnu/write-tcl.h \
    $$PWD/DependLibs/libgnu/write-xml.h \
    $$PWD/DependLibs/libgnu/x-appdata.h \
    $$PWD/DependLibs/libgnu/x-awk.h \
    $$PWD/DependLibs/libgnu/x-c.h \
    $$PWD/DependLibs/libgnu/x-csharp.h \
    $$PWD/DependLibs/libgnu/x-desktop.h \
    $$PWD/DependLibs/libgnu/x-elisp.h \
    $$PWD/DependLibs/libgnu/x-glade.h \
    $$PWD/DependLibs/libgnu/x-gsettings.h \
    $$PWD/DependLibs/libgnu/x-java.h \
    $$PWD/DependLibs/libgnu/x-javascript.h \
    $$PWD/DependLibs/libgnu/x-librep.h \
    $$PWD/DependLibs/libgnu/x-lisp.h \
    $$PWD/DependLibs/libgnu/x-lua.h \
    $$PWD/DependLibs/libgnu/x-perl.h \
    $$PWD/DependLibs/libgnu/x-php.h \
    $$PWD/DependLibs/libgnu/x-po.h \
    $$PWD/DependLibs/libgnu/x-properties.h \
    $$PWD/DependLibs/libgnu/x-python.h \
    $$PWD/DependLibs/libgnu/x-rst.h \
    $$PWD/DependLibs/libgnu/x-scheme.h \
    $$PWD/DependLibs/libgnu/x-sh.h \
    $$PWD/DependLibs/libgnu/x-smalltalk.h \
    $$PWD/DependLibs/libgnu/x-stringtable.h \
    $$PWD/DependLibs/libgnu/x-tcl.h \
    $$PWD/DependLibs/libgnu/x-vala.h \
    $$PWD/DependLibs/libgnu/x-ycp.h \
    $$PWD/DependLibs/libgnu/x509-ext.h \
    $$PWD/DependLibs/libgnu/x509.h \
    $$PWD/DependLibs/libgnu/x509/gnutls-idna.h \
    $$PWD/DependLibs/libgnu/x509/gnutls_common.h \
    $$PWD/DependLibs/libgnu/x509/verify-high.h \
    $$PWD/DependLibs/libgnu/x509/x509_int.h \
    $$PWD/DependLibs/libgnu/x509_b64.h \
    $$PWD/DependLibs/libgnu/xalloc-oversized.h \
    $$PWD/DependLibs/libgnu/xalloc.h \
    $$PWD/DependLibs/libgnu/xerror.h \
    $$PWD/DependLibs/libgnu/xgettext.h \
    $$PWD/DependLibs/libgnu/xmalloca.h \
    $$PWD/DependLibs/libgnu/xreadlink.h \
    $$PWD/DependLibs/libgnu/xsize_gnu.h \
    $$PWD/DependLibs/libgnu/xstriconv.h \
    $$PWD/DependLibs/libgnu/xvasprintf.h \
    $$PWD/DependLibs/libgnu/int_gnu.h

SOURCES += 	$$PWD/DependLibs/libgnu/accelerated/accelerated.c \
    $$PWD/DependLibs/libgnu/accelerated/cryptodev-gcm.c \
    $$PWD/DependLibs/libgnu/accelerated/cryptodev.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-cbc-x86-aesni.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-cbc-x86-ssse3.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-ccm-x86-aesni.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-padlock.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-x86-aesni.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-x86-pclmul.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-x86-ssse3.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-padlock.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/hmac-padlock.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/hmac-x86-ssse3.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/sha-padlock.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/sha-x86-ssse3.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/x86-common.c \
    $$PWD/DependLibs/libgnu/algorithms/cert_types.c \
    $$PWD/DependLibs/libgnu/algorithms/ciphers.c \
    $$PWD/DependLibs/libgnu/algorithms/ciphersuites.c \
    $$PWD/DependLibs/libgnu/algorithms/ecc_algorithms.c \
    $$PWD/DependLibs/libgnu/algorithms/kx.c \
    $$PWD/DependLibs/libgnu/algorithms/mac_algorithms.c \
    $$PWD/DependLibs/libgnu/algorithms/protocols.c \
    $$PWD/DependLibs/libgnu/algorithms/publickey.c \
    $$PWD/DependLibs/libgnu/algorithms/secparams.c \
    $$PWD/DependLibs/libgnu/algorithms/sign_algorithms.c \
    $$PWD/DependLibs/libgnu/allocator.c \
    $$PWD/DependLibs/libgnu/areadlink.c \
    $$PWD/DependLibs/libgnu/asnprintf.c \
    $$PWD/DependLibs/libgnu/asprintf.c \
    $$PWD/DependLibs/libgnu/atexit.c \
    $$PWD/DependLibs/libgnu/atfork.c \
    $$PWD/DependLibs/libgnu/ath.c \
    $$PWD/DependLibs/libgnu/auth/anon.c \
    $$PWD/DependLibs/libgnu/auth/anon_ecdh.c \
    $$PWD/DependLibs/libgnu/auth/cert.c \
    $$PWD/DependLibs/libgnu/auth/dh_common.c \
    $$PWD/DependLibs/libgnu/auth/dhe.c \
    $$PWD/DependLibs/libgnu/auth/dhe_psk.c \
    $$PWD/DependLibs/libgnu/auth/ecdhe.c \
    $$PWD/DependLibs/libgnu/auth/psk.c \
    $$PWD/DependLibs/libgnu/auth/psk_passwd.c \
    $$PWD/DependLibs/libgnu/auth/rsa_gnutls.c \
    $$PWD/DependLibs/libgnu/auth/rsa_psk.c \
    $$PWD/DependLibs/libgnu/auth/srp_auth.c \
    $$PWD/DependLibs/libgnu/auth/srp_passwd.c \
    $$PWD/DependLibs/libgnu/auth/srp_rsa.c \
    $$PWD/DependLibs/libgnu/auth/srp_sb64.c \
    $$PWD/DependLibs/libgnu/auto-verify.c \
    $$PWD/DependLibs/libgnu/base64_gnu.c \
    $$PWD/DependLibs/libgnu/basename.c \
    $$PWD/DependLibs/libgnu/binary-io.c \
    $$PWD/DependLibs/libgnu/bindtextdom.c \
    $$PWD/DependLibs/libgnu/bitrotate.c \
    $$PWD/DependLibs/libgnu/btowc.c \
    $$PWD/DependLibs/libgnu/c-ctype.c \
    $$PWD/DependLibs/libgnu/c-strcasecmp.c \
    $$PWD/DependLibs/libgnu/c-strncasecmp.c \
    $$PWD/DependLibs/libgnu/c-strstr.c \
    $$PWD/DependLibs/libgnu/canonicalize-lgpl.c \
    $$PWD/DependLibs/libgnu/careadlinkat.c \
    $$PWD/DependLibs/libgnu/cipher/arcfour.c \
    $$PWD/DependLibs/libgnu/cipher/blowfish.c \
    $$PWD/DependLibs/libgnu/cipher/camellia-glue.c \
    $$PWD/DependLibs/libgnu/cipher/camellia.c \
    $$PWD/DependLibs/libgnu/cipher/cast5.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-aeswrap.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-cbc.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-ccm.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-cfb.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-cmac.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-ctr.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-gcm.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-ofb.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-selftest.c \
    $$PWD/DependLibs/libgnu/cipher/cipher_list.c \
    $$PWD/DependLibs/libgnu/cipher/crc.c \
    $$PWD/DependLibs/libgnu/cipher/des.c \
    $$PWD/DependLibs/libgnu/cipher/dsa-common.c \
    $$PWD/DependLibs/libgnu/cipher/dsa.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-curves.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-ecdsa.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-eddsa.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-gost.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-misc.c \
    $$PWD/DependLibs/libgnu/cipher/ecc_cipher.c \
    $$PWD/DependLibs/libgnu/cipher/elgamal.c \
    $$PWD/DependLibs/libgnu/cipher/gost28147.c \
    $$PWD/DependLibs/libgnu/cipher/gostr3411-94.c \
    $$PWD/DependLibs/libgnu/cipher/hash-common.c \
    $$PWD/DependLibs/libgnu/cipher/hmac-tests.c \
    $$PWD/DependLibs/libgnu/cipher/idea.c \
    $$PWD/DependLibs/libgnu/cipher/kdf.c \
    $$PWD/DependLibs/libgnu/cipher/mac-cmac.c \
    $$PWD/DependLibs/libgnu/cipher/mac-gmac.c \
    $$PWD/DependLibs/libgnu/cipher/mac-hmac.c \
    $$PWD/DependLibs/libgnu/cipher/mac_cipher.c \
    $$PWD/DependLibs/libgnu/cipher/md.c \
    $$PWD/DependLibs/libgnu/cipher/md4.c \
    $$PWD/DependLibs/libgnu/cipher/md5.c \
    $$PWD/DependLibs/libgnu/cipher/md5_cypher.c \
    $$PWD/DependLibs/libgnu/cipher/primegen.c \
    $$PWD/DependLibs/libgnu/cipher/pubkey-util.c \
    $$PWD/DependLibs/libgnu/cipher/pubkey_cipher.c \
    $$PWD/DependLibs/libgnu/cipher/rfc2268.c \
    $$PWD/DependLibs/libgnu/cipher/rijndael.c \
    $$PWD/DependLibs/libgnu/cipher/rmd160.c \
    $$PWD/DependLibs/libgnu/cipher/rsa-common.c \
    $$PWD/DependLibs/libgnu/cipher/rsa.c \
    $$PWD/DependLibs/libgnu/cipher/salsa20.c \
    $$PWD/DependLibs/libgnu/cipher/scrypt.c \
    $$PWD/DependLibs/libgnu/cipher/seed.c \
    $$PWD/DependLibs/libgnu/cipher/serpent.c \
    $$PWD/DependLibs/libgnu/cipher/sha1.c \
    $$PWD/DependLibs/libgnu/cipher/sha256.c \
    $$PWD/DependLibs/libgnu/cipher/sha512.c \
    $$PWD/DependLibs/libgnu/cipher/stribog.c \
    $$PWD/DependLibs/libgnu/cipher/tiger.c \
    $$PWD/DependLibs/libgnu/cipher/twofish.c \
    $$PWD/DependLibs/libgnu/cipher/whirlpool.c \
    $$PWD/DependLibs/libgnu/cldr-plural-exp.c \
    $$PWD/DependLibs/libgnu/cldr-plural.c \
    $$PWD/DependLibs/libgnu/cldr-plurals.c \
    $$PWD/DependLibs/libgnu/clean-temp.c \
    $$PWD/DependLibs/libgnu/close.c \
    $$PWD/DependLibs/libgnu/closeout.c \
    $$PWD/DependLibs/libgnu/code-from-errno.c \
    $$PWD/DependLibs/libgnu/code-to-errno.c \
    $$PWD/DependLibs/libgnu/coding.c \
    $$PWD/DependLibs/libgnu/color.c \
    $$PWD/DependLibs/libgnu/common_gnu.c \
    $$PWD/DependLibs/libgnu/compat/clock.c \
    $$PWD/DependLibs/libgnu/compat/compat_compat.c \
    $$PWD/DependLibs/libgnu/compat/getpid.c \
    $$PWD/DependLibs/libgnu/concat-filename.c \
    $$PWD/DependLibs/libgnu/context.c \
    $$PWD/DependLibs/libgnu/copy-acl.c \
    $$PWD/DependLibs/libgnu/copy-file.c \
    $$PWD/DependLibs/libgnu/crypto-api.c \
    $$PWD/DependLibs/libgnu/crypto-backend.c \
    $$PWD/DependLibs/libgnu/crypto-selftests-pk.c \
    $$PWD/DependLibs/libgnu/crypto-selftests.c \
    $$PWD/DependLibs/libgnu/csharpcomp.c \
    $$PWD/DependLibs/libgnu/csharpexec.c \
    $$PWD/DependLibs/libgnu/dcgettext.c \
    $$PWD/DependLibs/libgnu/dcigettext.c \
    $$PWD/DependLibs/libgnu/dcngettext.c \
    $$PWD/DependLibs/libgnu/debug.c \
    $$PWD/DependLibs/libgnu/decoding.c \
    $$PWD/DependLibs/libgnu/dgettext.c \
    $$PWD/DependLibs/libgnu/dir-list.c \
    $$PWD/DependLibs/libgnu/dirname-lgpl.c \
    $$PWD/DependLibs/libgnu/dirname.c \
    $$PWD/DependLibs/libgnu/djgpp/getpwnam.c \
    $$PWD/DependLibs/libgnu/djgpp/ioctl_gnu.c \
    $$PWD/DependLibs/libgnu/djgpp/unsetenv.c \
    $$PWD/DependLibs/libgnu/dngettext.c \
    $$PWD/DependLibs/libgnu/dumpsexp.c \
    $$PWD/DependLibs/libgnu/element.c \
    $$PWD/DependLibs/libgnu/envsubst.c \
    $$PWD/DependLibs/libgnu/error-progname.c \
    $$PWD/DependLibs/libgnu/error.c \
    $$PWD/DependLibs/libgnu/errors.c \
    $$PWD/DependLibs/libgnu/estream-printf.c \
    $$PWD/DependLibs/libgnu/estream.c \
    $$PWD/DependLibs/libgnu/exitfail.c \
    $$PWD/DependLibs/libgnu/explodename.c \
    $$PWD/DependLibs/libgnu/ext/alpn.c \
    $$PWD/DependLibs/libgnu/ext/cert_type.c \
    $$PWD/DependLibs/libgnu/ext/dumbfw.c \
    $$PWD/DependLibs/libgnu/ext/ecc_ext.c \
    $$PWD/DependLibs/libgnu/ext/etm.c \
    $$PWD/DependLibs/libgnu/ext/ext_master_secret.c \
    $$PWD/DependLibs/libgnu/ext/heartbeat.c \
    $$PWD/DependLibs/libgnu/ext/max_record.c \
    $$PWD/DependLibs/libgnu/ext/safe_renegotiation.c \
    $$PWD/DependLibs/libgnu/ext/server_name.c \
    $$PWD/DependLibs/libgnu/ext/session_ticket.c \
    $$PWD/DependLibs/libgnu/ext/signature.c \
    $$PWD/DependLibs/libgnu/ext/srp_wrapper.c \
    $$PWD/DependLibs/libgnu/ext/srtp.c \
    $$PWD/DependLibs/libgnu/ext/status_request.c \
    $$PWD/DependLibs/libgnu/extras/hex.c \
    $$PWD/DependLibs/libgnu/extras/randomart.c \
    $$PWD/DependLibs/libgnu/fatal-signal.c \
    $$PWD/DependLibs/libgnu/fd-hook.c \
    $$PWD/DependLibs/libgnu/file-list.c \
    $$PWD/DependLibs/libgnu/file-ostream.c \
    $$PWD/DependLibs/libgnu/file-ostream.oo.c \
    $$PWD/DependLibs/libgnu/filter-quote.c \
    $$PWD/DependLibs/libgnu/filter-sr-latin.c \
    $$PWD/DependLibs/libgnu/finddomain.c \
    $$PWD/DependLibs/libgnu/fips.c \
    $$PWD/DependLibs/libgnu/float_gnu.c \
    $$PWD/DependLibs/libgnu/fopen.c \
    $$PWD/DependLibs/libgnu/format-awk.c \
    $$PWD/DependLibs/libgnu/format-boost.c \
    $$PWD/DependLibs/libgnu/format-c.c \
    $$PWD/DependLibs/libgnu/format-csharp.c \
    $$PWD/DependLibs/libgnu/format-elisp.c \
    $$PWD/DependLibs/libgnu/format-gcc-internal.c \
    $$PWD/DependLibs/libgnu/format-gfc-internal.c \
    $$PWD/DependLibs/libgnu/format-java.c \
    $$PWD/DependLibs/libgnu/format-javascript.c \
    $$PWD/DependLibs/libgnu/format-kde-kuit.c \
    $$PWD/DependLibs/libgnu/format-kde.c \
    $$PWD/DependLibs/libgnu/format-librep.c \
    $$PWD/DependLibs/libgnu/format-lisp.c \
    $$PWD/DependLibs/libgnu/format-lua.c \
    $$PWD/DependLibs/libgnu/format-pascal.c \
    $$PWD/DependLibs/libgnu/format-perl-brace.c \
    $$PWD/DependLibs/libgnu/format-perl.c \
    $$PWD/DependLibs/libgnu/format-php.c \
    $$PWD/DependLibs/libgnu/format-python-brace.c \
    $$PWD/DependLibs/libgnu/format-python.c \
    $$PWD/DependLibs/libgnu/format-qt-plural.c \
    $$PWD/DependLibs/libgnu/format-qt.c \
    $$PWD/DependLibs/libgnu/format-scheme.c \
    $$PWD/DependLibs/libgnu/format-sh.c \
    $$PWD/DependLibs/libgnu/format-tcl.c \
    $$PWD/DependLibs/libgnu/format-ycp.c \
    $$PWD/DependLibs/libgnu/format.c \
    $$PWD/DependLibs/libgnu/fstat.c \
    $$PWD/DependLibs/libgnu/fstrcmp.c \
    $$PWD/DependLibs/libgnu/fwriteerror.c \
    $$PWD/DependLibs/libgnu/gcd.c \
### util with main	$$PWD/DependLibs/libgnu/gcryptrnd.c \
### util with main	$$PWD/DependLibs/libgnu/gen-posix-lock-obj.c \
### util with main	$$PWD/DependLibs/libgnu/gen-w32-lock-obj.c \
    $$PWD/DependLibs/libgnu/getdelim.c \
    $$PWD/DependLibs/libgnu/getline.c \
    $$PWD/DependLibs/libgnu/getopt.c \
    $$PWD/DependLibs/libgnu/getopt1.c \
    $$PWD/DependLibs/libgnu/getrandom.c \
    $$PWD/DependLibs/libgnu/gettext-po.c \
    $$PWD/DependLibs/libgnu/gettext.c \
    $$PWD/DependLibs/libgnu/gettimeofday.c \
    $$PWD/DependLibs/libgnu/ghash.c \
    $$PWD/DependLibs/libgnu/gl_linked_list.c \
    $$PWD/DependLibs/libgnu/gl_list.c \
    $$PWD/DependLibs/libgnu/gl_xlist.c \
    $$PWD/DependLibs/libgnu/glist.c \
    $$PWD/DependLibs/libgnu/global_gnu.c \
    $$PWD/DependLibs/libgnu/gmessages.c \
    $$PWD/DependLibs/libgnu/gnutls_alert.c \
    $$PWD/DependLibs/libgnu/gnutls_anon_cred.c \
    $$PWD/DependLibs/libgnu/gnutls_asn1_tab.c \
    $$PWD/DependLibs/libgnu/gnutls_auth.c \
    $$PWD/DependLibs/libgnu/gnutls_buffers.c \
    $$PWD/DependLibs/libgnu/gnutls_cert.c \
    $$PWD/DependLibs/libgnu/gnutls_cipher.c \
    $$PWD/DependLibs/libgnu/gnutls_cipher_int.c \
    $$PWD/DependLibs/libgnu/gnutls_compress.c \
    $$PWD/DependLibs/libgnu/gnutls_constate.c \
    $$PWD/DependLibs/libgnu/gnutls_datum.c \
    $$PWD/DependLibs/libgnu/gnutls_db.c \
    $$PWD/DependLibs/libgnu/gnutls_dh.c \
    $$PWD/DependLibs/libgnu/gnutls_dtls.c \
    $$PWD/DependLibs/libgnu/gnutls_ecc.c \
    $$PWD/DependLibs/libgnu/gnutls_errors.c \
    $$PWD/DependLibs/libgnu/gnutls_extensions.c \
    $$PWD/DependLibs/libgnu/gnutls_global.c \
    $$PWD/DependLibs/libgnu/gnutls_handshake.c \
    $$PWD/DependLibs/libgnu/gnutls_hash_int.c \
    $$PWD/DependLibs/libgnu/gnutls_helper.c \
    $$PWD/DependLibs/libgnu/gnutls_kx.c \
    $$PWD/DependLibs/libgnu/gnutls_mbuffers.c \
    $$PWD/DependLibs/libgnu/gnutls_mem.c \
    $$PWD/DependLibs/libgnu/gnutls_mpi.c \
    $$PWD/DependLibs/libgnu/gnutls_num.c \
    $$PWD/DependLibs/libgnu/gnutls_pcert.c \
    $$PWD/DependLibs/libgnu/gnutls_pk.c \
    $$PWD/DependLibs/libgnu/gnutls_priority.c \
    $$PWD/DependLibs/libgnu/gnutls_privkey.c \
    $$PWD/DependLibs/libgnu/gnutls_privkey_raw.c \
    $$PWD/DependLibs/libgnu/gnutls_psk.c \
    $$PWD/DependLibs/libgnu/gnutls_pubkey.c \
    $$PWD/DependLibs/libgnu/gnutls_random.c \
    $$PWD/DependLibs/libgnu/gnutls_range.c \
    $$PWD/DependLibs/libgnu/gnutls_record.c \
    $$PWD/DependLibs/libgnu/gnutls_session.c \
    $$PWD/DependLibs/libgnu/gnutls_session_pack.c \
    $$PWD/DependLibs/libgnu/gnutls_sig.c \
    $$PWD/DependLibs/libgnu/gnutls_srp.c \
    $$PWD/DependLibs/libgnu/gnutls_state.c \
    $$PWD/DependLibs/libgnu/gnutls_str.c \
    $$PWD/DependLibs/libgnu/gnutls_supplemental.c \
    $$PWD/DependLibs/libgnu/gnutls_ui.c \
    $$PWD/DependLibs/libgnu/gnutls_v2_compat.c \
    $$PWD/DependLibs/libgnu/gnutls_x509.c \
    $$PWD/DependLibs/libgnu/gnutlsxx.cpp \
    $$PWD/DependLibs/libgnu/gpg-error.c \
    $$PWD/DependLibs/libgnu/gprimes.c \
    $$PWD/DependLibs/libgnu/gstr.c \
    $$PWD/DependLibs/libgnu/gstrfuncs.c \
    $$PWD/DependLibs/libgnu/gstring.c \
    $$PWD/DependLibs/libgnu/hard-locale.c \
    $$PWD/DependLibs/libgnu/hash-pjw-bare.c \
    $$PWD/DependLibs/libgnu/hash-pjw.c \
    $$PWD/DependLibs/libgnu/hash-string.c \
    $$PWD/DependLibs/libgnu/hash-triple.c \
    $$PWD/DependLibs/libgnu/hash.c \
    $$PWD/DependLibs/libgnu/hash_gnu.c \
    $$PWD/DependLibs/libgnu/hmac-md5.c \
    $$PWD/DependLibs/libgnu/hmac-sha1.c \
    $$PWD/DependLibs/libgnu/hmac-sha256.c \
    $$PWD/DependLibs/libgnu/hmac-sha512.c \
    $$PWD/DependLibs/libgnu/hmac256.c \
    $$PWD/DependLibs/libgnu/hostname.c \
    $$PWD/DependLibs/libgnu/hwf-arm.c \
    $$PWD/DependLibs/libgnu/hwf-x86.c \
    $$PWD/DependLibs/libgnu/hwfeatures.c \
    $$PWD/DependLibs/libgnu/iconv_close.c \
    $$PWD/DependLibs/libgnu/iconv_gnu.c \
    $$PWD/DependLibs/libgnu/iconv_open.c \
    $$PWD/DependLibs/libgnu/inet_ntop.c \
    $$PWD/DependLibs/libgnu/inet_pton.c \
    $$PWD/DependLibs/libgnu/init_gnu.c \
    $$PWD/DependLibs/libgnu/int_gnu.c \
    $$PWD/DependLibs/libgnu/intl-compat.c \
    $$PWD/DependLibs/libgnu/intl-exports.c \
    $$PWD/DependLibs/libgnu/iswblank.c \
    $$PWD/DependLibs/libgnu/itold.c \
    $$PWD/DependLibs/libgnu/its.c \
    $$PWD/DependLibs/libgnu/javacomp.c \
    $$PWD/DependLibs/libgnu/javaexec.c \
    $$PWD/DependLibs/libgnu/javaversion.c \
    $$PWD/DependLibs/libgnu/kwset.c \
    $$PWD/DependLibs/libgnu/l10nflist.c \
    $$PWD/DependLibs/libgnu/lang-table.c \
    $$PWD/DependLibs/libgnu/langprefs.c \
    $$PWD/DependLibs/libgnu/loadmsgcat.c \
    $$PWD/DependLibs/libgnu/localcharset.c \
    $$PWD/DependLibs/libgnu/localealias.c \
    $$PWD/DependLibs/libgnu/localeconv.c \
    $$PWD/DependLibs/libgnu/localename.c \
    $$PWD/DependLibs/libgnu/locating-rule.c \
    $$PWD/DependLibs/libgnu/lock_gnu.c \
    $$PWD/DependLibs/libgnu/locks.c \
    $$PWD/DependLibs/libgnu/log.c \
    $$PWD/DependLibs/libgnu/lstat.c \
    $$PWD/DependLibs/libgnu/m-fgrep.c \
    $$PWD/DependLibs/libgnu/m-regex.c \
    $$PWD/DependLibs/libgnu/malloc.c \
    $$PWD/DependLibs/libgnu/malloca.c \
    $$PWD/DependLibs/libgnu/markup.c \
    $$PWD/DependLibs/libgnu/mbchar.c \
    $$PWD/DependLibs/libgnu/mbiter.c \
    $$PWD/DependLibs/libgnu/mbrlen.c \
    $$PWD/DependLibs/libgnu/mbrtowc.c \
    $$PWD/DependLibs/libgnu/mbsinit.c \
    $$PWD/DependLibs/libgnu/mbslen.c \
    $$PWD/DependLibs/libgnu/mbsstr.c \
    $$PWD/DependLibs/libgnu/mbswidth.c \
    $$PWD/DependLibs/libgnu/mbtowc.c \
    $$PWD/DependLibs/libgnu/mbuiter.c \
    $$PWD/DependLibs/libgnu/memchr.c \
    $$PWD/DependLibs/libgnu/memmove.c \
    $$PWD/DependLibs/libgnu/message.c \
    $$PWD/DependLibs/libgnu/misc/cvsuser.c \
    $$PWD/DependLibs/libgnu/misc_gnu.c \
    $$PWD/DependLibs/libgnu/missing-string.c \
    $$PWD/DependLibs/libgnu/mkerrcodes.c \
    $$PWD/DependLibs/libgnu/mkheader.c \
    $$PWD/DependLibs/libgnu/mkw32errmap.c \
    $$PWD/DependLibs/libgnu/mkw32errmap.map.c \
    $$PWD/DependLibs/libgnu/mman_w32.c \
    $$PWD/DependLibs/libgnu/mpi/ec-ed25519.c \
    $$PWD/DependLibs/libgnu/mpi/ec.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-add1.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-lshift.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-mul1.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-mul2.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-mul3.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-rshift.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-sub1.c \
    $$PWD/DependLibs/libgnu/mpi/generic/udiv-w-sdiv.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-add.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-bit.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-cmp.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-div.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-gcd.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-inline.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-inv.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-mod.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-mpow.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-mul.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-pow.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-scan.c \
    $$PWD/DependLibs/libgnu/mpi/mpicoder.c \
    $$PWD/DependLibs/libgnu/mpi/mpih-div.c \
    $$PWD/DependLibs/libgnu/mpi/mpih-mul.c \
    $$PWD/DependLibs/libgnu/mpi/mpiutil.c \
    $$PWD/DependLibs/libgnu/mpicalc.c \
    $$PWD/DependLibs/libgnu/msgattrib.c \
    $$PWD/DependLibs/libgnu/msgcat.c \
    $$PWD/DependLibs/libgnu/msgcmp.c \
    $$PWD/DependLibs/libgnu/msgcomm.c \
    $$PWD/DependLibs/libgnu/msgconv.c \
    $$PWD/DependLibs/libgnu/msgen.c \
    $$PWD/DependLibs/libgnu/msgexec.c \
    $$PWD/DependLibs/libgnu/msgfilter.c \
    $$PWD/DependLibs/libgnu/msgfmt.c \
    $$PWD/DependLibs/libgnu/msggrep.c \
    $$PWD/DependLibs/libgnu/msginit.c \
    $$PWD/DependLibs/libgnu/msgl-ascii.c \
    $$PWD/DependLibs/libgnu/msgl-cat.c \
    $$PWD/DependLibs/libgnu/msgl-charset.c \
    $$PWD/DependLibs/libgnu/msgl-check.c \
    $$PWD/DependLibs/libgnu/msgl-english.c \
    $$PWD/DependLibs/libgnu/msgl-equal.c \
    $$PWD/DependLibs/libgnu/msgl-fsearch.c \
    $$PWD/DependLibs/libgnu/msgl-header.c \
    $$PWD/DependLibs/libgnu/msgl-iconv.c \
    $$PWD/DependLibs/libgnu/msgmerge.c \
    $$PWD/DependLibs/libgnu/msgunfmt.c \
    $$PWD/DependLibs/libgnu/msguniq.c \
    $$PWD/DependLibs/libgnu/msvc-inval.c \
    $$PWD/DependLibs/libgnu/msvc-nothrow.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta-aeads.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta-armors.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta-ciphers.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta-hashes.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-decrypt-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-decrypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-encrypt-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-encrypt-table.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-encrypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-invert-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-set-decrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-set-encrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-set-key-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes128-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes128-set-decrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes128-set-encrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes192-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes192-set-decrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes192-set-encrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes256-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes256-set-decrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes256-set-encrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aesdata.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_arcfour-crypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_arcfour.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_arctwo-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_arctwo.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base16-decode.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base16-encode.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base16-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64-decode.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64-encode.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64url-decode.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64url-encode.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64url-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_bignum-random-prime.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_bignum-random.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_bignum.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_blowfish.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_buffer-init.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_buffer.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-absorb.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-crypt-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-invert-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-table.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia128-crypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia128-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia128-set-decrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia128-set-encrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia192-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia256-crypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia256-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia256-set-decrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia256-set-encrypt-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cast128-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cast128.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cbc.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm-aes128.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm-aes192.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm-aes256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-core-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-crypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-poly1305-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-poly1305.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-set-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-set-nonce.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cipher_nettle.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cnd-copy.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ctr.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_curve25519-eh-to-x.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_curve25519-mul-g.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_curve25519-mul.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_der-iterator.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_der2dsa.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_der2rsa.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_des-compat.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_des.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_des3.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_desdata.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_drbg-aes-self-test.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_drbg-aes.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-compat-keygen.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-compat.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-gen-params.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-hash.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-keygen-fips186.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-keygen.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sha1-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sha1-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sha256-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sha256-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-validate.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa2sexp.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eax-aes128-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eax-aes128.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eax.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-192.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-224.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-25519.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-384.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-521.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-a-to-j.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-add-eh.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-add-ehh.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-add-jja.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-add-jjj.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-dup-eh.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-dup-jj.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-ecdsa-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-ecdsa-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-eh-to-a.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-hash.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-j-to-a.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mod-arith.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mod-inv.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mod.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mul-a-eh.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mul-a.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mul-g-eh.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mul-g.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-pm1-redc.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-point-mul-g.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-point-mul.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-point.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-pp1-redc.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-random.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-scalar.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-size.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eccdata.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecdsa-keygen.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecdsa-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecdsa-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ed25519-sha512-pubkey.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ed25519-sha512-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ed25519-sha512-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-compress.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-decompress.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-expand.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-hash.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-pubkey.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_egd.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_fat-arm.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_fat-x86_64.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes128-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes128.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes192-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes192.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes256-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-camellia128-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-camellia128.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-camellia256-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-camellia256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcmdata.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_getopt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_getopt1.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gmp-glue.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gosthash94-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gosthash94.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-md5.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-ripemd160.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha1.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha224.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha384.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha512.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_init_nettle.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_knuth-lfib.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_mac_nettle.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md2-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md2.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md4-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md4.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5-compat.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5-compress.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_memxor.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_memxor3.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_mini-gmp.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_mpi_nettle.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pbkdf2-hmac-sha1.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pbkdf2-hmac-sha256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pbkdf2.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pgp-encode.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pk.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-decrypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-encrypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-digest.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-md5.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-sha1.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-sha256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-sha512.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_poly1305-aes.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_poly1305-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_provable-prime.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_realloc.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ripemd160-compress.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ripemd160-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ripemd160.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rnd-common.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rnd-fips.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rnd.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-blind.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-decrypt-tr.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-decrypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-encrypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-keygen-fips186.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-keygen.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-md5-sign-tr.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-md5-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-md5-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-pkcs1-sign-tr.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-pkcs1-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-pkcs1-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha1-sign-tr.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha1-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha1-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha256-sign-tr.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha256-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha256-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha512-sign-tr.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha512-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha512-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sign-tr.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sign.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-verify.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa2openpgp.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa2sexp.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-128-set-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-256-set-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-core-internal.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-crypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-set-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-set-nonce.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20r12-crypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sec-add-1.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sec-sub-1.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sec-tabselect.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-decrypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-encrypt.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-set-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp-format.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp-transport-format.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp-transport.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp2bignum.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp2dsa.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp2rsa.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha-example.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha1-compress.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha1-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha1.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha224-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha256-compress.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha256-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-224-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-224.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-256-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-384-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-384.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-512-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-512.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-permute.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha384-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512-224-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512-256-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512-compress.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_shadata.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_twofish-meta.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_twofish.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_twofishdata.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-l2.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-l3.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-nh-n.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-nh.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-poly128.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-poly64.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-set-key.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac128.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac32.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac64.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac96.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_version.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_write-be32.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_write-le32.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_write-le64.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_yarrow256.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_yarrow_key_event.c \
    $$PWD/DependLibs/libgnu/ngettext.c \
    $$PWD/DependLibs/libgnu/nl_langinfo.c \
    $$PWD/DependLibs/libgnu/obstack.c \
    $$PWD/DependLibs/libgnu/open-catalog.c \
    $$PWD/DependLibs/libgnu/open.c \
    $$PWD/DependLibs/libgnu/opencdk/armor.c \
    $$PWD/DependLibs/libgnu/opencdk/kbnode.c \
    $$PWD/DependLibs/libgnu/opencdk/keydb.c \
    $$PWD/DependLibs/libgnu/opencdk/literal.c \
    $$PWD/DependLibs/libgnu/opencdk/misc_opencdk.c \
    $$PWD/DependLibs/libgnu/opencdk/new-packet.c \
    $$PWD/DependLibs/libgnu/opencdk/pubkey_pgp.c \
    $$PWD/DependLibs/libgnu/opencdk/read-packet.c \
    $$PWD/DependLibs/libgnu/opencdk/seskey.c \
    $$PWD/DependLibs/libgnu/opencdk/sig-check.c \
    $$PWD/DependLibs/libgnu/opencdk/stream.c \
    $$PWD/DependLibs/libgnu/opencdk/write-packet.c \
    $$PWD/DependLibs/libgnu/openpgp/compat_pgp.c \
    $$PWD/DependLibs/libgnu/openpgp/extras.c \
    $$PWD/DependLibs/libgnu/openpgp/gnutls_openpgp.c \
    $$PWD/DependLibs/libgnu/openpgp/output_pgp.c \
    $$PWD/DependLibs/libgnu/openpgp/pgp.c \
    $$PWD/DependLibs/libgnu/openpgp/pgpverify.c \
    $$PWD/DependLibs/libgnu/openpgp/privkey_pgp.c \
    $$PWD/DependLibs/libgnu/osdep.c \
    $$PWD/DependLibs/libgnu/ostream.c \
    $$PWD/DependLibs/libgnu/ostream.oo.c \
    $$PWD/DependLibs/libgnu/parser_aux.c \
    $$PWD/DependLibs/libgnu/pin.c \
    $$PWD/DependLibs/libgnu/pkcs11.c \
    $$PWD/DependLibs/libgnu/pkcs11_int.c \
    $$PWD/DependLibs/libgnu/pkcs11_privkey.c \
    $$PWD/DependLibs/libgnu/pkcs11_secret.c \
    $$PWD/DependLibs/libgnu/pkcs11_write.c \
    $$PWD/DependLibs/libgnu/pkcs11x.c \
    $$PWD/DependLibs/libgnu/pkix_asn1_tab.c \
    $$PWD/DependLibs/libgnu/plural-count.c \
    $$PWD/DependLibs/libgnu/plural-eval.c \
    $$PWD/DependLibs/libgnu/plural-exp.c \
    $$PWD/DependLibs/libgnu/plural-table.c \
    $$PWD/DependLibs/libgnu/plural.c \
    $$PWD/DependLibs/libgnu/po-charset.c \
    $$PWD/DependLibs/libgnu/po-error.c \
    $$PWD/DependLibs/libgnu/po-gram-gen.c \
    $$PWD/DependLibs/libgnu/po-lex.c \
    $$PWD/DependLibs/libgnu/po-time.c \
    $$PWD/DependLibs/libgnu/po-xerror.c \
    $$PWD/DependLibs/libgnu/posix-lock.c \
    $$PWD/DependLibs/libgnu/posix-thread.c \
    $$PWD/DependLibs/libgnu/printf-args.c \
    $$PWD/DependLibs/libgnu/printf-parse.c \
    $$PWD/DependLibs/libgnu/printf.c \
    $$PWD/DependLibs/libgnu/progname.c \
    $$PWD/DependLibs/libgnu/progreloc.c \
    $$PWD/DependLibs/libgnu/propername.c \
    $$PWD/DependLibs/libgnu/raise.c \
    $$PWD/DependLibs/libgnu/random-csprng.c \
    $$PWD/DependLibs/libgnu/random-daemon.c \
    $$PWD/DependLibs/libgnu/random-fips.c \
    $$PWD/DependLibs/libgnu/random-system.c \
    $$PWD/DependLibs/libgnu/random_gnu.c \
    $$PWD/DependLibs/libgnu/rawmemchr.c \
    $$PWD/DependLibs/libgnu/read-catalog-abstract.c \
    $$PWD/DependLibs/libgnu/read-catalog.c \
    $$PWD/DependLibs/libgnu/read-csharp.c \
    $$PWD/DependLibs/libgnu/read-desktop.c \
    $$PWD/DependLibs/libgnu/read-file-gnu.c \
    $$PWD/DependLibs/libgnu/read-file.c \
    $$PWD/DependLibs/libgnu/read-java.c \
    $$PWD/DependLibs/libgnu/read-mo.c \
    $$PWD/DependLibs/libgnu/read-po.c \
    $$PWD/DependLibs/libgnu/read-properties.c \
    $$PWD/DependLibs/libgnu/read-resources.c \
    $$PWD/DependLibs/libgnu/read-stringtable.c \
    $$PWD/DependLibs/libgnu/read-tcl.c \
    $$PWD/DependLibs/libgnu/readlink.c \
    $$PWD/DependLibs/libgnu/realloc.c \
    $$PWD/DependLibs/libgnu/recode-sr-latin.c \
    $$PWD/DependLibs/libgnu/regcomp.c \
    $$PWD/DependLibs/libgnu/regex.c \
    $$PWD/DependLibs/libgnu/regex_internal.c \
    $$PWD/DependLibs/libgnu/regexec.c \
    $$PWD/DependLibs/libgnu/relocatable.c \
    $$PWD/DependLibs/libgnu/relocwrapper.c \
    $$PWD/DependLibs/libgnu/rndegd.c \
    $$PWD/DependLibs/libgnu/rndhw.c \
    $$PWD/DependLibs/libgnu/rndlinux.c \
    $$PWD/DependLibs/libgnu/rndunix.c \
    $$PWD/DependLibs/libgnu/rndw32.c \
    $$PWD/DependLibs/libgnu/rndw32ce.c \
    $$PWD/DependLibs/libgnu/safe-memfuncs.c \
    $$PWD/DependLibs/libgnu/same.c \
    $$PWD/DependLibs/libgnu/search-path.c \
    $$PWD/DependLibs/libgnu/secmem_gnu.c \
    $$PWD/DependLibs/libgnu/sentence.c \
    $$PWD/DependLibs/libgnu/setenv.c \
    $$PWD/DependLibs/libgnu/setlocale.c \
    $$PWD/DependLibs/libgnu/sexp_gnu.c \
    $$PWD/DependLibs/libgnu/sigprocmask.c \
    $$PWD/DependLibs/libgnu/stat.c \
    $$PWD/DependLibs/libgnu/stdio-write.c \
    $$PWD/DependLibs/libgnu/stdmem.c \
    $$PWD/DependLibs/libgnu/stpcpy.c \
    $$PWD/DependLibs/libgnu/stpncpy.c \
    $$PWD/DependLibs/libgnu/str-list.c \
    $$PWD/DependLibs/libgnu/strchrnul.c \
    $$PWD/DependLibs/libgnu/strerror-override.c \
    $$PWD/DependLibs/libgnu/strerror-sym.c \
    $$PWD/DependLibs/libgnu/strerror.c \
    $$PWD/DependLibs/libgnu/striconv.c \
    $$PWD/DependLibs/libgnu/striconveh.c \
    $$PWD/DependLibs/libgnu/striconveha.c \
    $$PWD/DependLibs/libgnu/strnlen.c \
    $$PWD/DependLibs/libgnu/strnlen1.c \
    $$PWD/DependLibs/libgnu/strsource-sym.c \
    $$PWD/DependLibs/libgnu/strsource.c \
    $$PWD/DependLibs/libgnu/strstr.c \
    $$PWD/DependLibs/libgnu/strtol.c \
    $$PWD/DependLibs/libgnu/strtoul.c \
    $$PWD/DependLibs/libgnu/structure.c \
    $$PWD/DependLibs/libgnu/styled-ostream.c \
    $$PWD/DependLibs/libgnu/styled-ostream.oo.c \
    $$PWD/DependLibs/libgnu/system-keys-dummy.c \
    $$PWD/DependLibs/libgnu/system-keys-win.c \
    $$PWD/DependLibs/libgnu/system.c \
    $$PWD/DependLibs/libgnu/system_override.c \
    $$PWD/DependLibs/libgnu/textdomain.c \
    $$PWD/DependLibs/libgnu/threadlib_gnu.c \
    $$PWD/DependLibs/libgnu/tmpdir.c \
    $$PWD/DependLibs/libgnu/tpm.c \
    $$PWD/DependLibs/libgnu/trim.c \
    $$PWD/DependLibs/libgnu/tsearch.c \
    $$PWD/DependLibs/libgnu/u64.c \
    $$PWD/DependLibs/libgnu/unictype/ctype_alpha.c \
    $$PWD/DependLibs/libgnu/unictype/ctype_space.c \
    $$PWD/DependLibs/libgnu/unistd_gnu.c \
    $$PWD/DependLibs/libgnu/unistr/u8-mbtoucr.c \
    $$PWD/DependLibs/libgnu/unistr/u8-uctomb-aux.c \
    $$PWD/DependLibs/libgnu/unistr/u8-uctomb.c \
    $$PWD/DependLibs/libgnu/uniwidth/width.c \
    $$PWD/DependLibs/libgnu/urlget.c \
    $$PWD/DependLibs/libgnu/urls.c \
    $$PWD/DependLibs/libgnu/vasnprintf.c \
    $$PWD/DependLibs/libgnu/vasprintf.c \
    $$PWD/DependLibs/libgnu/verify-tofu.c \
    $$PWD/DependLibs/libgnu/version_ans.c \
    $$PWD/DependLibs/libgnu/version_libgnu.c \
    $$PWD/DependLibs/libgnu/visibility_gnu.c \
    $$PWD/DependLibs/libgnu/w32-gettext.c \
    $$PWD/DependLibs/libgnu/w32-lock.c \
    $$PWD/DependLibs/libgnu/w32-thread.c \
    $$PWD/DependLibs/libgnu/wcrtomb.c \
    $$PWD/DependLibs/libgnu/wctype-h.c \
    $$PWD/DependLibs/libgnu/wcwidth.c \
    $$PWD/DependLibs/libgnu/write-catalog.c \
    $$PWD/DependLibs/libgnu/write-csharp.c \
    $$PWD/DependLibs/libgnu/write-desktop.c \
    $$PWD/DependLibs/libgnu/write-java.c \
    $$PWD/DependLibs/libgnu/write-mo.c \
    $$PWD/DependLibs/libgnu/write-po.c \
    $$PWD/DependLibs/libgnu/write-properties.c \
    $$PWD/DependLibs/libgnu/write-qt.c \
    $$PWD/DependLibs/libgnu/write-resources.c \
    $$PWD/DependLibs/libgnu/write-stringtable.c \
    $$PWD/DependLibs/libgnu/write-tcl.c \
    $$PWD/DependLibs/libgnu/write-xml.c \
    $$PWD/DependLibs/libgnu/x-awk.c \
    $$PWD/DependLibs/libgnu/x-c.c \
    $$PWD/DependLibs/libgnu/x-csharp.c \
    $$PWD/DependLibs/libgnu/x-desktop.c \
    $$PWD/DependLibs/libgnu/x-elisp.c \
    $$PWD/DependLibs/libgnu/x-java.c \
    $$PWD/DependLibs/libgnu/x-javascript.c \
    $$PWD/DependLibs/libgnu/x-librep.c \
    $$PWD/DependLibs/libgnu/x-lisp.c \
    $$PWD/DependLibs/libgnu/x-lua.c \
    $$PWD/DependLibs/libgnu/x-perl.c \
    $$PWD/DependLibs/libgnu/x-php.c \
    $$PWD/DependLibs/libgnu/x-po.c \
    $$PWD/DependLibs/libgnu/x-python.c \
    $$PWD/DependLibs/libgnu/x-rst.c \
    $$PWD/DependLibs/libgnu/x-scheme.c \
    $$PWD/DependLibs/libgnu/x-sh.c \
    $$PWD/DependLibs/libgnu/x-smalltalk.c \
    $$PWD/DependLibs/libgnu/x-tcl.c \
    $$PWD/DependLibs/libgnu/x-vala.c \
    $$PWD/DependLibs/libgnu/x-ycp.c \
    $$PWD/DependLibs/libgnu/x509/crl.c \
    $$PWD/DependLibs/libgnu/x509/crl_write.c \
    $$PWD/DependLibs/libgnu/x509/crq.c \
    $$PWD/DependLibs/libgnu/x509/dn.c \
    $$PWD/DependLibs/libgnu/x509/email-verify.c \
    $$PWD/DependLibs/libgnu/x509/extensions.c \
    $$PWD/DependLibs/libgnu/x509/gnutls_common.c \
    $$PWD/DependLibs/libgnu/x509/hostname-verify.c \
    $$PWD/DependLibs/libgnu/x509/key_decode.c \
    $$PWD/DependLibs/libgnu/x509/key_encode.c \
    $$PWD/DependLibs/libgnu/x509/mpi_x509.c \
    $$PWD/DependLibs/libgnu/x509/name_constraints.c \
    $$PWD/DependLibs/libgnu/x509/ocsp.c \
    $$PWD/DependLibs/libgnu/x509/ocsp_output.c \
    $$PWD/DependLibs/libgnu/x509/output_x509.c \
    $$PWD/DependLibs/libgnu/x509/pkcs12.c \
    $$PWD/DependLibs/libgnu/x509/pkcs12_bag.c \
    $$PWD/DependLibs/libgnu/x509/pkcs12_encr.c \
    $$PWD/DependLibs/libgnu/x509/privkey_openssl.c \
    $$PWD/DependLibs/libgnu/x509/privkey_pkcs8.c \
    $$PWD/DependLibs/libgnu/x509/privkey_x509.c \
    $$PWD/DependLibs/libgnu/x509/sign_x509.c \
    $$PWD/DependLibs/libgnu/x509/verify-high.c \
    $$PWD/DependLibs/libgnu/x509/verify-high2.c \
    $$PWD/DependLibs/libgnu/x509/verify_x509.c \
    $$PWD/DependLibs/libgnu/x509/x509.c \
    $$PWD/DependLibs/libgnu/x509/x509_dn.c \
    $$PWD/DependLibs/libgnu/x509/x509_ext.c \
    $$PWD/DependLibs/libgnu/x509/x509_write.c \
    $$PWD/DependLibs/libgnu/x509_b64.c \
    $$PWD/DependLibs/libgnu/xasprintf.c \
    $$PWD/DependLibs/libgnu/xconcat-filename.c \
    $$PWD/DependLibs/libgnu/xerror.c \
    $$PWD/DependLibs/libgnu/xgettext.c \
    $$PWD/DependLibs/libgnu/xmalloc.c \
    $$PWD/DependLibs/libgnu/xmalloca.c \
    $$PWD/DependLibs/libgnu/xreadlink.c \
    $$PWD/DependLibs/libgnu/xsize_gnu.c \
    $$PWD/DependLibs/libgnu/xstrdup.c \
    $$PWD/DependLibs/libgnu/xstriconv.c \
    $$PWD/DependLibs/libgnu/xvasprintf.c \
    $$PWD/DependLibs/libgnu/os2compat2.c

