DEFINES += GLIB_COMPILATION _MBCS __need_nettle_getopt

INCLUDEPATH += $$PWD/DependLibs/libgnu

HEADERS += 	$$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvTargetOsConfig.h \
    $$PWD/DependLibs/libgnu/abstract_gnu.h \
    $$PWD/DependLibs/libgnu/accelerated/accelerated.h \
    $$PWD/DependLibs/libgnu/accelerated/cryptodev.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-aead.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-padlock.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-x86.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/sha-padlock.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/sha-x86.h \
    $$PWD/DependLibs/libgnu/accelerated/x86/x86-common.h \
    $$PWD/DependLibs/libgnu/algorithms_gnu.h \
    $$PWD/DependLibs/libgnu/alignof.h \
    $$PWD/DependLibs/libgnu/alloca.in.h \
    $$PWD/DependLibs/libgnu/alloca_gnu.h \
    $$PWD/DependLibs/libgnu/alloca_gnu.in.h \
    $$PWD/DependLibs/libgnu/allocator.h \
    $$PWD/DependLibs/libgnu/areadlink.h \
    $$PWD/DependLibs/libgnu/arg-nonnull.h \
    $$PWD/DependLibs/libgnu/atfork.h \
    $$PWD/DependLibs/libgnu/ath.h \
    $$PWD/DependLibs/libgnu/auth/anon.h \
    $$PWD/DependLibs/libgnu/auth/cert.h \
    $$PWD/DependLibs/libgnu/auth/dh_common.h \
    $$PWD/DependLibs/libgnu/auth/ecdhe.h \
    $$PWD/DependLibs/libgnu/auth/psk.h \
    $$PWD/DependLibs/libgnu/auth/psk_passwd.h \
    $$PWD/DependLibs/libgnu/auth/rsa_common.h \
    $$PWD/DependLibs/libgnu/auth/srp_auth.h \
    $$PWD/DependLibs/libgnu/auth/srp_passwd.h \
    $$PWD/DependLibs/libgnu/base64_gnu.h \
    $$PWD/DependLibs/libgnu/basename.h \
    $$PWD/DependLibs/libgnu/binary-io.h \
    $$PWD/DependLibs/libgnu/bitrotate.h \
    $$PWD/DependLibs/libgnu/c++defs.h \
    $$PWD/DependLibs/libgnu/c-ctype.h \
    $$PWD/DependLibs/libgnu/c-strcase.h \
    $$PWD/DependLibs/libgnu/c-strcaseeq.h \
    $$PWD/DependLibs/libgnu/c-strstr.h \
    $$PWD/DependLibs/libgnu/careadlinkat.h \
    $$PWD/DependLibs/libgnu/cipher-proto.h \
    $$PWD/DependLibs/libgnu/cipher.h \
    $$PWD/DependLibs/libgnu/cipher/bithelp.h \
    $$PWD/DependLibs/libgnu/cipher/bufhelp.h \
    $$PWD/DependLibs/libgnu/cipher/camellia.h \
    $$PWD/DependLibs/libgnu/cipher/cipher-internal.h \
    $$PWD/DependLibs/libgnu/cipher/cipher-selftest.h \
    $$PWD/DependLibs/libgnu/cipher/ecc-common.h \
    $$PWD/DependLibs/libgnu/cipher/gost.h \
    $$PWD/DependLibs/libgnu/cipher/hash-common.h \
    $$PWD/DependLibs/libgnu/cipher/kdf-internal.h \
    $$PWD/DependLibs/libgnu/cipher/mac-internal.h \
    $$PWD/DependLibs/libgnu/cipher/pubkey-internal.h \
    $$PWD/DependLibs/libgnu/cipher/rijndael-tables.h \
    $$PWD/DependLibs/libgnu/cipher/rmd.h \
    $$PWD/DependLibs/libgnu/cldr-plural-exp.h \
    $$PWD/DependLibs/libgnu/cldr-plural.h \
    $$PWD/DependLibs/libgnu/clean-temp.h \
    $$PWD/DependLibs/libgnu/closeout.h \
    $$PWD/DependLibs/libgnu/code-from-errno.h \
    $$PWD/DependLibs/libgnu/code-to-errno.h \
    $$PWD/DependLibs/libgnu/color.h \
    $$PWD/DependLibs/libgnu/common_gnu.h \
    $$PWD/DependLibs/libgnu/compat.h \
    $$PWD/DependLibs/libgnu/compat/libcompat.h \
    $$PWD/DependLibs/libgnu/concat-filename.h \
    $$PWD/DependLibs/libgnu/config_libgnu.h \
    $$PWD/DependLibs/libgnu/context.h \
    $$PWD/DependLibs/libgnu/copy-file.h \
    $$PWD/DependLibs/libgnu/crypto-backend.h \
    $$PWD/DependLibs/libgnu/crypto.h \
    $$PWD/DependLibs/libgnu/csharpcomp.h \
    $$PWD/DependLibs/libgnu/csharpexec.h \
    $$PWD/DependLibs/libgnu/debug.h \
    $$PWD/DependLibs/libgnu/diffseq.h \
    $$PWD/DependLibs/libgnu/dir-list.h \
    $$PWD/DependLibs/libgnu/dirname.h \
    $$PWD/DependLibs/libgnu/djgpp/djpwd.h \
    $$PWD/DependLibs/libgnu/djgpp/ioctl_gnu.h \
    $$PWD/DependLibs/libgnu/dosname.h \
    $$PWD/DependLibs/libgnu/dtls.h \
    $$PWD/DependLibs/libgnu/ec-context.h \
    $$PWD/DependLibs/libgnu/element.h \
    $$PWD/DependLibs/libgnu/err-codes-sym.h \
    $$PWD/DependLibs/libgnu/err-codes.h \
    $$PWD/DependLibs/libgnu/err-sources-sym.h \
    $$PWD/DependLibs/libgnu/err-sources.h \
    $$PWD/DependLibs/libgnu/errno.in.h \
    $$PWD/DependLibs/libgnu/errnos-sym.h \
    $$PWD/DependLibs/libgnu/error-progname.h \
    $$PWD/DependLibs/libgnu/error.h \
    $$PWD/DependLibs/libgnu/estream-printf.h \
    $$PWD/DependLibs/libgnu/eval-plural.h \
    $$PWD/DependLibs/libgnu/exitfail.h \
    $$PWD/DependLibs/libgnu/export.h \
    $$PWD/DependLibs/libgnu/ext/alpn.h \
    $$PWD/DependLibs/libgnu/ext/cert_type.h \
    $$PWD/DependLibs/libgnu/ext/dumbfw.h \
    $$PWD/DependLibs/libgnu/ext/ecc_ext.h \
    $$PWD/DependLibs/libgnu/ext/etm.h \
    $$PWD/DependLibs/libgnu/ext/ext_master_secret.h \
    $$PWD/DependLibs/libgnu/ext/heartbeat.h \
    $$PWD/DependLibs/libgnu/ext/max_record.h \
    $$PWD/DependLibs/libgnu/ext/safe_renegotiation.h \
    $$PWD/DependLibs/libgnu/ext/server_name.h \
    $$PWD/DependLibs/libgnu/ext/session_ticket.h \
    $$PWD/DependLibs/libgnu/ext/signature.h \
    $$PWD/DependLibs/libgnu/ext/srp_wrapper.h \
    $$PWD/DependLibs/libgnu/ext/srtp.h \
    $$PWD/DependLibs/libgnu/ext/status_request.h \
    $$PWD/DependLibs/libgnu/extras/hex.h \
    $$PWD/DependLibs/libgnu/extras/randomart.h \
    $$PWD/DependLibs/libgnu/fatal-signal.h \
    $$PWD/DependLibs/libgnu/fcntl_gnu.in.h \
    $$PWD/DependLibs/libgnu/fcntl_gnu.h \
    $$PWD/DependLibs/libgnu/fd-hook.h \
    $$PWD/DependLibs/libgnu/file-list.h \
    $$PWD/DependLibs/libgnu/file-ostream.h \
    $$PWD/DependLibs/libgnu/file-ostream.oo.h \
    $$PWD/DependLibs/libgnu/file_ostream.priv.h \
    $$PWD/DependLibs/libgnu/file_ostream.vt.h \
    $$PWD/DependLibs/libgnu/filename.h \
    $$PWD/DependLibs/libgnu/filters.h \
    $$PWD/DependLibs/libgnu/fips.h \
    $$PWD/DependLibs/libgnu/float_gnu.h \
    $$PWD/DependLibs/libgnu/fnmatch.h \
    $$PWD/DependLibs/libgnu/format-c-parse.h \
    $$PWD/DependLibs/libgnu/format-invalid.h \
    $$PWD/DependLibs/libgnu/format.h \
    $$PWD/DependLibs/libgnu/fstrcmp.h \
    $$PWD/DependLibs/libgnu/fwriteerror.h \
    $$PWD/DependLibs/libgnu/g-gnulib.h \
    $$PWD/DependLibs/libgnu/g10lib.h \
    $$PWD/DependLibs/libgnu/gcd.h \
    $$PWD/DependLibs/libgnu/gcrypt-int.h \
    $$PWD/DependLibs/libgnu/gcrypt.h \
    $$PWD/DependLibs/libgnu/getopt.h \
    $$PWD/DependLibs/libgnu/getopt.in.h \
    $$PWD/DependLibs/libgnu/getopt_int.h \
    $$PWD/DependLibs/libgnu/gettext-po.h \
    $$PWD/DependLibs/libgnu/gettext-po.in.h \
    $$PWD/DependLibs/libgnu/gettext.h \
    $$PWD/DependLibs/libgnu/gettextP.h \
    $$PWD/DependLibs/libgnu/ghash.h \
    $$PWD/DependLibs/libgnu/gl_anylinked_list1.h \
    $$PWD/DependLibs/libgnu/gl_anylinked_list2.h \
    $$PWD/DependLibs/libgnu/gl_linked_list.h \
    $$PWD/DependLibs/libgnu/gl_list.h \
    $$PWD/DependLibs/libgnu/gl_xlist.h \
    $$PWD/DependLibs/libgnu/glib.h \
    $$PWD/DependLibs/libgnu/glist.h \
    $$PWD/DependLibs/libgnu/gmo.h \
    $$PWD/DependLibs/libgnu/gnutls.h \
    $$PWD/DependLibs/libgnu/gnutls_auth.h \
    $$PWD/DependLibs/libgnu/gnutls_buffers.h \
    $$PWD/DependLibs/libgnu/gnutls_cipher.h \
    $$PWD/DependLibs/libgnu/gnutls_cipher_int.h \
    $$PWD/DependLibs/libgnu/gnutls_compress.h \
    $$PWD/DependLibs/libgnu/gnutls_constate.h \
    $$PWD/DependLibs/libgnu/gnutls_crypto.h \
    $$PWD/DependLibs/libgnu/gnutls_datum.h \
    $$PWD/DependLibs/libgnu/gnutls_db.h \
    $$PWD/DependLibs/libgnu/gnutls_dh.h \
    $$PWD/DependLibs/libgnu/gnutls_dtls.h \
    $$PWD/DependLibs/libgnu/gnutls_ecc.h \
    $$PWD/DependLibs/libgnu/gnutls_errors.h \
    $$PWD/DependLibs/libgnu/gnutls_extensions.h \
    $$PWD/DependLibs/libgnu/gnutls_global.h \
    $$PWD/DependLibs/libgnu/gnutls_handshake.h \
    $$PWD/DependLibs/libgnu/gnutls_hash_int.h \
    $$PWD/DependLibs/libgnu/gnutls_helper.h \
    $$PWD/DependLibs/libgnu/gnutls_int.h \
    $$PWD/DependLibs/libgnu/gnutls_kx.h \
    $$PWD/DependLibs/libgnu/gnutls_mbuffers.h \
    $$PWD/DependLibs/libgnu/gnutls_mem.h \
    $$PWD/DependLibs/libgnu/gnutls_mpi.h \
    $$PWD/DependLibs/libgnu/gnutls_num.h \
    $$PWD/DependLibs/libgnu/gnutls_pk.h \
    $$PWD/DependLibs/libgnu/gnutls_random.h \
    $$PWD/DependLibs/libgnu/gnutls_record.h \
    $$PWD/DependLibs/libgnu/gnutls_session_pack.h \
    $$PWD/DependLibs/libgnu/gnutls_sig.h \
    $$PWD/DependLibs/libgnu/gnutls_srp.h \
    $$PWD/DependLibs/libgnu/gnutls_state.h \
    $$PWD/DependLibs/libgnu/gnutls_str.h \
    $$PWD/DependLibs/libgnu/gnutls_str_array.h \
    $$PWD/DependLibs/libgnu/gnutls_supplemental.h \
    $$PWD/DependLibs/libgnu/gnutls_urls.h \
    $$PWD/DependLibs/libgnu/gnutls_v2_compat.h \
    $$PWD/DependLibs/libgnu/gnutls_x509.h \
    $$PWD/DependLibs/libgnu/gnutlsxx.h \
    $$PWD/DependLibs/libgnu/gpg-error.h \
    $$PWD/DependLibs/libgnu/gpgrt-int.h \
    $$PWD/DependLibs/libgnu/gprimes.h \
    $$PWD/DependLibs/libgnu/gstr.h \
    $$PWD/DependLibs/libgnu/gstrfuncs.h \
    $$PWD/DependLibs/libgnu/gstring.h \
    $$PWD/DependLibs/libgnu/gtypes.h \
    $$PWD/DependLibs/libgnu/hard-locale.h \
    $$PWD/DependLibs/libgnu/hash-pjw-bare.h \
    $$PWD/DependLibs/libgnu/hash-pjw.h \
    $$PWD/DependLibs/libgnu/hash-string.h \
    $$PWD/DependLibs/libgnu/hash-triple.h \
    $$PWD/DependLibs/libgnu/hash.h \
    $$PWD/DependLibs/libgnu/hash_gnu.h \
    $$PWD/DependLibs/libgnu/hmac.h \
    $$PWD/DependLibs/libgnu/hmac256.h \
    $$PWD/DependLibs/libgnu/hwf-common.h \
    $$PWD/DependLibs/libgnu/iconv.h \
    $$PWD/DependLibs/libgnu/iconv.in.h \
    $$PWD/DependLibs/libgnu/iconv_gnu.h \
    $$PWD/DependLibs/libgnu/iconv_open-aix.h \
    $$PWD/DependLibs/libgnu/iconv_open-hpux.h \
    $$PWD/DependLibs/libgnu/iconv_open-irix.h \
    $$PWD/DependLibs/libgnu/iconv_open-osf.h \
    $$PWD/DependLibs/libgnu/iconv_open-solaris.h \
    $$PWD/DependLibs/libgnu/iconveh.h \
    $$PWD/DependLibs/libgnu/init_gnu.h \
    $$PWD/DependLibs/libgnu/intprops.h \
    $$PWD/DependLibs/libgnu/its.h \
    $$PWD/DependLibs/libgnu/javacomp.h \
    $$PWD/DependLibs/libgnu/javaexec.h \
    $$PWD/DependLibs/libgnu/javaversion.h \
    $$PWD/DependLibs/libgnu/kwset.h \
    $$PWD/DependLibs/libgnu/lang-table.h \
    $$PWD/DependLibs/libgnu/langinfo.h \
    $$PWD/DependLibs/libgnu/langinfo.in.h \
    $$PWD/DependLibs/libgnu/libcharset.h \
    $$PWD/DependLibs/libgnu/libgnuintl.h \
    $$PWD/DependLibs/libgnu/libgnuintl.in.h \
    $$PWD/DependLibs/libgnu/libgrep.h \
    $$PWD/DependLibs/libgnu/libintl.h \
    $$PWD/DependLibs/libgnu/libtasn1.h \
    $$PWD/DependLibs/libgnu/loadinfo.h \
    $$PWD/DependLibs/libgnu/localcharset.h \
    $$PWD/DependLibs/libgnu/locale_gnu.h \
    $$PWD/DependLibs/libgnu/locale_gnu.in.h \
    $$PWD/DependLibs/libgnu/localename.h \
    $$PWD/DependLibs/libgnu/locating-rule.h \
    $$PWD/DependLibs/libgnu/lock_gnu.h \
    $$PWD/DependLibs/libgnu/locks.h \
    $$PWD/DependLibs/libgnu/malloca.h \
    $$PWD/DependLibs/libgnu/markup.h \
    $$PWD/DependLibs/libgnu/mbchar.h \
    $$PWD/DependLibs/libgnu/mbiter.h \
    $$PWD/DependLibs/libgnu/mbswidth.h \
    $$PWD/DependLibs/libgnu/mbtowc-impl.h \
    $$PWD/DependLibs/libgnu/mbuiter.h \
    $$PWD/DependLibs/libgnu/message.h \
    $$PWD/DependLibs/libgnu/minmax.h \
    $$PWD/DependLibs/libgnu/mkerrcodes.h \
    $$PWD/DependLibs/libgnu/mman_w32.h \
    $$PWD/DependLibs/libgnu/moo.h \
    $$PWD/DependLibs/libgnu/mpi.h \
    $$PWD/DependLibs/libgnu/mpi/asm-syntax.h \
    $$PWD/DependLibs/libgnu/mpi/ec-internal.h \
    $$PWD/DependLibs/libgnu/mpi/generic/mpi-asm-defs.h \
    $$PWD/DependLibs/libgnu/mpi/longlong.h \
    $$PWD/DependLibs/libgnu/mpi/mod-source-info.h \
    $$PWD/DependLibs/libgnu/mpi/mpi-inline.h \
    $$PWD/DependLibs/libgnu/mpi/mpi-internal.h \
    $$PWD/DependLibs/libgnu/mpi/sysdep.h \
    $$PWD/DependLibs/libgnu/msgfmt.h \
    $$PWD/DependLibs/libgnu/msgl-ascii.h \
    $$PWD/DependLibs/libgnu/msgl-cat.h \
    $$PWD/DependLibs/libgnu/msgl-charset.h \
    $$PWD/DependLibs/libgnu/msgl-check.h \
    $$PWD/DependLibs/libgnu/msgl-english.h \
    $$PWD/DependLibs/libgnu/msgl-equal.h \
    $$PWD/DependLibs/libgnu/msgl-fsearch.h \
    $$PWD/DependLibs/libgnu/msgl-header.h \
    $$PWD/DependLibs/libgnu/msgl-iconv.h \
    $$PWD/DependLibs/libgnu/msgunfmt.h \
    $$PWD/DependLibs/libgnu/msvc-inval.h \
    $$PWD/DependLibs/libgnu/msvc-nothrow.h \
    $$PWD/DependLibs/libgnu/nettle/config_nettle.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-stdint.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-types.h \
    $$PWD/DependLibs/libgnu/nettle/nettle-write.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_arcfour.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_arctwo.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_asn1.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_base16.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_bignum.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_blowfish.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_buffer.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_cast128.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_cast128_sboxes.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_cbc.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-poly1305.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ctr.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_curve25519.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_des-compat.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_des.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_desCode.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_desinfo.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_drbg-aes.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-compat.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-fips.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_eax.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-192.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-224.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-25519.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-256.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-384.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-521.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-curve.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecdsa.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_egd.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_fat-setup.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_getopt.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_getopt_int.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_gmp-glue.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_gosthash94.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_keymap.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_knuth-lfib.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_macros.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_md2.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_md4.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5-compat.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_memxor-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_memxor.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_mini-gmp.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_pbkdf2.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_pgp.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_poly1305.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_realloc.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_ripemd160.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_rnd-common.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_rotors.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-fips.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-internal.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha1.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha2.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_twofish.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_version.h \
    $$PWD/DependLibs/libgnu/nettle/nettle_yarrow.h \
    $$PWD/DependLibs/libgnu/obstack.h \
    $$PWD/DependLibs/libgnu/ocsp.h \
    $$PWD/DependLibs/libgnu/open-catalog.h \
    $$PWD/DependLibs/libgnu/opencdk/context.h \
    $$PWD/DependLibs/libgnu/opencdk/filters_opencdk.h \
    $$PWD/DependLibs/libgnu/opencdk/keydb.h \
    $$PWD/DependLibs/libgnu/opencdk/main.h \
    $$PWD/DependLibs/libgnu/opencdk/opencdk.h \
    $$PWD/DependLibs/libgnu/opencdk/packet.h \
    $$PWD/DependLibs/libgnu/opencdk/stream.h \
    $$PWD/DependLibs/libgnu/opencdk/types_opencdk.h \
    $$PWD/DependLibs/libgnu/openpgp.h \
    $$PWD/DependLibs/libgnu/openpgp/gnutls_openpgp.h \
    $$PWD/DependLibs/libgnu/openpgp/openpgp_int.h \
    $$PWD/DependLibs/libgnu/os2compat.h \
    $$PWD/DependLibs/libgnu/ostream.h \
    $$PWD/DependLibs/libgnu/ostream.oo.h \
    $$PWD/DependLibs/libgnu/ostream.priv.h \
    $$PWD/DependLibs/libgnu/ostream.vt.h \
    $$PWD/DependLibs/libgnu/parser_aux.h \
    $$PWD/DependLibs/libgnu/pathmax.h \
    $$PWD/DependLibs/libgnu/pin.h \
    $$PWD/DependLibs/libgnu/pkcs11.h \
    $$PWD/DependLibs/libgnu/pkcs11_int.h \
    $$PWD/DependLibs/libgnu/pkcs11x.h \
    $$PWD/DependLibs/libgnu/pkcs12.h \
    $$PWD/DependLibs/libgnu/pkcs7.h \
    $$PWD/DependLibs/libgnu/plural-count.h \
    $$PWD/DependLibs/libgnu/plural-distrib.h \
    $$PWD/DependLibs/libgnu/plural-eval.h \
    $$PWD/DependLibs/libgnu/plural-exp.h \
    $$PWD/DependLibs/libgnu/plural-table.h \
    $$PWD/DependLibs/libgnu/po-charset.h \
    $$PWD/DependLibs/libgnu/po-error.h \
    $$PWD/DependLibs/libgnu/po-gram-gen.h \
    $$PWD/DependLibs/libgnu/po-gram-gen2.h \
    $$PWD/DependLibs/libgnu/po-gram.h \
    $$PWD/DependLibs/libgnu/po-lex.h \
    $$PWD/DependLibs/libgnu/po-time.h \
    $$PWD/DependLibs/libgnu/po-xerror.h \
    $$PWD/DependLibs/libgnu/pos.h \
    $$PWD/DependLibs/libgnu/posix-lock-obj.h \
    $$PWD/DependLibs/libgnu/printf-args.h \
    $$PWD/DependLibs/libgnu/printf-parse.h \
    $$PWD/DependLibs/libgnu/printf.h \
    $$PWD/DependLibs/libgnu/priority_options.h \
    $$PWD/DependLibs/libgnu/progname.h \
    $$PWD/DependLibs/libgnu/propername.h \
    $$PWD/DependLibs/libgnu/quote.h \
    $$PWD/DependLibs/libgnu/rand-internal.h \
    $$PWD/DependLibs/libgnu/random_gnu.h \
    $$PWD/DependLibs/libgnu/read-catalog-abstract.h \
    $$PWD/DependLibs/libgnu/read-catalog.h \
    $$PWD/DependLibs/libgnu/read-csharp.h \
    $$PWD/DependLibs/libgnu/read-desktop.h \
    $$PWD/DependLibs/libgnu/read-file.h \
    $$PWD/DependLibs/libgnu/read-java.h \
    $$PWD/DependLibs/libgnu/read-mo.h \
    $$PWD/DependLibs/libgnu/read-po.h \
    $$PWD/DependLibs/libgnu/read-properties.h \
    $$PWD/DependLibs/libgnu/read-resources.h \
    $$PWD/DependLibs/libgnu/read-stringtable.h \
    $$PWD/DependLibs/libgnu/read-tcl.h \
    $$PWD/DependLibs/libgnu/regex.h \
    $$PWD/DependLibs/libgnu/regex_internal.h \
    $$PWD/DependLibs/libgnu/relocatable.h \
    $$PWD/DependLibs/libgnu/same-inode.h \
    $$PWD/DependLibs/libgnu/same.h \
    $$PWD/DependLibs/libgnu/search-path.h \
    $$PWD/DependLibs/libgnu/secmem_gnu.h \
    $$PWD/DependLibs/libgnu/self-test.h \
    $$PWD/DependLibs/libgnu/sentence.h \
    $$PWD/DependLibs/libgnu/signal.in.h \
    $$PWD/DependLibs/libgnu/signal_gnu.h \
    $$PWD/DependLibs/libgnu/signal_gnu.in.h \
    $$PWD/DependLibs/libgnu/size_max.h \
    $$PWD/DependLibs/libgnu/stdalign.h \
    $$PWD/DependLibs/libgnu/stdarg.in.h \
    $$PWD/DependLibs/libgnu/stdbool.in.h \
    $$PWD/DependLibs/libgnu/stddef.in.h \
    $$PWD/DependLibs/libgnu/stddef_gnu.h \
    $$PWD/DependLibs/libgnu/stddef_gnu.in.h \
    $$PWD/DependLibs/libgnu/stdint.in.h \
    $$PWD/DependLibs/libgnu/stdio.in.h \
    $$PWD/DependLibs/libgnu/stdio_gnu.h \
    $$PWD/DependLibs/libgnu/stdio_gnu.in.h \
    $$PWD/DependLibs/libgnu/stdlib.in.h \
    $$PWD/DependLibs/libgnu/stdlib_gnu.h \
    $$PWD/DependLibs/libgnu/stdlib_gnu.in.h \
    $$PWD/DependLibs/libgnu/stdmem.h \
    $$PWD/DependLibs/libgnu/str-kmp.h \
    $$PWD/DependLibs/libgnu/str-list.h \
    $$PWD/DependLibs/libgnu/str-two-way.h \
    $$PWD/DependLibs/libgnu/streq.h \
    $$PWD/DependLibs/libgnu/strerror-override.h \
    $$PWD/DependLibs/libgnu/striconv.h \
    $$PWD/DependLibs/libgnu/striconveh.h \
    $$PWD/DependLibs/libgnu/striconveha.h \
    $$PWD/DependLibs/libgnu/string.in.h \
    $$PWD/DependLibs/libgnu/string_gnu.h \
    $$PWD/DependLibs/libgnu/string_gnu.in.h \
    $$PWD/DependLibs/libgnu/strnlen1.h \
    $$PWD/DependLibs/libgnu/structure.h \
    $$PWD/DependLibs/libgnu/styled-ostream.h \
    $$PWD/DependLibs/libgnu/styled-ostream.oo.h \
    $$PWD/DependLibs/libgnu/styled_ostream.priv.h \
    $$PWD/DependLibs/libgnu/styled_ostream.vt.h \
    $$PWD/DependLibs/libgnu/sys_select.in.h \
    $$PWD/DependLibs/libgnu/sys_stat.in.h \
    $$PWD/DependLibs/libgnu/sys_time.in.h \
    $$PWD/DependLibs/libgnu/sys_types.in.h \
    $$PWD/DependLibs/libgnu/sys_wait.in.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.aarch64-apple-darwin.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.aarch64-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.alpha-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.arm-apple-darwin.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.arm-unknown-linux-androideabi.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.arm-unknown-linux-gnueabi.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.arm-unknown-linux-gnueabihf.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.hppa-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.i486-pc-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.i486-pc-kfreebsd-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.i686-pc-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.linux-android.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.m68k-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.mingw32.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.mips-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.mips64el-unknown-linux-gnuabi64.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.mipsel-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.or1k-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.powerpc-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.powerpc64-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.powerpc64le-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.s390x-ibm-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.sh4-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.sparc-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.sparc64-unknown-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.x86_64-pc-kfreebsd-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.x86_64-pc-linux-gnu.h \
    $$PWD/DependLibs/libgnu/syscfg/lock-obj-pub.x86_64-pc-linux-gnux32.h \
    $$PWD/DependLibs/libgnu/system-keys.h \
    $$PWD/DependLibs/libgnu/system.h \
    $$PWD/DependLibs/libgnu/thread.h \
    $$PWD/DependLibs/libgnu/time.in.h \
    $$PWD/DependLibs/libgnu/time_gnu.h \
    $$PWD/DependLibs/libgnu/time_gnu.in.h \
    $$PWD/DependLibs/libgnu/tls.h \
    $$PWD/DependLibs/libgnu/tmpdir.h \
    $$PWD/DependLibs/libgnu/tpm.h \
    $$PWD/DependLibs/libgnu/trim.h \
    $$PWD/DependLibs/libgnu/tsearch.h \
    $$PWD/DependLibs/libgnu/types_gnu.h \
    $$PWD/DependLibs/libgnu/u64.h \
    $$PWD/DependLibs/libgnu/uniconv.in.h \
    $$PWD/DependLibs/libgnu/unictype.h \
    $$PWD/DependLibs/libgnu/unictype/bitmap.h \
    $$PWD/DependLibs/libgnu/unictype/ctype_alpha.h \
    $$PWD/DependLibs/libgnu/unictype/ctype_space.h \
    $$PWD/DependLibs/libgnu/unilbrk.h \
    $$PWD/DependLibs/libgnu/unilbrk.in.h \
    $$PWD/DependLibs/libgnu/uniname.h \
    $$PWD/DependLibs/libgnu/unistd.in.h \
    $$PWD/DependLibs/libgnu/unistd_gnu.h \
    $$PWD/DependLibs/libgnu/unistd_gnu.in.h \
    $$PWD/DependLibs/libgnu/unistr.h \
    $$PWD/DependLibs/libgnu/unistr.in.h \
    $$PWD/DependLibs/libgnu/unitypes.h \
    $$PWD/DependLibs/libgnu/unitypes.in.h \
    $$PWD/DependLibs/libgnu/uniwidth.h \
    $$PWD/DependLibs/libgnu/uniwidth.in.h \
    $$PWD/DependLibs/libgnu/uniwidth/cjk.h \
    $$PWD/DependLibs/libgnu/unlocked-io.h \
    $$PWD/DependLibs/libgnu/unused-parameter.h \
    $$PWD/DependLibs/libgnu/urls.h \
    $$PWD/DependLibs/libgnu/vasnprintf.h \
    $$PWD/DependLibs/libgnu/vasnwprintf.h \
    $$PWD/DependLibs/libgnu/vasprintf.h \
    $$PWD/DependLibs/libgnu/verify.h \
    $$PWD/DependLibs/libgnu/visibility_gnu.h \
    $$PWD/DependLibs/libgnu/w32-add.h \
    $$PWD/DependLibs/libgnu/w32-lock-obj.h \
    $$PWD/DependLibs/libgnu/w32ce-add.h \
    $$PWD/DependLibs/libgnu/warn-on-use.h \
    $$PWD/DependLibs/libgnu/wchar.in.h \
    $$PWD/DependLibs/libgnu/wchar_gnu.h \
    $$PWD/DependLibs/libgnu/wchar_gnu.in.h \
    $$PWD/DependLibs/libgnu/wctype.in.h \
    $$PWD/DependLibs/libgnu/wctype_gnu.h \
    $$PWD/DependLibs/libgnu/wprintf-parse.h \
    $$PWD/DependLibs/libgnu/write-catalog.h \
    $$PWD/DependLibs/libgnu/write-csharp.h \
    $$PWD/DependLibs/libgnu/write-desktop.h \
    $$PWD/DependLibs/libgnu/write-java.h \
    $$PWD/DependLibs/libgnu/write-mo.h \
    $$PWD/DependLibs/libgnu/write-po.h \
    $$PWD/DependLibs/libgnu/write-properties.h \
    $$PWD/DependLibs/libgnu/write-qt.h \
    $$PWD/DependLibs/libgnu/write-resources.h \
    $$PWD/DependLibs/libgnu/write-stringtable.h \
    $$PWD/DependLibs/libgnu/write-tcl.h \
    $$PWD/DependLibs/libgnu/write-xml.h \
    $$PWD/DependLibs/libgnu/x-appdata.h \
    $$PWD/DependLibs/libgnu/x-awk.h \
    $$PWD/DependLibs/libgnu/x-c.h \
    $$PWD/DependLibs/libgnu/x-csharp.h \
    $$PWD/DependLibs/libgnu/x-desktop.h \
    $$PWD/DependLibs/libgnu/x-elisp.h \
    $$PWD/DependLibs/libgnu/x-glade.h \
    $$PWD/DependLibs/libgnu/x-gsettings.h \
    $$PWD/DependLibs/libgnu/x-java.h \
    $$PWD/DependLibs/libgnu/x-javascript.h \
    $$PWD/DependLibs/libgnu/x-librep.h \
    $$PWD/DependLibs/libgnu/x-lisp.h \
    $$PWD/DependLibs/libgnu/x-lua.h \
    $$PWD/DependLibs/libgnu/x-perl.h \
    $$PWD/DependLibs/libgnu/x-php.h \
    $$PWD/DependLibs/libgnu/x-po.h \
    $$PWD/DependLibs/libgnu/x-properties.h \
    $$PWD/DependLibs/libgnu/x-python.h \
    $$PWD/DependLibs/libgnu/x-rst.h \
    $$PWD/DependLibs/libgnu/x-scheme.h \
    $$PWD/DependLibs/libgnu/x-sh.h \
    $$PWD/DependLibs/libgnu/x-smalltalk.h \
    $$PWD/DependLibs/libgnu/x-stringtable.h \
    $$PWD/DependLibs/libgnu/x-tcl.h \
    $$PWD/DependLibs/libgnu/x-vala.h \
    $$PWD/DependLibs/libgnu/x-ycp.h \
    $$PWD/DependLibs/libgnu/x509-ext.h \
    $$PWD/DependLibs/libgnu/x509.h \
    $$PWD/DependLibs/libgnu/x509/gnutls-idna.h \
    $$PWD/DependLibs/libgnu/x509/gnutls_common.h \
    $$PWD/DependLibs/libgnu/x509/verify-high.h \
    $$PWD/DependLibs/libgnu/x509/x509_int.h \
    $$PWD/DependLibs/libgnu/x509_b64.h \
    $$PWD/DependLibs/libgnu/xalloc-oversized.h \
    $$PWD/DependLibs/libgnu/xalloc.h \
    $$PWD/DependLibs/libgnu/xerror.h \
    $$PWD/DependLibs/libgnu/xgettext.h \
    $$PWD/DependLibs/libgnu/xmalloca.h \
    $$PWD/DependLibs/libgnu/xreadlink.h \
    $$PWD/DependLibs/libgnu/xsize_gnu.h \
    $$PWD/DependLibs/libgnu/xstriconv.h \
    $$PWD/DependLibs/libgnu/xvasprintf.h \
    $$PWD/DependLibs/libgnu/int_gnu.h


SOURCES += 	\
    $$PWD/DependLibs/libgnu/base64_gnu.c \
    $$PWD/DependLibs/libgnu/common_gnu.c \
    $$PWD/DependLibs/libgnu/djgpp/ioctl_gnu.c \
    $$PWD/DependLibs/libgnu/float_gnu.c \
### util with main	$$PWD/DependLibs/libgnu/gcryptrnd.c \
### util with main	$$PWD/DependLibs/libgnu/gen-posix-lock-obj.c \
### util with main	$$PWD/DependLibs/libgnu/gen-w32-lock-obj.c \
    $$PWD/DependLibs/libgnu/global_gnu.c \
    $$PWD/DependLibs/libgnu/hash_gnu.c \
    $$PWD/DependLibs/libgnu/iconv_gnu.c \
    $$PWD/DependLibs/libgnu/init_gnu.c \
    $$PWD/DependLibs/libgnu/int_gnu.c \
    $$PWD/DependLibs/libgnu/lock_gnu.c \
    $$PWD/DependLibs/libgnu/misc_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cast128-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes128-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa2openpgp_gnu.c \
    $$PWD/DependLibs/libgnu/random_gnu.c \
    $$PWD/DependLibs/libgnu/read-file-gnu.c \
    $$PWD/DependLibs/libgnu/secmem_gnu.c \
    $$PWD/DependLibs/libgnu/sexp_gnu.c \
    $$PWD/DependLibs/libgnu/threadlib_gnu.c \
    $$PWD/DependLibs/libgnu/unistd_gnu.c \
    $$PWD/DependLibs/libgnu/version_libgnu.c \
    $$PWD/DependLibs/libgnu/visibility_gnu.c \
    $$PWD/DependLibs/libgnu/xsize_gnu.c \
#    $$PWD/DependLibs/libgnu/os2compat2.c \ #alignment errors in linux
    $$PWD/DependLibs/libgnu/error_gnu.c \
    $$PWD/DependLibs/libgnu/malloc_gnu.c \
    $$PWD/DependLibs/libgnu/log_gnu.c \
    $$PWD/DependLibs/libgnu/os2compat2_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-cbc-x86-aesni_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-cbc-x86-ssse3_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-ccm-x86-aesni_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-padlock_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-x86-aesni_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-x86-pclmul_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-gcm-x86-ssse3_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/aes-padlock_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/hmac-padlock_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/hmac-x86-ssse3_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/sha-padlock_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/sha-x86-ssse3_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/x86/x86-common_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/accelerated_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/cryptodev-gcm_gnu.c \
    $$PWD/DependLibs/libgnu/accelerated/cryptodev_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/cert_types_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/ciphers_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/ciphersuites_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/ecc_algorithms_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/kx_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/mac_algorithms_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/protocols_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/publickey_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/secparams_gnu.c \
    $$PWD/DependLibs/libgnu/algorithms/sign_algorithms_gnu.c \
    $$PWD/DependLibs/libgnu/auth/anon_gnu.c \
    $$PWD/DependLibs/libgnu/auth/anon_ecdh_gnu.c \
    $$PWD/DependLibs/libgnu/auth/cert_gnu.c \
    $$PWD/DependLibs/libgnu/auth/dh_common_gnu.c \
    $$PWD/DependLibs/libgnu/auth/dhe_gnu.c \
    $$PWD/DependLibs/libgnu/auth/dhe_psk_gnu.c \
    $$PWD/DependLibs/libgnu/auth/ecdhe_gnu.c \
    $$PWD/DependLibs/libgnu/auth/psk_gnu.c \
    $$PWD/DependLibs/libgnu/auth/psk_passwd_gnu.c \
    $$PWD/DependLibs/libgnu/auth/rsa_gnutls_gnu.c \
    $$PWD/DependLibs/libgnu/auth/rsa_psk_gnu.c \
    $$PWD/DependLibs/libgnu/auth/srp_auth_gnu.c \
    $$PWD/DependLibs/libgnu/auth/srp_passwd_gnu.c \
    $$PWD/DependLibs/libgnu/auth/srp_rsa_gnu.c \
    $$PWD/DependLibs/libgnu/auth/srp_sb64_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/arcfour_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/blowfish_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/camellia-glue_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/camellia_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cast5_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-aeswrap_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-cbc_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-ccm_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-cfb_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-cmac_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-ctr_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-gcm_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-ofb_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher-selftest_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/cipher_list_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/crc_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/des_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/dsa-common_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/dsa_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-curves_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-ecdsa_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-eddsa_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-gost_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/ecc-misc_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/ecc_cipher_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/elgamal_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/gost28147_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/gostr3411-94_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/hash-common_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/hmac-tests_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/idea_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/kdf_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/mac-cmac_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/mac-gmac_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/mac-hmac_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/mac_cipher_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/md_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/md5_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/md5_cypher_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/md4_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/primegen_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/pubkey-util_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/pubkey_cipher_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/rfc2268_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/rijndael_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/rmd160_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/rsa-common_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/rsa_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/salsa20_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/scrypt_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/seed_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/sha1_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/sha256_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/sha512_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/stribog_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/tiger_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/serpent_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/twofish_gnu.c \
    $$PWD/DependLibs/libgnu/cipher/whirlpool_gnu.c \
    $$PWD/DependLibs/libgnu/compat/clock_gnu.c \
    $$PWD/DependLibs/libgnu/compat/compat_compat_gnu.c \
    $$PWD/DependLibs/libgnu/compat/getpid_gnu.c \
    $$PWD/DependLibs/libgnu/djgpp/getpwnam_gnu.c \
    $$PWD/DependLibs/libgnu/djgpp/unsetenv_gnu.c \
    $$PWD/DependLibs/libgnu/ext/alpn_gnu.c \
    $$PWD/DependLibs/libgnu/ext/cert_type_gnu.c \
    $$PWD/DependLibs/libgnu/ext/dumbfw_gnu.c \
    $$PWD/DependLibs/libgnu/ext/ecc_ext_gnu.c \
    $$PWD/DependLibs/libgnu/ext/etm_gnu.c \
    $$PWD/DependLibs/libgnu/ext/ext_master_secret_gnu.c \
    $$PWD/DependLibs/libgnu/ext/heartbeat_gnu.c \
    $$PWD/DependLibs/libgnu/ext/max_record_gnu.c \
    $$PWD/DependLibs/libgnu/ext/safe_renegotiation_gnu.c \
    $$PWD/DependLibs/libgnu/ext/server_name_gnu.c \
    $$PWD/DependLibs/libgnu/ext/session_ticket_gnu.c \
    $$PWD/DependLibs/libgnu/ext/signature_gnu.c \
    $$PWD/DependLibs/libgnu/ext/srp_wrapper_gnu.c \
    $$PWD/DependLibs/libgnu/ext/srtp_gnu.c \
    $$PWD/DependLibs/libgnu/ext/status_request_gnu.c \
    $$PWD/DependLibs/libgnu/extras/hex_gnu.c \
    $$PWD/DependLibs/libgnu/extras/randomart_gnu.c \
    $$PWD/DependLibs/libgnu/misc/cvsuser_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-add1_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-lshift_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-mul1_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-mul2_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-mul3_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-rshift_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/generic/mpih-sub1_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/generic/udiv-w-sdiv_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/ec-ed25519_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/ec_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-add_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-bit_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-cmp_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-div_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-gcd_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-inline_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-inv_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-mod_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-mpow_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-mul_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-pow_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpi-scan_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpicoder_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpih-div_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpih-mul_gnu.c \
    $$PWD/DependLibs/libgnu/mpi/mpiutil_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta-aeads_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta-armors_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta-ciphers_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle-meta-hashes_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-decrypt-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-decrypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-encrypt-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-encrypt-table_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-encrypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-invert-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-set-decrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-set-encrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes-set-key-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes128-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes128-set-decrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes128-set-encrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes192-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes192-set-decrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes192-set-encrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes256-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes256-set-decrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aes256-set-encrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_aesdata_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_arcfour-crypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_arcfour_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_arctwo-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_arctwo_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base16-decode_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base16-encode_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base16-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64-decode_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64-encode_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64url-decode_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64url-encode_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_base64url-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_bignum-random-prime_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_bignum-random_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_bignum_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_blowfish_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_buffer-init_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_buffer_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-absorb_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-crypt-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-invert-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia-table_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia128-crypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia128-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia128-set-decrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia128-set-encrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia192-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia256-crypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia256-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia256-set-decrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_camellia256-set-encrypt-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cast128_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cbc_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm-aes128_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm-aes192_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm-aes256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ccm_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-core-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-crypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-poly1305-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-poly1305_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-set-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_chacha-set-nonce_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cipher_nettle_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_cnd-copy_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ctr_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_curve25519-eh-to-x_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_curve25519-mul-g_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_curve25519-mul_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_der-iterator_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_der2dsa_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_der2rsa_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_des-compat_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_des_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_des3_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_desdata_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_drbg-aes-self-test_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_drbg-aes_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-compat-keygen_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-compat_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-gen-params_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-hash_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-keygen-fips186_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-keygen_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sha1-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sha1-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sha256-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sha256-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-validate_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eax-aes128-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa2sexp_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_dsa_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eax-aes128_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eax_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-192_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-224_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-25519_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-384_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-521_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-a-to-j_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-add-eh_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-add-ehh_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-add-jja_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-add-jjj_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-dup-eh_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-dup-jj_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-ecdsa-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-ecdsa-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-eh-to-a_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-hash_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-j-to-a_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mod-arith_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mod-inv_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mod_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mul-a-eh_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mul-a_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mul-g-eh_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-mul-g_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-pm1-redc_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-point-mul-g_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-point-mul_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-point_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-pp1-redc_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-random_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-scalar_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecc-size_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eccdata_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecdsa-keygen_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecdsa-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ecdsa-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ed25519-sha512-pubkey_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ed25519-sha512-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ed25519-sha512-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-compress_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-decompress_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-expand_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-hash_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-pubkey_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_eddsa-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_egd_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_fat-arm_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_fat-x86_64_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes128_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes192-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes192_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes256-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-aes256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-camellia128-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-camellia128_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-camellia256-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm-camellia256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcm_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gcmdata_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_getopt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_getopt1_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gmp-glue_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gosthash94-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_gosthash94_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-md5_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-ripemd160_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha1_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha224_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha384_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac-sha512_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_hmac_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_init_nettle_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_knuth-lfib_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_mac_nettle_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md2-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md2_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md4-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md4_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5-compat_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5-compress_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_md5_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_memxor_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_memxor3_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_mini-gmp_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_mpi_nettle_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pbkdf2-hmac-sha1_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pbkdf2-hmac-sha256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pbkdf2_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pgp-encode_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pk_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-decrypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-encrypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-digest_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-md5_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-sha1_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-sha256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1-rsa-sha512_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_pkcs1_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_poly1305-aes_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_poly1305-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_provable-prime_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_realloc_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ripemd160-compress_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ripemd160-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_ripemd160_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rnd-common_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rnd-fips_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rnd_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-blind_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-decrypt-tr_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-decrypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-encrypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-keygen-fips186_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-keygen_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-md5-sign-tr_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-md5-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-md5-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-pkcs1-sign-tr_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-pkcs1-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-pkcs1-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha1-sign-tr_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha1-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha1-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha256-sign-tr_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha256-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha256-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha512-sign-tr_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha512-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sha512-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sign-tr_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-sign_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa-verify_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa2sexp_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_rsa_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-128-set-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-256-set-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-core-internal_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-crypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-set-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20-set-nonce_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_salsa20r12-crypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sec-add-1_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sec-sub-1_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sec-tabselect_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-decrypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-encrypt_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_serpent-set-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp-format_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp-transport-format_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp-transport_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp2dsa_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp2bignum_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sexp2rsa_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha-example_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha1-compress_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha1-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha1_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha224-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha256-compress_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha256-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-224-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-224_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-256-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-384-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-384_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-512-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-512_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3-permute_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha3_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha384-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512-224-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512-256-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512-compress_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_sha512_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_shadata_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_twofish-meta_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_twofish_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_twofishdata_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-l2_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-l3_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-nh-n_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-nh_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-poly128_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-poly64_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac-set-key_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac128_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac32_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac64_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_umac96_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_version_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_write-be32_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_write-le32_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_write-le64_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_yarrow256_gnu.c \
    $$PWD/DependLibs/libgnu/nettle/nettle_yarrow_key_event_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/armor_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/kbnode_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/keydb_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/literal_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/misc_opencdk_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/new-packet_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/pubkey_pgp_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/read-packet_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/seskey_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/sig-check_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/stream_gnu.c \
    $$PWD/DependLibs/libgnu/opencdk/write-packet_gnu.c \
    $$PWD/DependLibs/libgnu/openpgp/compat_pgp_gnu.c \
    $$PWD/DependLibs/libgnu/openpgp/extras_gnu.c \
    $$PWD/DependLibs/libgnu/openpgp/gnutls_openpgp_gnu.c \
    $$PWD/DependLibs/libgnu/openpgp/output_pgp_gnu.c \
    $$PWD/DependLibs/libgnu/openpgp/pgp_gnu.c \
    $$PWD/DependLibs/libgnu/openpgp/pgpverify_gnu.c \
    $$PWD/DependLibs/libgnu/openpgp/privkey_pgp_gnu.c \
    $$PWD/DependLibs/libgnu/unictype/ctype_alpha_gnu.c \
    $$PWD/DependLibs/libgnu/unictype/ctype_space_gnu.c \
    $$PWD/DependLibs/libgnu/unistr/u8-mbtoucr_gnu.c \
    $$PWD/DependLibs/libgnu/unistr/u8-uctomb-aux_gnu.c \
    $$PWD/DependLibs/libgnu/unistr/u8-uctomb_gnu.c \
    $$PWD/DependLibs/libgnu/uniwidth/width_gnu.c \
    $$PWD/DependLibs/libgnu/x509/crl_gnu.c \
    $$PWD/DependLibs/libgnu/x509/crl_write_gnu.c \
    $$PWD/DependLibs/libgnu/x509/crq_gnu.c \
    $$PWD/DependLibs/libgnu/x509/dn_gnu.c \
    $$PWD/DependLibs/libgnu/x509/email-verify_gnu.c \
    $$PWD/DependLibs/libgnu/x509/extensions_gnu.c \
    $$PWD/DependLibs/libgnu/x509/gnutls_common_gnu.c \
    $$PWD/DependLibs/libgnu/x509/hostname-verify_gnu.c \
    $$PWD/DependLibs/libgnu/x509/key_decode_gnu.c \
    $$PWD/DependLibs/libgnu/x509/key_encode_gnu.c \
    $$PWD/DependLibs/libgnu/x509/mpi_x509_gnu.c \
    $$PWD/DependLibs/libgnu/x509/name_constraints_gnu.c \
    $$PWD/DependLibs/libgnu/x509/ocsp_gnu.c \
    $$PWD/DependLibs/libgnu/x509/ocsp_output_gnu.c \
    $$PWD/DependLibs/libgnu/x509/output_x509_gnu.c \
    $$PWD/DependLibs/libgnu/x509/pkcs12_gnu.c \
    $$PWD/DependLibs/libgnu/x509/pkcs12_encr_gnu.c \
    $$PWD/DependLibs/libgnu/x509/pkcs12_bag_gnu.c \
    $$PWD/DependLibs/libgnu/x509/privkey_openssl_gnu.c \
    $$PWD/DependLibs/libgnu/x509/privkey_pkcs8_gnu.c \
    $$PWD/DependLibs/libgnu/x509/privkey_x509_gnu.c \
    $$PWD/DependLibs/libgnu/x509/sign_x509_gnu.c \
    $$PWD/DependLibs/libgnu/x509/verify-high_gnu.c \
    $$PWD/DependLibs/libgnu/x509/verify-high2_gnu.c \
    $$PWD/DependLibs/libgnu/x509/verify_x509_gnu.c \
    $$PWD/DependLibs/libgnu/x509/x509_gnu.c \
    $$PWD/DependLibs/libgnu/x509/x509_dn_gnu.c \
    $$PWD/DependLibs/libgnu/x509/x509_ext_gnu.c \
    $$PWD/DependLibs/libgnu/x509/x509_write_gnu.c \
    $$PWD/DependLibs/libgnu/allocator_gnu.c \
    $$PWD/DependLibs/libgnu/areadlink_gnu.c \
    $$PWD/DependLibs/libgnu/asnprintf_gnu.c \
    $$PWD/DependLibs/libgnu/asprintf_gnu.c \
    $$PWD/DependLibs/libgnu/atexit_gnu.c \
    $$PWD/DependLibs/libgnu/atfork_gnu.c \
    $$PWD/DependLibs/libgnu/ath_gnu.c \
    $$PWD/DependLibs/libgnu/auto-verify_gnu.c \
    $$PWD/DependLibs/libgnu/basename_gnu.c \
    $$PWD/DependLibs/libgnu/binary-io_gnu.c \
    $$PWD/DependLibs/libgnu/bindtextdom_gnu.c \
    $$PWD/DependLibs/libgnu/bitrotate_gnu.c \
    $$PWD/DependLibs/libgnu/btowc_gnu.c \
    $$PWD/DependLibs/libgnu/c-ctype_gnu.c \
    $$PWD/DependLibs/libgnu/c-strcasecmp_gnu.c \
    $$PWD/DependLibs/libgnu/c-strncasecmp_gnu.c \
    $$PWD/DependLibs/libgnu/c-strstr_gnu.c \
    $$PWD/DependLibs/libgnu/canonicalize-lgpl_gnu.c \
    $$PWD/DependLibs/libgnu/careadlinkat_gnu.c \
    $$PWD/DependLibs/libgnu/cldr-plural-exp_gnu.c \
    $$PWD/DependLibs/libgnu/cldr-plural_gnu.c \
    $$PWD/DependLibs/libgnu/cldr-plurals_gnu.c \
    $$PWD/DependLibs/libgnu/clean-temp_gnu.c \
    $$PWD/DependLibs/libgnu/close_gnu.c \
    $$PWD/DependLibs/libgnu/closeout_gnu.c \
    $$PWD/DependLibs/libgnu/code-from-errno_gnu.c \
    $$PWD/DependLibs/libgnu/code-to-errno_gnu.c \
    $$PWD/DependLibs/libgnu/coding_gnu.c \
    $$PWD/DependLibs/libgnu/color_gnu.c \
    $$PWD/DependLibs/libgnu/concat-filename_gnu.c \
    $$PWD/DependLibs/libgnu/context_gnu.c \
    $$PWD/DependLibs/libgnu/copy-acl_gnu.c \
    $$PWD/DependLibs/libgnu/copy-file_gnu.c \
    $$PWD/DependLibs/libgnu/crypto-api_gnu.c \
    $$PWD/DependLibs/libgnu/crypto-backend_gnu.c \
    $$PWD/DependLibs/libgnu/crypto-selftests-pk_gnu.c \
    $$PWD/DependLibs/libgnu/crypto-selftests_gnu.c \
    $$PWD/DependLibs/libgnu/csharpcomp_gnu.c \
    $$PWD/DependLibs/libgnu/csharpexec_gnu.c \
    $$PWD/DependLibs/libgnu/dcgettext_gnu.c \
    $$PWD/DependLibs/libgnu/dcigettext_gnu.c \
    $$PWD/DependLibs/libgnu/dcngettext_gnu.c \
    $$PWD/DependLibs/libgnu/debug_gnu.c \
    $$PWD/DependLibs/libgnu/decoding_gnu.c \
    $$PWD/DependLibs/libgnu/dgettext_gnu.c \
    $$PWD/DependLibs/libgnu/dir-list_gnu.c \
    $$PWD/DependLibs/libgnu/dirname-lgpl_gnu.c \
    $$PWD/DependLibs/libgnu/dirname_gnu.c \
    $$PWD/DependLibs/libgnu/dngettext_gnu.c \
    $$PWD/DependLibs/libgnu/dumpsexp_gnu.c \
    $$PWD/DependLibs/libgnu/element_gnu.c \
    $$PWD/DependLibs/libgnu/envsubst_gnu.c \
    $$PWD/DependLibs/libgnu/error-progname_gnu.c \
    $$PWD/DependLibs/libgnu/errors_gnu.c \
    $$PWD/DependLibs/libgnu/estream-printf_gnu.c \
    $$PWD/DependLibs/libgnu/estream_gnu.c \
    $$PWD/DependLibs/libgnu/exitfail_gnu.c \
    $$PWD/DependLibs/libgnu/explodename_gnu.c \
    $$PWD/DependLibs/libgnu/fatal-signal_gnu.c \
    $$PWD/DependLibs/libgnu/fd-hook_gnu.c \
    $$PWD/DependLibs/libgnu/file-list_gnu.c \
    $$PWD/DependLibs/libgnu/file-ostream_gnu.c \
    $$PWD/DependLibs/libgnu/file-ostream.oo_gnu.c \
    $$PWD/DependLibs/libgnu/filter-quote_gnu.c \
    $$PWD/DependLibs/libgnu/filter-sr-latin_gnu.c \
    $$PWD/DependLibs/libgnu/finddomain_gnu.c \
    $$PWD/DependLibs/libgnu/fips_gnu.c \
    $$PWD/DependLibs/libgnu/fopen_gnu.c \
    $$PWD/DependLibs/libgnu/format-awk_gnu.c \
    $$PWD/DependLibs/libgnu/format-boost_gnu.c \
    $$PWD/DependLibs/libgnu/format-c_gnu.c \
    $$PWD/DependLibs/libgnu/format-csharp_gnu.c \
    $$PWD/DependLibs/libgnu/format-elisp_gnu.c \
    $$PWD/DependLibs/libgnu/format-gcc-internal_gnu.c \
    $$PWD/DependLibs/libgnu/format-gfc-internal_gnu.c \
    $$PWD/DependLibs/libgnu/format-java_gnu.c \
    $$PWD/DependLibs/libgnu/format-javascript_gnu.c \
    $$PWD/DependLibs/libgnu/format-kde-kuit_gnu.c \
    $$PWD/DependLibs/libgnu/format-kde_gnu.c \
    $$PWD/DependLibs/libgnu/format-librep_gnu.c \
    $$PWD/DependLibs/libgnu/format-lisp_gnu.c \
    $$PWD/DependLibs/libgnu/format-lua_gnu.c \
    $$PWD/DependLibs/libgnu/format-pascal_gnu.c \
    $$PWD/DependLibs/libgnu/format-perl-brace_gnu.c \
    $$PWD/DependLibs/libgnu/format-perl_gnu.c \
    $$PWD/DependLibs/libgnu/format-php_gnu.c \
    $$PWD/DependLibs/libgnu/format-python-brace_gnu.c \
    $$PWD/DependLibs/libgnu/format-python_gnu.c \
    $$PWD/DependLibs/libgnu/format-qt-plural_gnu.c \
    $$PWD/DependLibs/libgnu/format-qt_gnu.c \
    $$PWD/DependLibs/libgnu/format-scheme_gnu.c \
    $$PWD/DependLibs/libgnu/format-sh_gnu.c \
    $$PWD/DependLibs/libgnu/format-tcl_gnu.c \
    $$PWD/DependLibs/libgnu/format-ycp_gnu.c \
    $$PWD/DependLibs/libgnu/format_gnu.c \
    $$PWD/DependLibs/libgnu/fstat_gnu.c \
    $$PWD/DependLibs/libgnu/fstrcmp_gnu.c \
    $$PWD/DependLibs/libgnu/fwriteerror_gnu.c \
    $$PWD/DependLibs/libgnu/gcd_gnu.c \
    $$PWD/DependLibs/libgnu/getdelim_gnu.c \
    $$PWD/DependLibs/libgnu/getline_gnu.c \
    $$PWD/DependLibs/libgnu/getopt_gnu.c \
    $$PWD/DependLibs/libgnu/getopt1_gnu.c \
    $$PWD/DependLibs/libgnu/getrandom_gnu.c \
    $$PWD/DependLibs/libgnu/gettext-po_gnu.c \
    $$PWD/DependLibs/libgnu/gettext_gnu.c \
    $$PWD/DependLibs/libgnu/gettimeofday_gnu.c \
    $$PWD/DependLibs/libgnu/ghash_gnu.c \
    $$PWD/DependLibs/libgnu/gl_linked_list_gnut.c \
    $$PWD/DependLibs/libgnu/gl_list_gnu.c \
    $$PWD/DependLibs/libgnu/gl_xlist_gnu.c \
    $$PWD/DependLibs/libgnu/glist_gnu.c \
    $$PWD/DependLibs/libgnu/gmessages_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_alert_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_anon_cred_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_asn1_tab_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_auth_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_buffers_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_cert_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_cipher_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_cipher_int_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_compress_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_constate_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_datum_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_db_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_dh_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_dtls_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_ecc_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_errors_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_extensions_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_global_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_handshake_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_hash_int_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_helper_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_kx_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_mbuffers_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_mem_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_mpi_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_num_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_pcert_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_pk_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_priority_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_privkey_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_privkey_raw_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_psk_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_pubkey_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_random_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_range_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_record_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_session_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_session_pack_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_sig_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_srp_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_state_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_str_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_supplemental_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_ui_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_v2_compat_gnu.c \
    $$PWD/DependLibs/libgnu/gnutls_x509_gnu.c \
    $$PWD/DependLibs/libgnu/gnutlsxx_gnu.cpp \
    $$PWD/DependLibs/libgnu/gpg-error_gnu.c \
    $$PWD/DependLibs/libgnu/gprimes_gnu.c \
    $$PWD/DependLibs/libgnu/gstr_gnu.c \
    $$PWD/DependLibs/libgnu/gstrfuncs_gnu.c \
    $$PWD/DependLibs/libgnu/gstring_gnu.c \
    $$PWD/DependLibs/libgnu/hard-locale_gnu.c \
    $$PWD/DependLibs/libgnu/hash-pjw-bare_gnu.c \
    $$PWD/DependLibs/libgnu/hash-pjw_gnu.c \
    $$PWD/DependLibs/libgnu/hash-string_gnu.c \
    $$PWD/DependLibs/libgnu/hash-triple_gnu.c \
    $$PWD/DependLibs/libgnu/hmac-md5_gnu.c \
    $$PWD/DependLibs/libgnu/hmac-sha1_gnu.c \
    $$PWD/DependLibs/libgnu/hmac-sha256_gnu.c \
    $$PWD/DependLibs/libgnu/hmac-sha512_gnu.c \
    $$PWD/DependLibs/libgnu/hmac256_gnu.c \
    $$PWD/DependLibs/libgnu/hostname_gnu.c \
    $$PWD/DependLibs/libgnu/hwf-arm_gnu.c \
    $$PWD/DependLibs/libgnu/hwf-x86_gnu.c \
    $$PWD/DependLibs/libgnu/hwfeatures_gnu.c \
    $$PWD/DependLibs/libgnu/iconv_close_gnu.c \
    $$PWD/DependLibs/libgnu/iconv_open_gnu.c \
    $$PWD/DependLibs/libgnu/inet_ntop_gnu.c \
    $$PWD/DependLibs/libgnu/inet_pton_gnu.c \
    $$PWD/DependLibs/libgnu/intl-compat_gnu.c \
    $$PWD/DependLibs/libgnu/intl-exports_gnu.c \
    $$PWD/DependLibs/libgnu/iswblank_gnu.c \
    $$PWD/DependLibs/libgnu/itold_gnu.c \
    $$PWD/DependLibs/libgnu/its_gnu.c \
    $$PWD/DependLibs/libgnu/javacomp_gnu.c \
    $$PWD/DependLibs/libgnu/javaexec_gnu.c \
    $$PWD/DependLibs/libgnu/javaversion_gnu.c \
    $$PWD/DependLibs/libgnu/kwset_gnu.c \
    $$PWD/DependLibs/libgnu/l10nflist_gnu.c \
    $$PWD/DependLibs/libgnu/lang-table_gnu.c \
    $$PWD/DependLibs/libgnu/langprefs_gnu.c \
    $$PWD/DependLibs/libgnu/loadmsgcat_gnu.c \
    $$PWD/DependLibs/libgnu/localcharset_gnu.c \
    $$PWD/DependLibs/libgnu/localealias_gnu.c \
    $$PWD/DependLibs/libgnu/localeconv_gnu.c \
    $$PWD/DependLibs/libgnu/localename_gnu.c \
    $$PWD/DependLibs/libgnu/locating-rule_gnu.c \
    $$PWD/DependLibs/libgnu/locks_gnu.c \
    $$PWD/DependLibs/libgnu/lstat_gnu.c \
    $$PWD/DependLibs/libgnu/m-fgrep_gnu.c \
    $$PWD/DependLibs/libgnu/m-regex_gnu.c \
    $$PWD/DependLibs/libgnu/malloca_gnu.c \
    $$PWD/DependLibs/libgnu/markup_gnu.c \
    $$PWD/DependLibs/libgnu/mbchar_gnu.c \
    $$PWD/DependLibs/libgnu/mbiter_gnu.c \
    $$PWD/DependLibs/libgnu/mbrlen_gnu.c \
    $$PWD/DependLibs/libgnu/mbrtowc_gnu.c \
    $$PWD/DependLibs/libgnu/mbsinit_gnu.c \
    $$PWD/DependLibs/libgnu/mbslen_gnu.c \
    $$PWD/DependLibs/libgnu/mbsstr_gnu.c \
    $$PWD/DependLibs/libgnu/mbswidth_gnu.c \
    $$PWD/DependLibs/libgnu/mbtowc_gnu.c \
    $$PWD/DependLibs/libgnu/mbuiter_gnu.c \
    $$PWD/DependLibs/libgnu/memchr_gnu.c \
    $$PWD/DependLibs/libgnu/memmove_gnu.c \
    $$PWD/DependLibs/libgnu/message_gnu.c \
    $$PWD/DependLibs/libgnu/missing-string_gnu.c \
    $$PWD/DependLibs/libgnu/mkerrcodes_gnu.c \
    $$PWD/DependLibs/libgnu/mkheader_gnu.c \
    $$PWD/DependLibs/libgnu/mkw32errmap_gnu.c \
    $$PWD/DependLibs/libgnu/mkw32errmap.map_gnu.c \
    $$PWD/DependLibs/libgnu/mman_w32_gnu.c \
    $$PWD/DependLibs/libgnu/mpicalc_gnu.c \
    $$PWD/DependLibs/libgnu/msgattrib_gnu.c \
    $$PWD/DependLibs/libgnu/msgcat_gnu.c \
    $$PWD/DependLibs/libgnu/msgcmp_gnu.c \
    $$PWD/DependLibs/libgnu/msgcomm_gnu.c \
    $$PWD/DependLibs/libgnu/msgconv_gnu.c \
    $$PWD/DependLibs/libgnu/msgen_gnu.c \
    $$PWD/DependLibs/libgnu/msgexec_gnu.c \
    $$PWD/DependLibs/libgnu/msgfilter_gnu.c \
    $$PWD/DependLibs/libgnu/msgfmt_gnu.c \
    $$PWD/DependLibs/libgnu/msggrep_gnu.c \
    $$PWD/DependLibs/libgnu/msginit_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-ascii_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-cat_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-charset_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-check_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-english_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-equal_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-fsearch_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-header_gnu.c \
    $$PWD/DependLibs/libgnu/msgl-iconv_gnu.c \
    $$PWD/DependLibs/libgnu/msgmerge_gnu.c \
    $$PWD/DependLibs/libgnu/msgunfmt_gnu.c \
    $$PWD/DependLibs/libgnu/msguniq_gnu.c \
    $$PWD/DependLibs/libgnu/msvc-inval_gnu.c \
    $$PWD/DependLibs/libgnu/msvc-nothrow_gnu.c \
    $$PWD/DependLibs/libgnu/ngettext_gnu.c \
    $$PWD/DependLibs/libgnu/nl_langinfo_gnu.c \
    $$PWD/DependLibs/libgnu/obstack_gnu.c \
    $$PWD/DependLibs/libgnu/open-catalog_gnu.c \
    $$PWD/DependLibs/libgnu/open_gnu.c \
    $$PWD/DependLibs/libgnu/osdep_gnu.c \
    $$PWD/DependLibs/libgnu/ostream_gnu.c \
    $$PWD/DependLibs/libgnu/ostream.oo_gnu.c \
    $$PWD/DependLibs/libgnu/parser_aux_gnu.c \
    $$PWD/DependLibs/libgnu/pin_gnu.c \
    $$PWD/DependLibs/libgnu/pkcs11_gnu.c \
    $$PWD/DependLibs/libgnu/pkcs11_int_gnu.c \
    $$PWD/DependLibs/libgnu/pkcs11_privkey_gnu.c \
    $$PWD/DependLibs/libgnu/pkcs11_secret_gnu.c \
    $$PWD/DependLibs/libgnu/pkcs11_write_gnu.c \
    $$PWD/DependLibs/libgnu/pkcs11x_gnu.c \
    $$PWD/DependLibs/libgnu/pkix_asn1_tab_gnu.c \
    $$PWD/DependLibs/libgnu/plural-count_gnu.c \
    $$PWD/DependLibs/libgnu/plural-eval_gnu.c \
    $$PWD/DependLibs/libgnu/plural-exp_gnu.c \
    $$PWD/DependLibs/libgnu/plural-table_gnu.c \
    $$PWD/DependLibs/libgnu/plural_gnu.c \
    $$PWD/DependLibs/libgnu/po-charset_gnu.c \
    $$PWD/DependLibs/libgnu/po-error_gnu.c \
    $$PWD/DependLibs/libgnu/po-gram-gen_gnu.c \
    $$PWD/DependLibs/libgnu/po-lex_gnu.c \
    $$PWD/DependLibs/libgnu/po-time_gnu.c \
    $$PWD/DependLibs/libgnu/po-xerror_gnu.c \
    $$PWD/DependLibs/libgnu/posix-lock_gnu.c \
    $$PWD/DependLibs/libgnu/posix-thread_gnu.c \
    $$PWD/DependLibs/libgnu/printf-args_gnu.c \
    $$PWD/DependLibs/libgnu/printf-parse_gnu.c \
    $$PWD/DependLibs/libgnu/printf_gnu.c \
    $$PWD/DependLibs/libgnu/progname_gnu.c \
    $$PWD/DependLibs/libgnu/progreloc_gnu.c \
    $$PWD/DependLibs/libgnu/propername_gnu.c \
    $$PWD/DependLibs/libgnu/raise_gnu.c \
    $$PWD/DependLibs/libgnu/random-csprng_gnu.c \
    $$PWD/DependLibs/libgnu/random-daemon_gnu.c \
    $$PWD/DependLibs/libgnu/random-fips_gnu.c \
    $$PWD/DependLibs/libgnu/random-system_gnu.c \
    $$PWD/DependLibs/libgnu/rawmemchr_gnu.c \
    $$PWD/DependLibs/libgnu/read-catalog-abstract_gnu.c \
    $$PWD/DependLibs/libgnu/read-catalog_gnu.c \
    $$PWD/DependLibs/libgnu/read-csharp_gnu.c \
    $$PWD/DependLibs/libgnu/read-desktop_gnu.c \
    $$PWD/DependLibs/libgnu/read-file_gnu.c \
    $$PWD/DependLibs/libgnu/read-java_gnu.c \
    $$PWD/DependLibs/libgnu/read-mo_gnu.c \
    $$PWD/DependLibs/libgnu/read-po_gnu.c \
    $$PWD/DependLibs/libgnu/read-properties_gnu.c \
    $$PWD/DependLibs/libgnu/read-resources_gnu.c \
    $$PWD/DependLibs/libgnu/read-stringtable_gnu.c \
    $$PWD/DependLibs/libgnu/read-tcl_gnu.c \
    $$PWD/DependLibs/libgnu/readlink_gnu.c \
    $$PWD/DependLibs/libgnu/realloc_gnu.c \
    $$PWD/DependLibs/libgnu/recode-sr-latin_gnu.c \
    $$PWD/DependLibs/libgnu/regcomp_gnu.c \
    $$PWD/DependLibs/libgnu/regex_gnu.c \
    $$PWD/DependLibs/libgnu/regex_internal_gnu.c \
    $$PWD/DependLibs/libgnu/regexec_gnu.c \
    $$PWD/DependLibs/libgnu/relocatable_gnu.c \
    $$PWD/DependLibs/libgnu/relocwrapper_gnu.c \
    $$PWD/DependLibs/libgnu/same_gnu.c \
    $$PWD/DependLibs/libgnu/search-path_gnu.c \
    $$PWD/DependLibs/libgnu/sentence_gnu.c \
    $$PWD/DependLibs/libgnu/setenv_gnu.c \
    $$PWD/DependLibs/libgnu/setlocale_gnu.c \
    $$PWD/DependLibs/libgnu/sigprocmask_gnu.c \
    $$PWD/DependLibs/libgnu/stat_gnu.c \
    $$PWD/DependLibs/libgnu/stdio-write_gnu.c \
    $$PWD/DependLibs/libgnu/stdmem_gnu.c \
    $$PWD/DependLibs/libgnu/stpcpy_gnu.c \
    $$PWD/DependLibs/libgnu/stpncpy_gnu.c \
    $$PWD/DependLibs/libgnu/str-list_gnu.c \
    $$PWD/DependLibs/libgnu/rndegd_gnu.c \
    $$PWD/DependLibs/libgnu/rndhw_gnu.c \
    $$PWD/DependLibs/libgnu/rndlinux_gnu.c \
    $$PWD/DependLibs/libgnu/rndunix_gnu.c \
    $$PWD/DependLibs/libgnu/rndw32_gnu.c \
    $$PWD/DependLibs/libgnu/rndw32ce_gnu.c \
    $$PWD/DependLibs/libgnu/safe-memfuncs_gnu.c \
    $$PWD/DependLibs/libgnu/strchrnul_gnu.c \
    $$PWD/DependLibs/libgnu/strerror-override_gnu.c \
    $$PWD/DependLibs/libgnu/strerror-sym_gnu.c \
    $$PWD/DependLibs/libgnu/strerror_gnu.c \
    $$PWD/DependLibs/libgnu/striconv_gnu.c \
    $$PWD/DependLibs/libgnu/striconveh_gnu.c \
    $$PWD/DependLibs/libgnu/striconveha_gnu.c \
    $$PWD/DependLibs/libgnu/strnlen_gnu.c \
    $$PWD/DependLibs/libgnu/strnlen1_gnu.c \
    $$PWD/DependLibs/libgnu/strsource-sym_gnu.c \
    $$PWD/DependLibs/libgnu/strsource_gnu.c \
    $$PWD/DependLibs/libgnu/strstr_gnu.c \
    $$PWD/DependLibs/libgnu/strtol_gnu.c \
    $$PWD/DependLibs/libgnu/strtoul_gnu.c \
    $$PWD/DependLibs/libgnu/structure_gnu.c \
    $$PWD/DependLibs/libgnu/styled-ostream_gnu.c \
    $$PWD/DependLibs/libgnu/styled-ostream.oo_gnu.c \
    $$PWD/DependLibs/libgnu/system-keys-dummy_gnu.c \
    $$PWD/DependLibs/libgnu/system-keys-win_gnu.c \
    $$PWD/DependLibs/libgnu/system_gnu.c \
    $$PWD/DependLibs/libgnu/system_override_gnu.c \
    $$PWD/DependLibs/libgnu/textdomain_gnu.c \
    $$PWD/DependLibs/libgnu/tmpdir_gnu.c \
    $$PWD/DependLibs/libgnu/tpm_gnu.c \
    $$PWD/DependLibs/libgnu/trim_gnu.c \
    $$PWD/DependLibs/libgnu/tsearch_gnu.c \
    $$PWD/DependLibs/libgnu/u64_gnu.c \
    $$PWD/DependLibs/libgnu/urlget_gnu.c \
    $$PWD/DependLibs/libgnu/urls_gnu.c \
    $$PWD/DependLibs/libgnu/vasnprintf_gnu.c \
    $$PWD/DependLibs/libgnu/vasprintf_gnu.c \
    $$PWD/DependLibs/libgnu/verify-tofu_gnu.c \
    $$PWD/DependLibs/libgnu/version_ans_gnu.c \
    $$PWD/DependLibs/libgnu/w32-gettext_gnu.c \
    $$PWD/DependLibs/libgnu/w32-lock_gnu.c \
    $$PWD/DependLibs/libgnu/w32-thread_gnu.c \
    $$PWD/DependLibs/libgnu/wcrtomb_gnu.c \
    $$PWD/DependLibs/libgnu/wctype-h_gnu.c \
    $$PWD/DependLibs/libgnu/wcwidth_gnu.c \
    $$PWD/DependLibs/libgnu/write-catalog_gnu.c \
    $$PWD/DependLibs/libgnu/write-csharp_gnu.c \
    $$PWD/DependLibs/libgnu/write-desktop_gnu.c \
    $$PWD/DependLibs/libgnu/write-java_gnu.c \
    $$PWD/DependLibs/libgnu/write-mo_gnu.c \
    $$PWD/DependLibs/libgnu/write-po_gnu.c \
    $$PWD/DependLibs/libgnu/write-properties_gnu.c \
    $$PWD/DependLibs/libgnu/write-qt_gnu.c \
    $$PWD/DependLibs/libgnu/write-resources_gnu.c \
    $$PWD/DependLibs/libgnu/write-stringtable_gnu.c \
    $$PWD/DependLibs/libgnu/write-tcl_gnu.c \
    $$PWD/DependLibs/libgnu/write-xml_gnu.c \
    $$PWD/DependLibs/libgnu/x-awk_gnu.c \
    $$PWD/DependLibs/libgnu/x-c_gnu.c \
    $$PWD/DependLibs/libgnu/x-csharp_gnu.c \
    $$PWD/DependLibs/libgnu/x-desktop_gnu.c \
    $$PWD/DependLibs/libgnu/x-elisp_gnu.c \
    $$PWD/DependLibs/libgnu/x-java_gnu.c \
    $$PWD/DependLibs/libgnu/x-javascript_gnu.c \
    $$PWD/DependLibs/libgnu/x-librep_gnu.c \
    $$PWD/DependLibs/libgnu/x-lisp_gnu.c \
    $$PWD/DependLibs/libgnu/x-lua_gnu.c \
    $$PWD/DependLibs/libgnu/x-perl_gnu.c \
    $$PWD/DependLibs/libgnu/x-php_gnu.c \
    $$PWD/DependLibs/libgnu/x-po_gnu.c \
    $$PWD/DependLibs/libgnu/x-python_gnu.c \
    $$PWD/DependLibs/libgnu/x-rst_gnu.c \
    $$PWD/DependLibs/libgnu/x-scheme_gnu.c \
    $$PWD/DependLibs/libgnu/x-sh_gnu.c \
    $$PWD/DependLibs/libgnu/x-smalltalk_gnu.c \
    $$PWD/DependLibs/libgnu/x-tcl_gnu.c \
    $$PWD/DependLibs/libgnu/x-vala_gnu.c \
    $$PWD/DependLibs/libgnu/x-ycp_gnu.c \
    $$PWD/DependLibs/libgnu/x509_b64_gnu.c \
    $$PWD/DependLibs/libgnu/xasprintf_gnu.c \
    $$PWD/DependLibs/libgnu/xconcat-filename_gnu.c \
    $$PWD/DependLibs/libgnu/xerror_gnu.c \
    $$PWD/DependLibs/libgnu/xgettext_gnu.c \
    $$PWD/DependLibs/libgnu/xmalloc_gnu.c \
    $$PWD/DependLibs/libgnu/xmalloca_gnu.c \
    $$PWD/DependLibs/libgnu/xreadlink_gnu.c \
    $$PWD/DependLibs/libgnu/xstrdup_gnu.c \
    $$PWD/DependLibs/libgnu/xstriconv_gnu.c \
    $$PWD/DependLibs/libgnu/xvasprintf_gnu.c

