INCLUDEPATH += $$PWD/DependLibs/libilbc/
INCLUDEPATH += $$PWD/DependLibs/libilbc/include



HEADERS += 	$$PWD/DependLibs/libilbc/../../GoTvCompilerConfig.h \
    $$PWD/DependLibs/libilbc/../../GoTvCpuArchDefines.h \
    $$PWD/DependLibs/libilbc/../../GoTvDependLibrariesConfig.h \
    $$PWD/DependLibs/libilbc/ilbc/abs_quant.h \
    $$PWD/DependLibs/libilbc/ilbc/abs_quant_loop.h \
    $$PWD/DependLibs/libilbc/ilbc/augmented_cb_corr.h \
    $$PWD/DependLibs/libilbc/ilbc/bw_expand.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_construct.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_augmentation.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_calc.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_search.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_search_core.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_update_best_index.h \
    $$PWD/DependLibs/libilbc/ilbc/chebyshev.h \
    $$PWD/DependLibs/libilbc/ilbc/comp_corr.h \
    $$PWD/DependLibs/libilbc/ilbc/constants.h \
    $$PWD/DependLibs/libilbc/ilbc/create_augmented_vec.h \
    $$PWD/DependLibs/libilbc/ilbc/decode.h \
    $$PWD/DependLibs/libilbc/ilbc/decode_residual.h \
    $$PWD/DependLibs/libilbc/ilbc/decoder_interpolate_lsf.h \
    $$PWD/DependLibs/libilbc/ilbc/defines.h \
    $$PWD/DependLibs/libilbc/ilbc/do_plc.h \
    $$PWD/DependLibs/libilbc/ilbc/encode.h \
    $$PWD/DependLibs/libilbc/ilbc/energy_inverse.h \
    $$PWD/DependLibs/libilbc/ilbc/enh_upsample.h \
    $$PWD/DependLibs/libilbc/ilbc/enhancer.h \
    $$PWD/DependLibs/libilbc/ilbc/enhancer_interface.h \
    $$PWD/DependLibs/libilbc/ilbc/filtered_cb_vecs.h \
    $$PWD/DependLibs/libilbc/ilbc/frame_classify.h \
    $$PWD/DependLibs/libilbc/ilbc/gain_dequant.h \
    $$PWD/DependLibs/libilbc/ilbc/gain_quant.h \
    $$PWD/DependLibs/libilbc/ilbc/get_cd_vec.h \
    $$PWD/DependLibs/libilbc/ilbc/get_lsp_poly.h \
    $$PWD/DependLibs/libilbc/ilbc/get_sync_seq.h \
    $$PWD/DependLibs/libilbc/ilbc/hp_input.h \
    $$PWD/DependLibs/libilbc/ilbc/hp_output.h \
    $$PWD/DependLibs/libilbc/ilbc/index_conv_dec.h \
    $$PWD/DependLibs/libilbc/ilbc/index_conv_enc.h \
    $$PWD/DependLibs/libilbc/ilbc/init_decode.h \
    $$PWD/DependLibs/libilbc/ilbc/init_encode.h \
    $$PWD/DependLibs/libilbc/ilbc/interface/ilbc.h \
    $$PWD/DependLibs/libilbc/ilbc/interpolate.h \
    $$PWD/DependLibs/libilbc/ilbc/interpolate_samples.h \
    $$PWD/DependLibs/libilbc/ilbc/lpc_encode.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_check.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_interpolate_to_poly_dec.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_interpolate_to_poly_enc.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_to_lsp.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_to_poly.h \
    $$PWD/DependLibs/libilbc/ilbc/lsp_to_lsf.h \
    $$PWD/DependLibs/libilbc/ilbc/my_corr.h \
    $$PWD/DependLibs/libilbc/ilbc/nearest_neighbor.h \
    $$PWD/DependLibs/libilbc/ilbc/pack_bits.h \
    $$PWD/DependLibs/libilbc/ilbc/poly_to_lsf.h \
    $$PWD/DependLibs/libilbc/ilbc/poly_to_lsp.h \
    $$PWD/DependLibs/libilbc/ilbc/refiner.h \
    $$PWD/DependLibs/libilbc/ilbc/simple_interpolate_lsf.h \
    $$PWD/DependLibs/libilbc/ilbc/simple_lpc_analysis.h \
    $$PWD/DependLibs/libilbc/ilbc/simple_lsf_dequant.h \
    $$PWD/DependLibs/libilbc/ilbc/simple_lsf_quant.h \
    $$PWD/DependLibs/libilbc/ilbc/smooth.h \
    $$PWD/DependLibs/libilbc/ilbc/smooth_out_data.h \
    $$PWD/DependLibs/libilbc/ilbc/sort_sq.h \
    $$PWD/DependLibs/libilbc/ilbc/split_vq.h \
    $$PWD/DependLibs/libilbc/ilbc/state_construct.h \
    $$PWD/DependLibs/libilbc/ilbc/state_search.h \
    $$PWD/DependLibs/libilbc/ilbc/swap_bytes.h \
    $$PWD/DependLibs/libilbc/ilbc/unpack_bits.h \
    $$PWD/DependLibs/libilbc/ilbc/vq3.h \
    $$PWD/DependLibs/libilbc/ilbc/vq4.h \
    $$PWD/DependLibs/libilbc/ilbc/window32_w32.h \
    $$PWD/DependLibs/libilbc/ilbc/xcorr_coef.h

SOURCES += 	\
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_augmentation_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_search_core_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/abs_quant_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/abs_quant_loop_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/augmented_cb_corr_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/bw_expand_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_construct_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_calc_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_search_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_update_best_index_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/chebyshev_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/comp_corr_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/constants_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/create_augmented_vec_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/decode_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/decode_residual_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/decoder_interpolate_lsf_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/do_plc_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/encode_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/energy_inverse_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/enh_upsample_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/enhancer_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/enhancer_interface_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/filtered_cb_vecs_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/frame_classify_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/gain_dequant_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/gain_quant_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/get_cd_vec_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/get_lsp_poly_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/get_sync_seq_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/hp_input_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/hp_output_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/ilbc_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/index_conv_dec_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/index_conv_enc_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/init_decode_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/init_encode_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/interpolate_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/interpolate_samples_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/lpc_encode_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_check_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_interpolate_to_poly_dec_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_interpolate_to_poly_enc_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_to_lsp_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_to_poly_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/lsp_to_lsf_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/my_corr_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/nearest_neighbor_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/pack_bits_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/poly_to_lsf_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/poly_to_lsp_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/refiner_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/simple_interpolate_lsf_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/simple_lpc_analysis_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/simple_lsf_dequant_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/simple_lsf_quant_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/smooth_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/smooth_out_data_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/sort_sq_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/split_vq_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/state_construct_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/state_search_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/swap_bytes_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/unpack_bits_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/vq3_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/vq4_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/window32_w32_ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/xcorr_coef_ilbc.c

