INCLUDEPATH += $$PWD/DependLibs/libilbc/
INCLUDEPATH += $$PWD/DependLibs/libilbc/include



HEADERS += 	$$PWD/DependLibs/libilbc/../../GoTvCompilerConfig.h \
    $$PWD/DependLibs/libilbc/../../GoTvCpuArchDefines.h \
    $$PWD/DependLibs/libilbc/../../GoTvDependLibrariesConfig.h \
    $$PWD/DependLibs/libilbc/ilbc/abs_quant.h \
    $$PWD/DependLibs/libilbc/ilbc/abs_quant_loop.h \
    $$PWD/DependLibs/libilbc/ilbc/augmented_cb_corr.h \
    $$PWD/DependLibs/libilbc/ilbc/bw_expand.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_construct.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_augmentation.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_calc.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_search.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_search_core.h \
    $$PWD/DependLibs/libilbc/ilbc/cb_update_best_index.h \
    $$PWD/DependLibs/libilbc/ilbc/chebyshev.h \
    $$PWD/DependLibs/libilbc/ilbc/comp_corr.h \
    $$PWD/DependLibs/libilbc/ilbc/constants.h \
    $$PWD/DependLibs/libilbc/ilbc/create_augmented_vec.h \
    $$PWD/DependLibs/libilbc/ilbc/decode.h \
    $$PWD/DependLibs/libilbc/ilbc/decode_residual.h \
    $$PWD/DependLibs/libilbc/ilbc/decoder_interpolate_lsf.h \
    $$PWD/DependLibs/libilbc/ilbc/defines.h \
    $$PWD/DependLibs/libilbc/ilbc/do_plc.h \
    $$PWD/DependLibs/libilbc/ilbc/encode.h \
    $$PWD/DependLibs/libilbc/ilbc/energy_inverse.h \
    $$PWD/DependLibs/libilbc/ilbc/enh_upsample.h \
    $$PWD/DependLibs/libilbc/ilbc/enhancer.h \
    $$PWD/DependLibs/libilbc/ilbc/enhancer_interface.h \
    $$PWD/DependLibs/libilbc/ilbc/filtered_cb_vecs.h \
    $$PWD/DependLibs/libilbc/ilbc/frame_classify.h \
    $$PWD/DependLibs/libilbc/ilbc/gain_dequant.h \
    $$PWD/DependLibs/libilbc/ilbc/gain_quant.h \
    $$PWD/DependLibs/libilbc/ilbc/get_cd_vec.h \
    $$PWD/DependLibs/libilbc/ilbc/get_lsp_poly.h \
    $$PWD/DependLibs/libilbc/ilbc/get_sync_seq.h \
    $$PWD/DependLibs/libilbc/ilbc/hp_input.h \
    $$PWD/DependLibs/libilbc/ilbc/hp_output.h \
    $$PWD/DependLibs/libilbc/ilbc/index_conv_dec.h \
    $$PWD/DependLibs/libilbc/ilbc/index_conv_enc.h \
    $$PWD/DependLibs/libilbc/ilbc/init_decode.h \
    $$PWD/DependLibs/libilbc/ilbc/init_encode.h \
    $$PWD/DependLibs/libilbc/ilbc/interface/ilbc.h \
    $$PWD/DependLibs/libilbc/ilbc/interpolate.h \
    $$PWD/DependLibs/libilbc/ilbc/interpolate_samples.h \
    $$PWD/DependLibs/libilbc/ilbc/lpc_encode.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_check.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_interpolate_to_poly_dec.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_interpolate_to_poly_enc.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_to_lsp.h \
    $$PWD/DependLibs/libilbc/ilbc/lsf_to_poly.h \
    $$PWD/DependLibs/libilbc/ilbc/lsp_to_lsf.h \
    $$PWD/DependLibs/libilbc/ilbc/my_corr.h \
    $$PWD/DependLibs/libilbc/ilbc/nearest_neighbor.h \
    $$PWD/DependLibs/libilbc/ilbc/pack_bits.h \
    $$PWD/DependLibs/libilbc/ilbc/poly_to_lsf.h \
    $$PWD/DependLibs/libilbc/ilbc/poly_to_lsp.h \
    $$PWD/DependLibs/libilbc/ilbc/refiner.h \
    $$PWD/DependLibs/libilbc/ilbc/simple_interpolate_lsf.h \
    $$PWD/DependLibs/libilbc/ilbc/simple_lpc_analysis.h \
    $$PWD/DependLibs/libilbc/ilbc/simple_lsf_dequant.h \
    $$PWD/DependLibs/libilbc/ilbc/simple_lsf_quant.h \
    $$PWD/DependLibs/libilbc/ilbc/smooth.h \
    $$PWD/DependLibs/libilbc/ilbc/smooth_out_data.h \
    $$PWD/DependLibs/libilbc/ilbc/sort_sq.h \
    $$PWD/DependLibs/libilbc/ilbc/split_vq.h \
    $$PWD/DependLibs/libilbc/ilbc/state_construct.h \
    $$PWD/DependLibs/libilbc/ilbc/state_search.h \
    $$PWD/DependLibs/libilbc/ilbc/swap_bytes.h \
    $$PWD/DependLibs/libilbc/ilbc/unpack_bits.h \
    $$PWD/DependLibs/libilbc/ilbc/vq3.h \
    $$PWD/DependLibs/libilbc/ilbc/vq4.h \
    $$PWD/DependLibs/libilbc/ilbc/window32_w32.h \
    $$PWD/DependLibs/libilbc/ilbc/xcorr_coef.h

SOURCES += 	$$PWD/DependLibs/libilbc/ilbc/abs_quant.c \
    $$PWD/DependLibs/libilbc/ilbc/abs_quant_loop.c \
    $$PWD/DependLibs/libilbc/ilbc/augmented_cb_corr.c \
    $$PWD/DependLibs/libilbc/ilbc/bw_expand.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_construct.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_augmentation.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_mem_energy_calc.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_search.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_search_core.c \
    $$PWD/DependLibs/libilbc/ilbc/cb_update_best_index.c \
    $$PWD/DependLibs/libilbc/ilbc/chebyshev.c \
    $$PWD/DependLibs/libilbc/ilbc/comp_corr.c \
    $$PWD/DependLibs/libilbc/ilbc/constants.c \
    $$PWD/DependLibs/libilbc/ilbc/create_augmented_vec.c \
    $$PWD/DependLibs/libilbc/ilbc/decode.c \
    $$PWD/DependLibs/libilbc/ilbc/decode_residual.c \
    $$PWD/DependLibs/libilbc/ilbc/decoder_interpolate_lsf.c \
    $$PWD/DependLibs/libilbc/ilbc/do_plc.c \
    $$PWD/DependLibs/libilbc/ilbc/encode.c \
    $$PWD/DependLibs/libilbc/ilbc/energy_inverse.c \
    $$PWD/DependLibs/libilbc/ilbc/enh_upsample.c \
    $$PWD/DependLibs/libilbc/ilbc/enhancer.c \
    $$PWD/DependLibs/libilbc/ilbc/enhancer_interface.c \
    $$PWD/DependLibs/libilbc/ilbc/filtered_cb_vecs.c \
    $$PWD/DependLibs/libilbc/ilbc/frame_classify.c \
    $$PWD/DependLibs/libilbc/ilbc/gain_dequant.c \
    $$PWD/DependLibs/libilbc/ilbc/gain_quant.c \
    $$PWD/DependLibs/libilbc/ilbc/get_cd_vec.c \
    $$PWD/DependLibs/libilbc/ilbc/get_lsp_poly.c \
    $$PWD/DependLibs/libilbc/ilbc/get_sync_seq.c \
    $$PWD/DependLibs/libilbc/ilbc/hp_input.c \
    $$PWD/DependLibs/libilbc/ilbc/hp_output.c \
    $$PWD/DependLibs/libilbc/ilbc/ilbc.c \
    $$PWD/DependLibs/libilbc/ilbc/index_conv_dec.c \
    $$PWD/DependLibs/libilbc/ilbc/index_conv_enc.c \
    $$PWD/DependLibs/libilbc/ilbc/init_decode.c \
    $$PWD/DependLibs/libilbc/ilbc/init_encode.c \
    $$PWD/DependLibs/libilbc/ilbc/interpolate.c \
    $$PWD/DependLibs/libilbc/ilbc/interpolate_samples.c \
    $$PWD/DependLibs/libilbc/ilbc/lpc_encode.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_check.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_interpolate_to_poly_dec.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_interpolate_to_poly_enc.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_to_lsp.c \
    $$PWD/DependLibs/libilbc/ilbc/lsf_to_poly.c \
    $$PWD/DependLibs/libilbc/ilbc/lsp_to_lsf.c \
    $$PWD/DependLibs/libilbc/ilbc/my_corr.c \
    $$PWD/DependLibs/libilbc/ilbc/nearest_neighbor.c \
    $$PWD/DependLibs/libilbc/ilbc/pack_bits.c \
    $$PWD/DependLibs/libilbc/ilbc/poly_to_lsf.c \
    $$PWD/DependLibs/libilbc/ilbc/poly_to_lsp.c \
    $$PWD/DependLibs/libilbc/ilbc/refiner.c \
    $$PWD/DependLibs/libilbc/ilbc/simple_interpolate_lsf.c \
    $$PWD/DependLibs/libilbc/ilbc/simple_lpc_analysis.c \
    $$PWD/DependLibs/libilbc/ilbc/simple_lsf_dequant.c \
    $$PWD/DependLibs/libilbc/ilbc/simple_lsf_quant.c \
    $$PWD/DependLibs/libilbc/ilbc/smooth.c \
    $$PWD/DependLibs/libilbc/ilbc/smooth_out_data.c \
    $$PWD/DependLibs/libilbc/ilbc/sort_sq.c \
    $$PWD/DependLibs/libilbc/ilbc/split_vq.c \
    $$PWD/DependLibs/libilbc/ilbc/state_construct.c \
    $$PWD/DependLibs/libilbc/ilbc/state_search.c \
    $$PWD/DependLibs/libilbc/ilbc/swap_bytes.c \
    $$PWD/DependLibs/libilbc/ilbc/unpack_bits.c \
    $$PWD/DependLibs/libilbc/ilbc/vq3.c \
    $$PWD/DependLibs/libilbc/ilbc/vq4.c \
    $$PWD/DependLibs/libilbc/ilbc/window32_w32.c \
    $$PWD/DependLibs/libilbc/ilbc/xcorr_coef.c

