win32{
DEFINES += _WINDOWS
}

DEFINES += USING_STATIC_LIBICONV

INCLUDEPATH += $$PWD/DependLibs/libiconv/

HEADERS += 	$$PWD/DependLibs/libiconv/aliases.h \
    $$PWD/DependLibs/libiconv/aliases2.h \
    $$PWD/DependLibs/libiconv/aliases_aix.h \
    $$PWD/DependLibs/libiconv/aliases_aix_sysaix.h \
    $$PWD/DependLibs/libiconv/aliases_dos.h \
    $$PWD/DependLibs/libiconv/aliases_extra.h \
    $$PWD/DependLibs/libiconv/aliases_osf1.h \
    $$PWD/DependLibs/libiconv/aliases_osf1_sysosf1.h \
    $$PWD/DependLibs/libiconv/aliases_sysaix.h \
    $$PWD/DependLibs/libiconv/aliases_syshpux.h \
    $$PWD/DependLibs/libiconv/aliases_sysosf1.h \
    $$PWD/DependLibs/libiconv/aliases_syssolaris.h \
    $$PWD/DependLibs/libiconv/armscii_8.h \
    $$PWD/DependLibs/libiconv/ascii.h \
    $$PWD/DependLibs/libiconv/atarist.h \
    $$PWD/DependLibs/libiconv/big5.h \
    $$PWD/DependLibs/libiconv/big5_2003.h \
    $$PWD/DependLibs/libiconv/big5hkscs1999.h \
    $$PWD/DependLibs/libiconv/big5hkscs2001.h \
    $$PWD/DependLibs/libiconv/big5hkscs2004.h \
    $$PWD/DependLibs/libiconv/big5hkscs2008.h \
    $$PWD/DependLibs/libiconv/c99.h \
    $$PWD/DependLibs/libiconv/canonical.h \
    $$PWD/DependLibs/libiconv/canonical_aix.h \
    $$PWD/DependLibs/libiconv/canonical_aix_sysaix.h \
    $$PWD/DependLibs/libiconv/canonical_dos.h \
    $$PWD/DependLibs/libiconv/canonical_extra.h \
    $$PWD/DependLibs/libiconv/canonical_local.h \
    $$PWD/DependLibs/libiconv/canonical_local_sysaix.h \
    $$PWD/DependLibs/libiconv/canonical_local_syshpux.h \
    $$PWD/DependLibs/libiconv/canonical_local_sysosf1.h \
    $$PWD/DependLibs/libiconv/canonical_local_syssolaris.h \
    $$PWD/DependLibs/libiconv/canonical_osf1.h \
    $$PWD/DependLibs/libiconv/canonical_osf1_sysosf1.h \
    $$PWD/DependLibs/libiconv/canonical_sysaix.h \
    $$PWD/DependLibs/libiconv/canonical_syshpux.h \
    $$PWD/DependLibs/libiconv/canonical_sysosf1.h \
    $$PWD/DependLibs/libiconv/canonical_syssolaris.h \
    $$PWD/DependLibs/libiconv/ces_big5.h \
    $$PWD/DependLibs/libiconv/ces_gbk.h \
    $$PWD/DependLibs/libiconv/cjk_variants.h \
    $$PWD/DependLibs/libiconv/cns11643.h \
    $$PWD/DependLibs/libiconv/cns11643_1.h \
    $$PWD/DependLibs/libiconv/cns11643_15.h \
    $$PWD/DependLibs/libiconv/cns11643_2.h \
    $$PWD/DependLibs/libiconv/cns11643_3.h \
    $$PWD/DependLibs/libiconv/cns11643_4.h \
    $$PWD/DependLibs/libiconv/cns11643_4a.h \
    $$PWD/DependLibs/libiconv/cns11643_4b.h \
    $$PWD/DependLibs/libiconv/cns11643_5.h \
    $$PWD/DependLibs/libiconv/cns11643_6.h \
    $$PWD/DependLibs/libiconv/cns11643_7.h \
    $$PWD/DependLibs/libiconv/cns11643_inv.h \
    $$PWD/DependLibs/libiconv/config_libiconv.h \
    $$PWD/DependLibs/libiconv/converters.h \
    $$PWD/DependLibs/libiconv/cp1046.h \
    $$PWD/DependLibs/libiconv/cp1124.h \
    $$PWD/DependLibs/libiconv/cp1125.h \
    $$PWD/DependLibs/libiconv/cp1129.h \
    $$PWD/DependLibs/libiconv/cp1131.h \
    $$PWD/DependLibs/libiconv/cp1133.h \
    $$PWD/DependLibs/libiconv/cp1161.h \
    $$PWD/DependLibs/libiconv/cp1162.h \
    $$PWD/DependLibs/libiconv/cp1163.h \
    $$PWD/DependLibs/libiconv/cp1250.h \
    $$PWD/DependLibs/libiconv/cp1251.h \
    $$PWD/DependLibs/libiconv/cp1252.h \
    $$PWD/DependLibs/libiconv/cp1253.h \
    $$PWD/DependLibs/libiconv/cp1254.h \
    $$PWD/DependLibs/libiconv/cp1255.h \
    $$PWD/DependLibs/libiconv/cp1256.h \
    $$PWD/DependLibs/libiconv/cp1257.h \
    $$PWD/DependLibs/libiconv/cp1258.h \
    $$PWD/DependLibs/libiconv/cp437.h \
    $$PWD/DependLibs/libiconv/cp737.h \
    $$PWD/DependLibs/libiconv/cp775.h \
    $$PWD/DependLibs/libiconv/cp850.h \
    $$PWD/DependLibs/libiconv/cp852.h \
    $$PWD/DependLibs/libiconv/cp853.h \
    $$PWD/DependLibs/libiconv/cp855.h \
    $$PWD/DependLibs/libiconv/cp856.h \
    $$PWD/DependLibs/libiconv/cp857.h \
    $$PWD/DependLibs/libiconv/cp858.h \
    $$PWD/DependLibs/libiconv/cp860.h \
    $$PWD/DependLibs/libiconv/cp861.h \
    $$PWD/DependLibs/libiconv/cp862.h \
    $$PWD/DependLibs/libiconv/cp863.h \
    $$PWD/DependLibs/libiconv/cp864.h \
    $$PWD/DependLibs/libiconv/cp865.h \
    $$PWD/DependLibs/libiconv/cp866.h \
    $$PWD/DependLibs/libiconv/cp869.h \
    $$PWD/DependLibs/libiconv/cp874.h \
    $$PWD/DependLibs/libiconv/cp922.h \
    $$PWD/DependLibs/libiconv/cp932.h \
    $$PWD/DependLibs/libiconv/cp932ext.h \
    $$PWD/DependLibs/libiconv/cp936.h \
    $$PWD/DependLibs/libiconv/cp936ext.h \
    $$PWD/DependLibs/libiconv/cp943.h \
    $$PWD/DependLibs/libiconv/cp949.h \
    $$PWD/DependLibs/libiconv/cp950.h \
    $$PWD/DependLibs/libiconv/cp950ext.h \
    $$PWD/DependLibs/libiconv/dec_hanyu.h \
    $$PWD/DependLibs/libiconv/dec_kanji.h \
    $$PWD/DependLibs/libiconv/euc_cn.h \
    $$PWD/DependLibs/libiconv/euc_jisx0213.h \
    $$PWD/DependLibs/libiconv/euc_jp.h \
    $$PWD/DependLibs/libiconv/euc_kr.h \
    $$PWD/DependLibs/libiconv/euc_tw.h \
    $$PWD/DependLibs/libiconv/flags.h \
    $$PWD/DependLibs/libiconv/flushwc.h \
    $$PWD/DependLibs/libiconv/gb12345.h \
    $$PWD/DependLibs/libiconv/gb12345ext.h \
    $$PWD/DependLibs/libiconv/gb18030.h \
    $$PWD/DependLibs/libiconv/gb18030ext.h \
    $$PWD/DependLibs/libiconv/gb18030uni.h \
    $$PWD/DependLibs/libiconv/gb2312.h \
    $$PWD/DependLibs/libiconv/gbk.h \
    $$PWD/DependLibs/libiconv/gbkext1.h \
    $$PWD/DependLibs/libiconv/gbkext2.h \
    $$PWD/DependLibs/libiconv/gbkext_inv.h \
    $$PWD/DependLibs/libiconv/georgian_academy.h \
    $$PWD/DependLibs/libiconv/georgian_ps.h \
    $$PWD/DependLibs/libiconv/hkscs1999.h \
    $$PWD/DependLibs/libiconv/hkscs2001.h \
    $$PWD/DependLibs/libiconv/hkscs2004.h \
    $$PWD/DependLibs/libiconv/hkscs2008.h \
    $$PWD/DependLibs/libiconv/hp_roman8.h \
    $$PWD/DependLibs/libiconv/hz.h \
    $$PWD/DependLibs/libiconv/iconv.h \
    $$PWD/DependLibs/libiconv/iconv_open1.h \
    $$PWD/DependLibs/libiconv/iconv_open2.h \
    $$PWD/DependLibs/libiconv/iso2022_cn.h \
    $$PWD/DependLibs/libiconv/iso2022_cnext.h \
    $$PWD/DependLibs/libiconv/iso2022_jp.h \
    $$PWD/DependLibs/libiconv/iso2022_jp1.h \
    $$PWD/DependLibs/libiconv/iso2022_jp2.h \
    $$PWD/DependLibs/libiconv/iso2022_jp3.h \
    $$PWD/DependLibs/libiconv/iso2022_kr.h \
    $$PWD/DependLibs/libiconv/iso646_cn.h \
    $$PWD/DependLibs/libiconv/iso646_jp.h \
    $$PWD/DependLibs/libiconv/iso8859_1.h \
    $$PWD/DependLibs/libiconv/iso8859_10.h \
    $$PWD/DependLibs/libiconv/iso8859_11.h \
    $$PWD/DependLibs/libiconv/iso8859_13.h \
    $$PWD/DependLibs/libiconv/iso8859_14.h \
    $$PWD/DependLibs/libiconv/iso8859_15.h \
    $$PWD/DependLibs/libiconv/iso8859_16.h \
    $$PWD/DependLibs/libiconv/iso8859_2.h \
    $$PWD/DependLibs/libiconv/iso8859_3.h \
    $$PWD/DependLibs/libiconv/iso8859_4.h \
    $$PWD/DependLibs/libiconv/iso8859_5.h \
    $$PWD/DependLibs/libiconv/iso8859_6.h \
    $$PWD/DependLibs/libiconv/iso8859_7.h \
    $$PWD/DependLibs/libiconv/iso8859_8.h \
    $$PWD/DependLibs/libiconv/iso8859_9.h \
    $$PWD/DependLibs/libiconv/isoir165.h \
    $$PWD/DependLibs/libiconv/isoir165ext.h \
    $$PWD/DependLibs/libiconv/java.h \
    $$PWD/DependLibs/libiconv/jisx0201.h \
    $$PWD/DependLibs/libiconv/jisx0208.h \
    $$PWD/DependLibs/libiconv/jisx0212.h \
    $$PWD/DependLibs/libiconv/jisx0213.h \
    $$PWD/DependLibs/libiconv/johab.h \
    $$PWD/DependLibs/libiconv/johab_hangul.h \
    $$PWD/DependLibs/libiconv/koi8_r.h \
    $$PWD/DependLibs/libiconv/koi8_ru.h \
    $$PWD/DependLibs/libiconv/koi8_t.h \
    $$PWD/DependLibs/libiconv/koi8_u.h \
    $$PWD/DependLibs/libiconv/ksc5601.h \
    $$PWD/DependLibs/libiconv/localcharset.h \
    $$PWD/DependLibs/libiconv/loop_unicode.h \
    $$PWD/DependLibs/libiconv/loop_wchar.h \
    $$PWD/DependLibs/libiconv/loops.h \
    $$PWD/DependLibs/libiconv/mac_arabic.h \
    $$PWD/DependLibs/libiconv/mac_centraleurope.h \
    $$PWD/DependLibs/libiconv/mac_croatian.h \
    $$PWD/DependLibs/libiconv/mac_cyrillic.h \
    $$PWD/DependLibs/libiconv/mac_greek.h \
    $$PWD/DependLibs/libiconv/mac_hebrew.h \
    $$PWD/DependLibs/libiconv/mac_iceland.h \
    $$PWD/DependLibs/libiconv/mac_roman.h \
    $$PWD/DependLibs/libiconv/mac_romania.h \
    $$PWD/DependLibs/libiconv/mac_thai.h \
    $$PWD/DependLibs/libiconv/mac_turkish.h \
    $$PWD/DependLibs/libiconv/mac_ukraine.h \
    $$PWD/DependLibs/libiconv/mulelao.h \
    $$PWD/DependLibs/libiconv/nextstep.h \
    $$PWD/DependLibs/libiconv/pt154.h \
    $$PWD/DependLibs/libiconv/relocatable.h \
    $$PWD/DependLibs/libiconv/riscos1.h \
    $$PWD/DependLibs/libiconv/rk1048.h \
    $$PWD/DependLibs/libiconv/shift_jisx0213.h \
    $$PWD/DependLibs/libiconv/sjis.h \
    $$PWD/DependLibs/libiconv/tcvn.h \
    $$PWD/DependLibs/libiconv/tds565.h \
    $$PWD/DependLibs/libiconv/tis620.h \
    $$PWD/DependLibs/libiconv/translit.h \
    $$PWD/DependLibs/libiconv/ucs2.h \
    $$PWD/DependLibs/libiconv/ucs2be.h \
    $$PWD/DependLibs/libiconv/ucs2internal.h \
    $$PWD/DependLibs/libiconv/ucs2le.h \
    $$PWD/DependLibs/libiconv/ucs2swapped.h \
    $$PWD/DependLibs/libiconv/ucs4.h \
    $$PWD/DependLibs/libiconv/ucs4be.h \
    $$PWD/DependLibs/libiconv/ucs4internal.h \
    $$PWD/DependLibs/libiconv/ucs4le.h \
    $$PWD/DependLibs/libiconv/ucs4swapped.h \
    $$PWD/DependLibs/libiconv/uhc_1.h \
    $$PWD/DependLibs/libiconv/uhc_2.h \
    $$PWD/DependLibs/libiconv/utf16.h \
    $$PWD/DependLibs/libiconv/utf16be.h \
    $$PWD/DependLibs/libiconv/utf16le.h \
    $$PWD/DependLibs/libiconv/utf32.h \
    $$PWD/DependLibs/libiconv/utf32be.h \
    $$PWD/DependLibs/libiconv/utf32le.h \
    $$PWD/DependLibs/libiconv/utf7.h \
    $$PWD/DependLibs/libiconv/utf8.h \
    $$PWD/DependLibs/libiconv/vietcomb.h \
    $$PWD/DependLibs/libiconv/viscii.h

SOURCES += 	$$PWD/DependLibs/libiconv/iconv.c \
    $$PWD/DependLibs/libiconv/localcharset.c \
    $$PWD/DependLibs/libiconv/relocatable.c

