

DEFINES += OUTSIDE_SPEEX __LITTLE_ENDIAN

INCLUDEPATH += $$PWD/../../../MediaToolsLib/
INCLUDEPATH += $$PWD/../../../MediaToolsLib/OpusTools/include
INCLUDEPATH += $$PWD/../../../MediaToolsLib/include
INCLUDEPATH += $$PWD/../../../MediaToolsLib/opus/win32
INCLUDEPATH += $$PWD/../../../MediaToolsLib/opus/celt
INCLUDEPATH += $$PWD/../../../MediaToolsLib/opus/silk
INCLUDEPATH += $$PWD/../../../MediaToolsLib/opus/silk/float
INCLUDEPATH += $$PWD/../../../
INCLUDEPATH += $$PWD/../../../../GuiInterface
INCLUDEPATH += $$PWD/../../../../GoTvCore/GoTvP2P



win32{
INCLUDEPATH += $$PWD/../../../MediaToolsLib/opus/win32
}

HEADERS += 	$$PWD/../../../../GoTvCompilerConfig.h \
	$$PWD/../../../../GoTvCpuArchDefines.h \
	$$PWD/../../../../GoTvDependLibrariesConfig.h \
	$$PWD/../../../../GoTvTargetOsConfig.h \
    $$PWD/../../../MediaToolsLib/AviDefs.h \
    $$PWD/../../../MediaToolsLib/MJPEGReader.h \
    $$PWD/../../../MediaToolsLib/MJPEGWriter.h \
    $$PWD/../../../MediaToolsLib/MediaTools.h \
    $$PWD/../../../MediaToolsLib/MyOpusHeader.h \
    $$PWD/../../../MediaToolsLib/OggBuffer.h \
    $$PWD/../../../MediaToolsLib/OggStream.h \
    $$PWD/../../../MediaToolsLib/OpusAudioDecoder.h \
    $$PWD/../../../MediaToolsLib/OpusAudioEncoder.h \
    $$PWD/../../../MediaToolsLib/OpusCallbackInterface.h \
    $$PWD/../../../MediaToolsLib/OpusFileDecoder.h \
    $$PWD/../../../MediaToolsLib/OpusFileEncoder.h \
    $$PWD/../../../MediaToolsLib/OpusTools/arch.h \
    $$PWD/../../../MediaToolsLib/OpusTools/cpusupport.h \
    $$PWD/../../../MediaToolsLib/OpusTools/diag_range.h \
    $$PWD/../../../MediaToolsLib/OpusTools/flac.h \
    $$PWD/../../../MediaToolsLib/OpusTools/include/getopt.h \
    $$PWD/../../../MediaToolsLib/OpusTools/lpc.h \
    $$PWD/../../../MediaToolsLib/OpusTools/opus_header.h \
    $$PWD/../../../MediaToolsLib/OpusTools/opusenc.h \
    $$PWD/../../../MediaToolsLib/OpusTools/os_support.h \
    $$PWD/../../../MediaToolsLib/OpusTools/picture.h \
    $$PWD/../../../MediaToolsLib/OpusTools/resample_sse.h \
    $$PWD/../../../MediaToolsLib/OpusTools/speex_resampler.h \
    $$PWD/../../../MediaToolsLib/OpusTools/stack_alloc.h \
    $$PWD/../../../MediaToolsLib/OpusTools/wav_io.h \
    $$PWD/../../../MediaToolsLib/OpusTools/wave_out.h \
    $$PWD/../../../MediaToolsLib/OpusTools/win32/config.h \
    $$PWD/../../../MediaToolsLib/OpusTools/win32/unicode_support.h \
    $$PWD/../../../MediaToolsLib/OpusTools/win32/opus_version.h \
    $$PWD/../../../MediaToolsLib/SndDefs.h \
    $$PWD/../../../MediaToolsLib/SndReader.h \
    $$PWD/../../../MediaToolsLib/SndWriter.h \
    $$PWD/../../../MediaToolsLib/include/ogg/ogg.h \
    $$PWD/../../../MediaToolsLib/include/ogg/os_types.h \
    $$PWD/../../../MediaToolsLib/include/opus.h \
    $$PWD/../../../MediaToolsLib/include/opus_custom.h \
    $$PWD/../../../MediaToolsLib/include/opus_defines.h \
    $$PWD/../../../MediaToolsLib/include/opus_multistream.h \
    $$PWD/../../../MediaToolsLib/include/opus_types.h \
    $$PWD/../../../MediaToolsLib/opus/celt/_kiss_fft_guts.h \
    $$PWD/../../../MediaToolsLib/opus/celt/arch_celt.h \
    $$PWD/../../../MediaToolsLib/opus/celt/arm/armcpu.h \
    $$PWD/../../../MediaToolsLib/opus/celt/arm/fixed_armv4.h \
    $$PWD/../../../MediaToolsLib/opus/celt/arm/fixed_armv5e.h \
    $$PWD/../../../MediaToolsLib/opus/celt/arm/kiss_fft_armv4.h \
    $$PWD/../../../MediaToolsLib/opus/celt/arm/kiss_fft_armv5e.h \
    $$PWD/../../../MediaToolsLib/opus/celt/arm/pitch_arm.h \
    $$PWD/../../../MediaToolsLib/opus/celt/bands.h \
    $$PWD/../../../MediaToolsLib/opus/celt/celt.h \
    $$PWD/../../../MediaToolsLib/opus/celt/celt_lpc.h \
    $$PWD/../../../MediaToolsLib/opus/celt/cpu_support.h \
    $$PWD/../../../MediaToolsLib/opus/celt/cwrs.h \
    $$PWD/../../../MediaToolsLib/opus/celt/ecintrin.h \
    $$PWD/../../../MediaToolsLib/opus/celt/entcode.h \
    $$PWD/../../../MediaToolsLib/opus/celt/entdec.h \
    $$PWD/../../../MediaToolsLib/opus/celt/entenc.h \
    $$PWD/../../../MediaToolsLib/opus/celt/fixed_debug.h \
    $$PWD/../../../MediaToolsLib/opus/celt/fixed_generic.h \
    $$PWD/../../../MediaToolsLib/opus/celt/float_cast.h \
    $$PWD/../../../MediaToolsLib/opus/celt/kiss_fft.h \
    $$PWD/../../../MediaToolsLib/opus/celt/laplace.h \
    $$PWD/../../../MediaToolsLib/opus/celt/mathops.h \
    $$PWD/../../../MediaToolsLib/opus/celt/mdct.h \
    $$PWD/../../../MediaToolsLib/opus/celt/mfrngcod.h \
    $$PWD/../../../MediaToolsLib/opus/celt/modes.h \
    $$PWD/../../../MediaToolsLib/opus/celt/os_support.h \
    $$PWD/../../../MediaToolsLib/opus/celt/pitch.h \
    $$PWD/../../../MediaToolsLib/opus/celt/quant_bands.h \
    $$PWD/../../../MediaToolsLib/opus/celt/rate.h \
    $$PWD/../../../MediaToolsLib/opus/celt/stack_alloc.h \
    $$PWD/../../../MediaToolsLib/opus/celt/static_modes_fixed.h \
    $$PWD/../../../MediaToolsLib/opus/celt/static_modes_float.h \
    $$PWD/../../../MediaToolsLib/opus/celt/vq.h \
    $$PWD/../../../MediaToolsLib/opus/celt/x86/pitch_sse.h \
    $$PWD/../../../MediaToolsLib/opus/silk/API.h \
    $$PWD/../../../MediaToolsLib/opus/silk/Inlines.h \
    $$PWD/../../../MediaToolsLib/opus/silk/MacroCount.h \
    $$PWD/../../../MediaToolsLib/opus/silk/MacroDebug.h \
    $$PWD/../../../MediaToolsLib/opus/silk/PLC.h \
    $$PWD/../../../MediaToolsLib/opus/silk/SigProc_FIX.h \
    $$PWD/../../../MediaToolsLib/opus/silk/control.h \
    $$PWD/../../../MediaToolsLib/opus/silk/debug.h \
    $$PWD/../../../MediaToolsLib/opus/silk/define.h \
    $$PWD/../../../MediaToolsLib/opus/silk/errors.h \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/main_FIX.h \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/structs_FIX.h \
    $$PWD/../../../MediaToolsLib/opus/silk/float/SigProc_FLP.h \
    $$PWD/../../../MediaToolsLib/opus/silk/float/main_FLP.h \
    $$PWD/../../../MediaToolsLib/opus/silk/float/structs_FLP.h \
    $$PWD/../../../MediaToolsLib/opus/silk/macros.h \
    $$PWD/../../../MediaToolsLib/opus/silk/main.h \
    $$PWD/../../../MediaToolsLib/opus/silk/pitch_est_defines.h \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_private.h \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_rom.h \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_structs.h \
    $$PWD/../../../MediaToolsLib/opus/silk/structs.h \
    $$PWD/../../../MediaToolsLib/opus/silk/tables.h \
    $$PWD/../../../MediaToolsLib/opus/silk/tuning_parameters.h \
    $$PWD/../../../MediaToolsLib/opus/silk/typedef.h \
    $$PWD/../../../MediaToolsLib/opus/src/analysis.h \
    $$PWD/../../../MediaToolsLib/opus/src/mlp.h \
    $$PWD/../../../MediaToolsLib/opus/src/opus_private.h \
    $$PWD/../../../MediaToolsLib/opus/src/tansig_table.h \
    $$PWD/../../../MediaToolsLib/opus/win32/config.h


SOURCES += 	$$PWD/../../AviDefs.cpp \
	$$PWD/../../MJPEGReader.cpp \
	$$PWD/../../MJPEGWriter.cpp \
	$$PWD/../../MediaTools.cpp \
	$$PWD/../../MyOpusHeader.cpp \
	$$PWD/../../OggBuffer.cpp \
	$$PWD/../../OggStream.cpp \
	$$PWD/../../OpusAudioDecoder.cpp \
	$$PWD/../../OpusAudioEncoder.cpp \
	$$PWD/../../OpusFileDecoder.cpp \
	$$PWD/../../OpusFileEncoder.cpp \
	$$PWD/../../OpusTools/audio-in.c \
	$$PWD/../../OpusTools/diag_range.c \
	$$PWD/../../OpusTools/flac.c \
	$$PWD/../../OpusTools/lpc.c \
	$$PWD/../../OpusTools/opus_header.c \
	$$PWD/../../OpusTools/opusdec.c \
	$$PWD/../../OpusTools/opusenc.c \
	$$PWD/../../OpusTools/picture.c \
	$$PWD/../../OpusTools/wav_io.c \
	$$PWD/../../OpusTools/wave_out.c \
	$$PWD/../../OpusTools/win32/unicode_support.c \
	$$PWD/../../SndDefs.cpp \
	$$PWD/../../SndReader.cpp \
	$$PWD/../../SndWriter.cpp \
	$$PWD/../../ogg/bitwise.c \
	$$PWD/../../ogg/framing.c \
    $$PWD/../../../MediaToolsLib/opus/celt/arm/arm_celt_map.c \
    $$PWD/../../../MediaToolsLib/opus/celt/arm/armcpu.c \
    $$PWD/../../../MediaToolsLib/opus/celt/bands.c \
    $$PWD/../../../MediaToolsLib/opus/celt/celt.c \
    $$PWD/../../../MediaToolsLib/opus/celt/celt_decoder.c \
    $$PWD/../../../MediaToolsLib/opus/celt/celt_encoder.c \
    $$PWD/../../../MediaToolsLib/opus/celt/celt_lpc.c \
    $$PWD/../../../MediaToolsLib/opus/celt/cwrs.c \
    $$PWD/../../../MediaToolsLib/opus/celt/entcode.c \
    $$PWD/../../../MediaToolsLib/opus/celt/entdec.c \
    $$PWD/../../../MediaToolsLib/opus/celt/entenc.c \
    $$PWD/../../../MediaToolsLib/opus/celt/kiss_fft.c \
    $$PWD/../../../MediaToolsLib/opus/celt/laplace.c \
    $$PWD/../../../MediaToolsLib/opus/celt/mathops.c \
    $$PWD/../../../MediaToolsLib/opus/celt/mdct.c \
    $$PWD/../../../MediaToolsLib/opus/celt/modes.c \
    $$PWD/../../../MediaToolsLib/opus/celt/pitch.c \
    $$PWD/../../../MediaToolsLib/opus/celt/quant_bands.c \
    $$PWD/../../../MediaToolsLib/opus/celt/rate.c \
    $$PWD/../../../MediaToolsLib/opus/celt/vq.c \
    $$PWD/../../../MediaToolsLib/opus/silk/A2NLSF.c \
    $$PWD/../../../MediaToolsLib/opus/silk/CNG.c \
    $$PWD/../../../MediaToolsLib/opus/silk/HP_variable_cutoff.c \
    $$PWD/../../../MediaToolsLib/opus/silk/LPC_analysis_filter.c \
    $$PWD/../../../MediaToolsLib/opus/silk/LPC_inv_pred_gain.c \
    $$PWD/../../../MediaToolsLib/opus/silk/LP_variable_cutoff.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NLSF2A.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NLSF_VQ.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NLSF_VQ_weights_laroia.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NLSF_decode.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NLSF_del_dec_quant.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NLSF_encode.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NLSF_stabilize.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NLSF_unpack.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NSQ.c \
    $$PWD/../../../MediaToolsLib/opus/silk/NSQ_del_dec.c \
    $$PWD/../../../MediaToolsLib/opus/silk/PLC.c \
    $$PWD/../../../MediaToolsLib/opus/silk/VAD.c \
    $$PWD/../../../MediaToolsLib/opus/silk/VQ_WMat_EC.c \
    $$PWD/../../../MediaToolsLib/opus/silk/ana_filt_bank_1.c \
    $$PWD/../../../MediaToolsLib/opus/silk/biquad_alt.c \
    $$PWD/../../../MediaToolsLib/opus/silk/bwexpander.c \
    $$PWD/../../../MediaToolsLib/opus/silk/bwexpander_32.c \
    $$PWD/../../../MediaToolsLib/opus/silk/check_control_input.c \
    $$PWD/../../../MediaToolsLib/opus/silk/code_signs.c \
    $$PWD/../../../MediaToolsLib/opus/silk/control_SNR.c \
    $$PWD/../../../MediaToolsLib/opus/silk/control_audio_bandwidth.c \
    $$PWD/../../../MediaToolsLib/opus/silk/control_codec.c \
    $$PWD/../../../MediaToolsLib/opus/silk/debug.c \
    $$PWD/../../../MediaToolsLib/opus/silk/dec_API.c \
    $$PWD/../../../MediaToolsLib/opus/silk/decode_core.c \
    $$PWD/../../../MediaToolsLib/opus/silk/decode_frame.c \
    $$PWD/../../../MediaToolsLib/opus/silk/decode_indices.c \
    $$PWD/../../../MediaToolsLib/opus/silk/decode_parameters.c \
    $$PWD/../../../MediaToolsLib/opus/silk/decode_pitch.c \
    $$PWD/../../../MediaToolsLib/opus/silk/decode_pulses.c \
    $$PWD/../../../MediaToolsLib/opus/silk/decoder_set_fs.c \
    $$PWD/../../../MediaToolsLib/opus/silk/enc_API.c \
    $$PWD/../../../MediaToolsLib/opus/silk/encode_indices.c \
    $$PWD/../../../MediaToolsLib/opus/silk/encode_pulses.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/LTP_analysis_filter_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/LTP_scale_ctrl_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/apply_sine_window_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/autocorr_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/burg_modified_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/corrMatrix_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/encode_frame_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/find_LPC_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/find_LTP_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/find_pitch_lags_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/find_pred_coefs_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/k2a_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/k2a_Q16_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/noise_shape_analysis_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/pitch_analysis_core_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/prefilter_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/process_gains_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/regularize_correlations_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/residual_energy16_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/residual_energy_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/schur64_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/schur_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/solve_LS_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/vector_ops_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/fixed/warped_autocorrelation_FIX.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/LPC_analysis_filter_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/LPC_inv_pred_gain_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/LTP_analysis_filter_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/LTP_scale_ctrl_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/apply_sine_window_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/autocorrelation_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/burg_modified_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/bwexpander_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/corrMatrix_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/encode_frame_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/energy_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/find_LPC_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/find_LTP_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/find_pitch_lags_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/find_pred_coefs_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/inner_product_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/k2a_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/levinsondurbin_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/noise_shape_analysis_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/pitch_analysis_core_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/prefilter_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/process_gains_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/regularize_correlations_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/residual_energy_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/scale_copy_vector_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/scale_vector_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/schur_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/solve_LS_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/sort_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/warped_autocorrelation_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/float/wrappers_FLP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/gain_quant.c \
    $$PWD/../../../MediaToolsLib/opus/silk/init_decoder.c \
    $$PWD/../../../MediaToolsLib/opus/silk/init_encoder.c \
    $$PWD/../../../MediaToolsLib/opus/silk/inner_prod_aligned.c \
    $$PWD/../../../MediaToolsLib/opus/silk/interpolate.c \
    $$PWD/../../../MediaToolsLib/opus/silk/lin2log.c \
    $$PWD/../../../MediaToolsLib/opus/silk/log2lin.c \
    $$PWD/../../../MediaToolsLib/opus/silk/pitch_est_tables.c \
    $$PWD/../../../MediaToolsLib/opus/silk/process_NLSFs.c \
    $$PWD/../../../MediaToolsLib/opus/silk/quant_LTP_gains.c \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler.c \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_down2.c \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_down2_3.c \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_private_AR2.c \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_private_IIR_FIR.c \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_private_down_FIR.c \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_private_up2_HQ.c \
    $$PWD/../../../MediaToolsLib/opus/silk/resampler_rom.c \
    $$PWD/../../../MediaToolsLib/opus/silk/shell_coder.c \
    $$PWD/../../../MediaToolsLib/opus/silk/sigm_Q15.c \
    $$PWD/../../../MediaToolsLib/opus/silk/sort.c \
    $$PWD/../../../MediaToolsLib/opus/silk/stereo_LR_to_MS.c \
    $$PWD/../../../MediaToolsLib/opus/silk/stereo_MS_to_LR.c \
    $$PWD/../../../MediaToolsLib/opus/silk/stereo_decode_pred.c \
    $$PWD/../../../MediaToolsLib/opus/silk/stereo_encode_pred.c \
    $$PWD/../../../MediaToolsLib/opus/silk/stereo_find_predictor.c \
    $$PWD/../../../MediaToolsLib/opus/silk/stereo_quant_pred.c \
    $$PWD/../../../MediaToolsLib/opus/silk/sum_sqr_shift.c \
    $$PWD/../../../MediaToolsLib/opus/silk/table_LSF_cos.c \
    $$PWD/../../../MediaToolsLib/opus/silk/tables_LTP.c \
    $$PWD/../../../MediaToolsLib/opus/silk/tables_NLSF_CB_NB_MB.c \
    $$PWD/../../../MediaToolsLib/opus/silk/tables_NLSF_CB_WB.c \
    $$PWD/../../../MediaToolsLib/opus/silk/tables_gain.c \
    $$PWD/../../../MediaToolsLib/opus/silk/tables_other.c \
    $$PWD/../../../MediaToolsLib/opus/silk/tables_pitch_lag.c \
    $$PWD/../../../MediaToolsLib/opus/silk/tables_pulses_per_block.c \
    $$PWD/../../../MediaToolsLib/opus/src/analysis.c \
    $$PWD/../../../MediaToolsLib/opus/src/mlp.c \
    $$PWD/../../../MediaToolsLib/opus/src/mlp_data.c \
    $$PWD/../../../MediaToolsLib/opus/src/opus.c \
    $$PWD/../../../MediaToolsLib/opus/src/opus_decoder.c \
    $$PWD/../../../MediaToolsLib/opus/src/opus_encoder.c \
    $$PWD/../../../MediaToolsLib/opus/src/opus_multistream.c \
    $$PWD/../../../MediaToolsLib/opus/src/opus_multistream_decoder.c \
    $$PWD/../../../MediaToolsLib/opus/src/opus_multistream_encoder.c \
    $$PWD/../../../MediaToolsLib/opus/src/repacketizer.c \
    $$PWD/../../OpusTools/resample_mediatools.c

