
DEFINES += LIBOPENMPT_BUILD LIBOPENMPT_BUILD_FULL MPT_ENABLE_DLOPEN

INCLUDEPATH += $$PWD/DependLibs/libopenmpt/
INCLUDEPATH += $$PWD/DependLibs/libopenmpt/include
INCLUDEPATH += $$PWD/DependLibs/libopenmpt/include/ogg/include
INCLUDEPATH += $$PWD/DependLibs/libopenmpt/include/vorbis/include
INCLUDEPATH += $$PWD/DependLibs/libopenmpt/include/zlib
INCLUDEPATH += $$PWD/DependLibs/libopenmpt/common
INCLUDEPATH += $$PWD/DependLibs/libopenmpt/soundlib
INCLUDEPATH += $$PWD/DependLibs/libopenmpt/build/svn_version

HEADERS += 	$$PWD/DependLibs/libopenmpt/common/BuildSettings.h \
    $$PWD/DependLibs/libopenmpt/common/CompilerDetect.h \
    $$PWD/DependLibs/libopenmpt/common/ComponentManager.h \
    $$PWD/DependLibs/libopenmpt/common/Endianness.h \
    $$PWD/DependLibs/libopenmpt/common/FileReader.h \
    $$PWD/DependLibs/libopenmpt/common/FileReaderFwd.h \
    $$PWD/DependLibs/libopenmpt/common/FlagSet.h \
    $$PWD/DependLibs/libopenmpt/common/Logging.h \
    $$PWD/DependLibs/libopenmpt/common/Profiler.h \
    $$PWD/DependLibs/libopenmpt/common/StringFixer.h \
    $$PWD/DependLibs/libopenmpt/common/WriteMemoryDump.h \
    $$PWD/DependLibs/libopenmpt/common/misc_util.h \
    $$PWD/DependLibs/libopenmpt/common/mptBufferIO.h \
    $$PWD/DependLibs/libopenmpt/common/mptCPU.h \
    $$PWD/DependLibs/libopenmpt/common/mptCRC.h \
    $$PWD/DependLibs/libopenmpt/common/mptFileIO.h \
    $$PWD/DependLibs/libopenmpt/common/mptIO.h \
    $$PWD/DependLibs/libopenmpt/common/mptLibrary.h \
    $$PWD/DependLibs/libopenmpt/common/mptMutex.h \
    $$PWD/DependLibs/libopenmpt/common/mptOS.h \
    $$PWD/DependLibs/libopenmpt/common/mptPathString.h \
    $$PWD/DependLibs/libopenmpt/common/mptRandom.h \
    $$PWD/DependLibs/libopenmpt/common/mptString.h \
    $$PWD/DependLibs/libopenmpt/common/mptStringFormat.h \
    $$PWD/DependLibs/libopenmpt/common/mptStringParse.h \
    $$PWD/DependLibs/libopenmpt/common/mptThread.h \
    $$PWD/DependLibs/libopenmpt/common/mptTime.h \
    $$PWD/DependLibs/libopenmpt/common/mptTypeTraits.h \
    $$PWD/DependLibs/libopenmpt/common/mptUUID.h \
    $$PWD/DependLibs/libopenmpt/common/mptWine.h \
    $$PWD/DependLibs/libopenmpt/common/serialization_utils.h \
    $$PWD/DependLibs/libopenmpt/common/stdafx.h \
    $$PWD/DependLibs/libopenmpt/common/typedefs.h \
    $$PWD/DependLibs/libopenmpt/common/version.h \
    $$PWD/DependLibs/libopenmpt/common/versionNumber.h \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt.h \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt.hpp \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_config.h \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_ext.h \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_ext.hpp \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_ext_impl.hpp \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_impl.hpp \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_internal.h \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_stream_callbacks_buffer.h \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_stream_callbacks_fd.h \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_stream_callbacks_file.h \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_version.h \
    $$PWD/DependLibs/libopenmpt/soundbase/SampleFormat.h \
    $$PWD/DependLibs/libopenmpt/soundbase/SampleFormatConverters.h \
    $$PWD/DependLibs/libopenmpt/soundbase/SampleFormatCopy.h \
    $$PWD/DependLibs/libopenmpt/sounddsp/AGC.h \
    $$PWD/DependLibs/libopenmpt/sounddsp/DSP.h \
    $$PWD/DependLibs/libopenmpt/sounddsp/EQ.h \
    $$PWD/DependLibs/libopenmpt/sounddsp/Reverb.h \
    $$PWD/DependLibs/libopenmpt/soundlib/AudioCriticalSection.h \
    $$PWD/DependLibs/libopenmpt/soundlib/AudioReadTarget.h \
    $$PWD/DependLibs/libopenmpt/soundlib/ChunkReader.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Container.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Dither.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Dlsbank.h \
    $$PWD/DependLibs/libopenmpt/soundlib/FloatMixer.h \
    $$PWD/DependLibs/libopenmpt/soundlib/ITCompression.h \
    $$PWD/DependLibs/libopenmpt/soundlib/ITTools.h \
    $$PWD/DependLibs/libopenmpt/soundlib/IntMixer.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Loaders.h \
    $$PWD/DependLibs/libopenmpt/soundlib/MIDIEvents.h \
    $$PWD/DependLibs/libopenmpt/soundlib/MIDIMacros.h \
    $$PWD/DependLibs/libopenmpt/soundlib/MPEGFrame.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Message.h \
    $$PWD/DependLibs/libopenmpt/soundlib/MixFuncTable.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Mixer.h \
    $$PWD/DependLibs/libopenmpt/soundlib/MixerInterface.h \
    $$PWD/DependLibs/libopenmpt/soundlib/MixerLoops.h \
    $$PWD/DependLibs/libopenmpt/soundlib/MixerSettings.h \
    $$PWD/DependLibs/libopenmpt/soundlib/ModChannel.h \
    $$PWD/DependLibs/libopenmpt/soundlib/ModInstrument.h \
    $$PWD/DependLibs/libopenmpt/soundlib/ModSample.h \
    $$PWD/DependLibs/libopenmpt/soundlib/ModSampleCopy.h \
    $$PWD/DependLibs/libopenmpt/soundlib/ModSequence.h \
    $$PWD/DependLibs/libopenmpt/soundlib/OggStream.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Paula.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Resampler.h \
    $$PWD/DependLibs/libopenmpt/soundlib/RowVisitor.h \
    $$PWD/DependLibs/libopenmpt/soundlib/S3MTools.h \
    $$PWD/DependLibs/libopenmpt/soundlib/SampleIO.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Snd_defs.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Sndfile.h \
    $$PWD/DependLibs/libopenmpt/soundlib/SoundFilePlayConfig.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Tables.h \
    $$PWD/DependLibs/libopenmpt/soundlib/Tagging.h \
    $$PWD/DependLibs/libopenmpt/soundlib/UMXTools.h \
    $$PWD/DependLibs/libopenmpt/soundlib/WAVTools.h \
    $$PWD/DependLibs/libopenmpt/soundlib/WindowedFIR.h \
    $$PWD/DependLibs/libopenmpt/soundlib/XMTools.h \
    $$PWD/DependLibs/libopenmpt/soundlib/mod_specifications.h \
    $$PWD/DependLibs/libopenmpt/soundlib/modcommand.h \
    $$PWD/DependLibs/libopenmpt/soundlib/modsmp_ctrl.h \
    $$PWD/DependLibs/libopenmpt/soundlib/pattern.h \
    $$PWD/DependLibs/libopenmpt/soundlib/patternContainer.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/DigiBoosterEcho.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/LFOPlugin.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/OpCodes.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/PlugInterface.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/PluginEventQueue.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/PluginManager.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/PluginMixBuffer.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/PluginStructs.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Chorus.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Compressor.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/DMOPlugin.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Distortion.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Echo.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Flanger.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Gargle.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/I3DL2Reverb.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/ParamEq.h \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/WavesReverb.h \
    $$PWD/DependLibs/libopenmpt/soundlib/tuning.h \
    $$PWD/DependLibs/libopenmpt/soundlib/tuningbase.h \
    $$PWD/DependLibs/libopenmpt/soundlib/tuningcollection.h

SOURCES += 	$$PWD/DependLibs/libopenmpt/common/ComponentManager.cpp \
    $$PWD/DependLibs/libopenmpt/common/FileReader.cpp \
    $$PWD/DependLibs/libopenmpt/common/Logging.cpp \
    $$PWD/DependLibs/libopenmpt/common/Profiler.cpp \
    $$PWD/DependLibs/libopenmpt/common/misc_util.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptCPU.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptFileIO.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptIO.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptLibrary.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptOS.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptPathString.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptRandom.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptString.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptStringFormat.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptStringParse.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptTime.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptUUID.cpp \
    $$PWD/DependLibs/libopenmpt/common/mptWine.cpp \
    $$PWD/DependLibs/libopenmpt/common/serialization_utils.cpp \
    $$PWD/DependLibs/libopenmpt/common/stdafx.cpp \
    $$PWD/DependLibs/libopenmpt/common/typedefs.cpp \
    $$PWD/DependLibs/libopenmpt/common/version.cpp \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_c.cpp \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_cxx.cpp \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_ext_impl.cpp \
    $$PWD/DependLibs/libopenmpt/libopenmpt/libopenmpt_impl.cpp \
    $$PWD/DependLibs/libopenmpt/sounddsp/AGC.cpp \
    $$PWD/DependLibs/libopenmpt/sounddsp/DSP.cpp \
    $$PWD/DependLibs/libopenmpt/sounddsp/EQ.cpp \
    $$PWD/DependLibs/libopenmpt/sounddsp/Reverb.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/AudioCriticalSection.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ContainerMMCMP.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ContainerPP20.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ContainerUMX.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ContainerXPK.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Dither.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Dlsbank.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Fastmix.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ITCompression.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ITTools.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/InstrumentExtensions.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_669.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_amf.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_ams.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_dbm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_digi.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_dmf.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_dsm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_dtm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_far.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_gdm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_imf.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_it.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_itp.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_mdl.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_med.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_mid.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_mo3.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_mod.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_mt2.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_mtm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_okt.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_plm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_psm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_ptm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_s3m.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_sfx.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_stm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_stp.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_uax.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_ult.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_wav.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Load_xm.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/MIDIEvents.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/MIDIMacros.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/MPEGFrame.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Message.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/MixFuncTable.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/MixerLoops.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/MixerSettings.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ModChannel.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ModInstrument.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ModSample.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/ModSequence.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/OggStream.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Paula.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/RowVisitor.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/S3MTools.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/SampleFormatFLAC.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/SampleFormatMP3.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/SampleFormatMediaFoundation.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/SampleFormatOpus.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/SampleFormatVorbis.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/SampleFormats.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/SampleIO.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Snd_flt.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Snd_fx.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Sndfile.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Sndmix.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/SoundFilePlayConfig.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Tables.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/Tagging.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/UMXTools.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/UpgradeModule.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/WAVTools.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/WindowedFIR.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/XMTools.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/load_j2b.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/mod_specifications.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/modcommand.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/modsmp_ctrl.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/pattern.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/patternContainer.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/DigiBoosterEcho.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/LFOPlugin.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/PlugInterface.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/PluginManager.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Chorus.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Compressor.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/DMOPlugin.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Distortion.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Echo.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Flanger.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/Gargle.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/I3DL2Reverb.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/ParamEq.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/plugins/dmo/WavesReverb.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/tuning.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/tuningCollection.cpp \
    $$PWD/DependLibs/libopenmpt/soundlib/tuningbase.cpp

