

INCLUDEPATH += $$PWD/DependLibs/libopencore-amr/amrnb/dec
INCLUDEPATH += $$PWD/DependLibs/libopencore-amr/amrnb/enc
INCLUDEPATH += $$PWD/DependLibs/libopencore-amr/amrnb/common
INCLUDEPATH += $$PWD/DependLibs/libopencore-amr/oscl
INCLUDEPATH += $$PWD/DependLibs/libopencore-amr/amrwb
INCLUDEPATH += $$PWD/DependLibs/libopencore-amr/src
INCLUDEPATH += $$PWD/DependLibs/libopencore-amr/include
INCLUDEPATH += $$PWD/DependLibs/libopencore-amr/

HEADERS += 	$$PWD/DependLibs/libopencore-amr/../../GoTvCompilerConfig.h \
    $$PWD/DependLibs/libopencore-amr/../../GoTvCpuArchDefines.h \
    $$PWD/DependLibs/libopencore-amr/../../GoTvDependLibrariesConfig.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/abs_s.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/add.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/az_lsp.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/basic_op.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/basic_op_arm_gcc_v5.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/basic_op_c_equivalent.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/basicop_malloc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/bitno_tab.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/bitreorder_tab.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/bytesused.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/cnst.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/cnst_vad.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/common_amrnb.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/d_gain_c.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/d_gain_p.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/d_plsf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/div_s.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/dtx_common_def.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/frame.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/frame_type_3gpp.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/gc_pred.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/get_const_tbls.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/gmed_n.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/gsm_amr_typedefs.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/int_lpc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/int_lsf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/inv_sqrt.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_add.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_add_c.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_comp.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_extract.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_mac.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_msu.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_mult.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_negate.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_shl.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_shr.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_shr_r.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_sub.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/log2.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/log2_norm.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsfwt.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp_az.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp_lsf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp_tab.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/mac_32.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/mode.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/mpy_32.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/mpy_32_16.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/mult.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/mult_r.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/n_proc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/negate.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/norm_l.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/norm_s.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/oper_32b.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/p_ol_wgh.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/pow2.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/pred_lt.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/pvgsmamr.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/q_plsf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/q_plsf_3_tbl.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/q_plsf_5_tbl.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/qgain475_tab.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/qua_gain.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/qua_gain_tbl.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/reorder.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/residu.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/reverse_bits.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/round.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/set_zero.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/shl.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/shr.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/shr_r.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/sqrt_l.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/sub.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/syn_filt.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/typedef.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/vad.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/weight_a.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/window_tab.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/wmf_to_ets.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/a_refl.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/agc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/amrdecode.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/b_cn_cod.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/bgnscd.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/c_g_aver.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d1035pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d2_11pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d2_9pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d3_14pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d4_17pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d8_31pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_amr.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_gain.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_lag3.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_lag6.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dtx_dec.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/ec_gains.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/ex_ctrl.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/gsmamr_dec.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/if2_to_ets.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/lsp_avg.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/ph_disp.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/post_pro.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/preemph.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/pstfilt.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/pvgsmamrdecoder.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/pvgsmamrdecoder_dpi.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/sp_dec.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/amrencode.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/autocorr.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c1035pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c2_11pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c2_9pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c3_14pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c4_17pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c8_31pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/calc_cor.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/calc_en.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cbsearch.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cl_ltp.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cod_amr.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/convolve.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cor_h.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cor_h_x.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cor_h_x2.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/div_32.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/dtx_enc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/enc_lag3.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/enc_lag6.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/ets_to_if2.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/ets_to_wmf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/g_adapt.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/g_code.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/g_pitch.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/gain_q.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/gsmamr_enc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/hp_max.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/inter_36.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/inter_36_tab.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/l_abs.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/lag_wind.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/lag_wind_tab.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/levinson.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/lpc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/ol_ltp.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/pitch_fr.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/pitch_ol.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/pre_big.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/pre_proc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/prm2bits.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/q_gain_c.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/q_gain_p.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/qgain475.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/qgain795.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/s10_8pf.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/set_sign.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/sid_sync.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/sp_enc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/spreproc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/spstproc.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/ton_stab.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/vad1.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/vad2.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/interf_dec.h \
    $$PWD/DependLibs/libopencore-amr/amrnb/interf_enc.h \
    $$PWD/DependLibs/libopencore-amr/amrwb/dec_if.h \
    $$PWD/DependLibs/libopencore-amr/amrwb/if_rom.h \
    $$PWD/DependLibs/libopencore-amr/config_libopencore-amr.h \
    $$PWD/DependLibs/libopencore-amr/include/decoder_amr_wb.h \
    $$PWD/DependLibs/libopencore-amr/include/pvamrwbdecoder_api.h \
    $$PWD/DependLibs/libopencore-amr/include/pvgsmamrdecoderinterface.h \
    $$PWD/DependLibs/libopencore-amr/oscl/oscl_base.h \
    $$PWD/DependLibs/libopencore-amr/oscl/oscl_base_macros.h \
    $$PWD/DependLibs/libopencore-amr/oscl/oscl_mem.h \
    $$PWD/DependLibs/libopencore-amr/src/dtx.h \
    $$PWD/DependLibs/libopencore-amr/src/e_pv_amrwbdec.h \
    $$PWD/DependLibs/libopencore-amr/src/get_amr_wb_bits.h \
    $$PWD/DependLibs/libopencore-amr/src/mime_io.h \
    $$PWD/DependLibs/libopencore-amr/src/normalize_amr_wb.h \
    $$PWD/DependLibs/libopencore-amr/src/pv_amr_wb_type_defs.h \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwb_math_op.h \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwbdecoder.h \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwbdecoder_acelp.h \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwbdecoder_basic_op.h \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwbdecoder_basic_op_cequivalent.h \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwbdecoder_basic_op_gcc_armv5.h \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwbdecoder_cnst.h \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwbdecoder_mem_funcs.h \
    $$PWD/DependLibs/libopencore-amr/src/q_pulse.h \
    $$PWD/DependLibs/libopencore-amr/src/qisf_ns.h \
    $$PWD/DependLibs/libopencore-amr/src/qpisf_2s.h \
    $$PWD/DependLibs/libopencore-amr/src/synthesis_amr_wb.h

SOURCES += 	$$PWD/DependLibs/libopencore-amr/amrnb/common/add.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/az_lsp.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/bitno_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/bitreorder_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/bits2prm.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/c2_9pf_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/copy.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/div_32_common.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/div_s.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/extract_h.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/extract_l.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/gains_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/gc_pred.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/get_const_tbls.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/gmed_n.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/gray_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/grid_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/int_lpc.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/inv_sqrt.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/inv_sqrt_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_abs_common.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_deposit_h.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_deposit_l.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/l_shr_r.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/log2.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/log2_norm.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/log2_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsfwt.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp_az.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp_lsf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp_lsf_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/lsp_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/mult_r.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/negate.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/norm_l.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/norm_s.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/overflow_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/ph_disp_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/pow2.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/pow2_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/pred_lt.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/q_plsf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/q_plsf_3.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/q_plsf_3_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/q_plsf_5.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/q_plsf_5_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/qua_gain_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/reorder.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/residu.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/round.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/set_zero.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/shr.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/shr_r.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/sqrt_l.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/sqrt_l_tbl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/sub.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/syn_filt.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/weight_a.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/common/window_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/a_refl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/agc.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/amrdecode.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/b_cn_cod.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/bgnscd.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/c_g_aver.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d1035pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d2_11pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d2_9pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d3_14pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d4_17pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d8_31pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d_gain_c.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d_gain_p.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d_plsf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d_plsf_3.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/d_plsf_5.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_amr.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_gain.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_input_format_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_lag3.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dec_lag6.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/decoder_gsm_amr.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/dtx_dec.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/ec_gains.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/ex_ctrl.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/if2_to_ets.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/int_lsf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/lsp_avg.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/ph_disp.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/post_pro.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/preemph.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/pstfilt.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/pvgsmamrdecoder.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/qgain475_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/sp_dec.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/dec/wmf_to_ets.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/amrencode.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/autocorr.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c1035pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c2_11pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c2_9pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c3_14pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c4_17pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/c8_31pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/calc_cor.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/calc_en.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cbsearch.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cl_ltp.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cod_amr.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/convolve.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cor_h.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cor_h_x.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/cor_h_x2.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/corrwght_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/div_32.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/dtx_enc.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/enc_lag3.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/enc_lag6.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/enc_output_format_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/ets_to_if2.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/ets_to_wmf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/g_adapt.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/g_code.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/g_pitch.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/gain_q.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/gsmamr_encoder_wrapper.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/hp_max.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/inter_36.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/inter_36_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/l_abs.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/l_comp.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/l_extract.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/l_negate.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/lag_wind.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/lag_wind_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/levinson.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/lflg_upd.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/lpc.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/ol_ltp.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/p_ol_wgh.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/pitch_fr.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/pitch_ol.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/pre_big.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/pre_proc.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/prm2bits.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/q_gain_c.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/q_gain_p.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/qgain475.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/qgain795.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/qua_gain.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/s10_8pf.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/set_sign.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/sid_sync.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/sp_enc.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/spreproc.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/spstproc.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/ton_stab.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/enc/vad1.cpp \
    $$PWD/DependLibs/libopencore-amr/amrnb/wrapper_amrnb.cpp \
    $$PWD/DependLibs/libopencore-amr/amrwb/wrapper_amrwb.cpp \
    $$PWD/DependLibs/libopencore-amr/src/agc2_amr_wb.cpp \
    $$PWD/DependLibs/libopencore-amr/src/band_pass_6k_7k.cpp \
    $$PWD/DependLibs/libopencore-amr/src/dec_acelp_2p_in_64.cpp \
    $$PWD/DependLibs/libopencore-amr/src/dec_acelp_4p_in_64.cpp \
    $$PWD/DependLibs/libopencore-amr/src/dec_alg_codebook.cpp \
    $$PWD/DependLibs/libopencore-amr/src/dec_gain2_amr_wb.cpp \
    $$PWD/DependLibs/libopencore-amr/src/deemphasis_32.cpp \
    $$PWD/DependLibs/libopencore-amr/src/dtx_decoder_amr_wb.cpp \
    $$PWD/DependLibs/libopencore-amr/src/get_amr_wb_bits.cpp \
    $$PWD/DependLibs/libopencore-amr/src/highpass_400hz_at_12k8.cpp \
    $$PWD/DependLibs/libopencore-amr/src/highpass_50hz_at_12k8.cpp \
    $$PWD/DependLibs/libopencore-amr/src/homing_amr_wb_dec.cpp \
    $$PWD/DependLibs/libopencore-amr/src/interpolate_isp.cpp \
    $$PWD/DependLibs/libopencore-amr/src/isf_extrapolation.cpp \
    $$PWD/DependLibs/libopencore-amr/src/isp_az.cpp \
    $$PWD/DependLibs/libopencore-amr/src/isp_isf.cpp \
    $$PWD/DependLibs/libopencore-amr/src/lagconceal.cpp \
    $$PWD/DependLibs/libopencore-amr/src/low_pass_filt_7k.cpp \
    $$PWD/DependLibs/libopencore-amr/src/median5.cpp \
    $$PWD/DependLibs/libopencore-amr/src/mime_io.cpp \
    $$PWD/DependLibs/libopencore-amr/src/noise_gen_amrwb.cpp \
    $$PWD/DependLibs/libopencore-amr/src/normalize_amr_wb.cpp \
    $$PWD/DependLibs/libopencore-amr/src/oversamp_12k8_to_16k.cpp \
    $$PWD/DependLibs/libopencore-amr/src/phase_dispersion.cpp \
    $$PWD/DependLibs/libopencore-amr/src/pit_shrp.cpp \
    $$PWD/DependLibs/libopencore-amr/src/pred_lt4.cpp \
    $$PWD/DependLibs/libopencore-amr/src/preemph_amrwb_dec.cpp \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwb_math_op.cpp \
    $$PWD/DependLibs/libopencore-amr/src/pvamrwbdecoder.cpp \
    $$PWD/DependLibs/libopencore-amr/src/q_gain2_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/src/qisf_ns.cpp \
    $$PWD/DependLibs/libopencore-amr/src/qisf_ns_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/src/qpisf_2s.cpp \
    $$PWD/DependLibs/libopencore-amr/src/qpisf_2s_tab.cpp \
    $$PWD/DependLibs/libopencore-amr/src/scale_signal.cpp \
    $$PWD/DependLibs/libopencore-amr/src/synthesis_amr_wb.cpp \
    $$PWD/DependLibs/libopencore-amr/src/voice_factor.cpp \
    $$PWD/DependLibs/libopencore-amr/src/wb_syn_filt.cpp \
    $$PWD/DependLibs/libopencore-amr/src/weight_amrwb_lpc.cpp



