
    INCLUDEPATH += $$PWD/DependLibs/openssl-1.0.2p
    INCLUDEPATH += $$PWD/DependLibs/openssl-1.0.2p/include

win32{
    INCLUDEPATH += $$PWD/sysheaders
}

unix{
    INCLUDEPATH += $$PWD/DependLibs/openssl-1.0.2p
    INCLUDEPATH += $$PWD/DependLibs/openssl-1.0.2p/include
}

INCLUDEPATH += $$PWD/GoTvCore/xbmc/xbmc/
INCLUDEPATH += $$PWD/DependLibs/



HEADERS += 	$$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvInterface/IDefs.h \
    $$PWD/GoTvInterface/IFromGui.h \
    $$PWD/GoTvInterface/IGoTv.h \
    $$PWD/GoTvInterface/IGoTvDefs.h \
    $$PWD/GoTvInterface/ILog.h \
    $$PWD/GoTvInterface/IScan.h \
    $$PWD/GoTvInterface/IToGui.h \
    $$PWD/GoTvInterface/config_libgotvptop.h \
    $$PWD/GoTvTargetOsConfig.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetCallbackInterface.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetInfo.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetInfoDb.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetMgr.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetMgrBase.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetRxSession.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetTxSession.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetXferDb.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetXferMgr.h \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetXferSession.h \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigList.h \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigListDb.h \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigListInfo.h \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigListLib.h \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigListMgr.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/WebRtcTypeDefs.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_common.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_core.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_core_internal.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_logging.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_logging_file_handling.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_rdft.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_resampler.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/array_view.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/arraysize.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/atomic32.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/atomicops.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_device.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_device_buffer.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_device_config.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_device_defines.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_device_generic.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_processing.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_util.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/base64.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/basictypes.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/block_mean_calculator.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/byteorder.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/checks.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/common_types.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/constructormagic.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/cpu_features_wrapper.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/critical_section_wrapper.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/criticalsection.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/delay_estimator.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/delay_estimator_internal.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/delay_estimator_wrapper.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/echo_cancellation.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/echo_cancellation_internal.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/echo_common.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/event.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/event_timer_posix.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/event_timer_win.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/event_wrapper.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/fake_audio_device.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/fileutils.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/fine_audio_buffer.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/format_macros.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/logging.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/module.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/module_common_types.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/pathutils.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/platform_file.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/platform_thread.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/platform_thread_types.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/random.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/real_fft.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/ring_buffer.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/safe_conversions.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/safe_conversions_impl.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/scoped_ptr.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/scoped_ref_ptr.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/scopedptrcollection.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/sec_buffer.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/signal_processing_library.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/spl_inl.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/spl_inl_armv7.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/spl_inl_mips.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/stringencode.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/stringutils.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/template_util.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/thread_annotations.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/thread_checker.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/thread_checker_impl.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/tick_util.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/timeutils.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/urlencode.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/wav_file.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/wav_header.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/win32.h \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/win32filesystem.h \
    $$PWD/GoTvCore/GoTvP2P/Groups/GroupDefs.h \
	$$PWD/GoTvCore/GoTvP2P/HostConnect/HostConnectInfo.h \
	$$PWD/GoTvCore/GoTvP2P/HostConnect/HostConnectInterface.h \
    $$PWD/GoTvCore/GoTvP2P/HostConnect/HostConnectMgr.h \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListCallbackInterface.h \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListInfo.h \
    $$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListInfoDb.h \
    $$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListMgr.h \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListMgrBase.h \
    $$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListRxSession.h \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListTxSession.h \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListXferDb.h \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListXferMger.h \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListXferSession.h \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostDb.h \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostDefs.h \
	$$PWD/GoTvCore/GoTvP2P/HostMgr/HostInfoBase.h \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostList.h \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostListEntry.h \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostSettingBase.h \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostTest.h \
	$$PWD/GoTvCore/GoTvP2P/HostMgr/OtherHostInfo.h \
	$$PWD/GoTvCore/GoTvP2P/HostMgr/OtherHostSrvMgr.h \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/RandomConnectEntry.h \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/AudioUtil.h \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/EchoCancel.h \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/MediaClient.h \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/MediaProcessor.h \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/RawAudio.h \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/RawVideo.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionAnnounce.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionBase.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionIdle.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionIsMyPortOpen.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionRandomConnect.h \
	$$PWD/GoTvCore/GoTvP2P/NetServices/NetActionQueryHostOnlineId.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionQueryMyIp.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServiceHost.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServiceDefs.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServiceHdr.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServiceUtils.h \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServicesMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Network/ConnectRequest.h \
    $$PWD/GoTvCore/GoTvP2P/Network/DirectConnectTester.h \
    $$PWD/GoTvCore/GoTvP2P/Network/Firewall.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetConnector.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetPortForward.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkDefs.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkEventAvail.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkEventBase.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkEventLost.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateAnnounce.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateAvail.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateBase.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateGetRelayList.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateLost.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateMachine.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateOnlineDirect.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateOnlineThroughRelay.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateRelaySearch.h \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateTestConnection.h \
    $$PWD/GoTvCore/GoTvP2P/Network/RcMulticastBase.h \
    $$PWD/GoTvCore/GoTvP2P/Network/RcMulticastBroadcast.h \
    $$PWD/GoTvCore/GoTvP2P/Network/RcMulticastListen.h \
    $$PWD/GoTvCore/GoTvP2P/NetworkMonitor/NetworkMonitor.h \
    $$PWD/GoTvCore/GoTvP2P/NetworkMonitor/NetStatusAccum.h \
	$$PWD/GoTvCore/GoTvP2P/NetworkTest/IsPortOpenTest.h \
    $$PWD/GoTvCore/GoTvP2P/NetworkTest/NetworkTestBase.h \
    $$PWD/GoTvCore/GoTvP2P/NetworkTest/PingResponseServer.h \
	$$PWD/GoTvCore/GoTvP2P/NetworkTest/QueryHostIdTest.h \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/BrowserHttpConnection.h \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/ContactList.h \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/EngineParams.h \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/EngineSettings.h \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/EngineSettingsDefaultValues.h \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/FileShareSettings.h \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PConnectList.h \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngine.h \
    $$PWD/GoTvCore/GoTvP2P/PluginSettings/PluginSetting.h \
    $$PWD/GoTvCore/GoTvP2P/PluginSettings/PluginSettingBinary.h \
    $$PWD/GoTvCore/GoTvP2P/PluginSettings/PluginSettingDb.h \
    $$PWD/GoTvCore/GoTvP2P/PluginSettings/PluginSettingMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/AudioJitterBuffer.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileLibraryDb.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileLibraryMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileRxSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileShareXferMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileShareXferSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileToXfer.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileTxSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileXferBaseMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileXferMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileXferPluginSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/LibraryFileInfo.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/P2PSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBase.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseClient.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseFileXfer.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseHostService.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseRelay.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseService.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseWebServer.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginClientConnectionTest.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginFileXfer.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginInvalid.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginMessenger.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginNetServices.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceAboutMe.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceAvatarImage.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceChatRoom.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceConnectionTest.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceFileShare.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceHostGroup.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceHostGroupListing.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceHostNetwork.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceRandomConnect.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceRandomConnectRelay.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceRelay.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceStoryboard.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceWebCam.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginSessionBase.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginSessionMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginTruthOrDare.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginVideoPhone.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginVoicePhone.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RcWebProxy.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/Relay.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RelayClientSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RelayClientTestSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RelayServerSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RelayServerTestSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RelaySession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RxSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SessionMgrBase.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SharedFileInfo.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SharedFilesDb.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SharedFilesFinder.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SharedFilesMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/TodGameSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/TxSession.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/VideoFeedMgr.h \
    $$PWD/GoTvCore/GoTvP2P/Plugins/VoiceFeedMgr.h \
	$$PWD/GoTvCore/GoTvP2P/QueryHostIdTest/QueryHostIdTest.h \
    $$PWD/GoTvCore/GoTvP2P/Search/RcScan.h \
    $$PWD/GoTvCore/GoTvP2P/Search/RcScanAction.h \
    $$PWD/GoTvCore/GoTvP2P/Search/RcScanMatchedConnection.h \
    $$PWD/GoTvCore/GoTvP2P/Search/RcScanPic.h \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebPageBuilder.h \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebPageSettings.h \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebServer.h \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebServerLib.h \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebSkt.h


SOURCES += \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetInfo.cpp \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetInfoDb.cpp \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetMgrBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetRxSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetTxSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetXferDb.cpp \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetXferMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/AssetMgr/AssetXferSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigList.cpp \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigListDb.cpp \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigListInfo.cpp \
    $$PWD/GoTvCore/GoTvP2P/BigListLib/BigListMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_core.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_core_mips.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_core_neon.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_core_sse2.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_logging_file_handling.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_rdft.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_rdft_mips.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_rdft_neon.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_rdft_sse2.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/aec_resampler.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/atomic32_posix.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/atomic32_win.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_device_buffer.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_device_generic.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/audio_util.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/base64.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/block_mean_calculator.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/checks.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/common_types.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/cpu_features.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/cpu_features_android.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/cpu_features_linux.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/criticalsection.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/delay_estimator.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/delay_estimator_wrapper.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/echo_cancellation.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/event.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/event_timer_posix.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/event_timer_win.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/event_wrapper.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/fileutils.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/fine_audio_buffer.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/logging.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/pathutils.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/platform_file.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/platform_thread.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/random.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/randomization_functions.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/ring_buffer.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/stringencode.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/stringutils.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/thread_checker_impl.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/tick_util.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/timeutils.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/urlencode.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/wav_file.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/wav_header.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/win32.cpp \
    $$PWD/GoTvCore/GoTvP2P/EchoCancel/win32filesystem.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostConnect/HostConnectInfo.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostConnect/HostConnectInterface.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostConnect/HostConnectMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListInfo.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListInfoDb.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListMgr.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListMgrBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListRxSession.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListTxSession.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListXferDb.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListXferMger.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostListMgr/HostListXferSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostDb.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostMgr/HostInfoBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostList.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostListEntry.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostSettingBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/HostTest.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostMgr/OtherHostInfo.cpp \
	$$PWD/GoTvCore/GoTvP2P/HostMgr/OtherHostSrvMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/HostMgr/RandomConnectEntry.cpp \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/AudioUtil.cpp \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/EchoCancel.cpp \
    $$PWD/GoTvCore/GoTvP2P/MediaProcessor/MediaProcessor.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionAnnounce.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionIdle.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionIsMyPortOpen.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionRandomConnect.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionHostOnlineId.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetActionQueryMyIp.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServiceHost.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServiceDefs.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServiceUtils.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetServices/NetServicesMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/ConnectRequest.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/DirectConnectTester.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/Firewall.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetConnector.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetPortForward.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkEventAvail.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkEventBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkEventLost.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateAnnounce.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateAvail.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateGetRelayList.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateLost.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateMachine.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateOnlineDirect.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateOnlineThroughRelay.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateRelaySearch.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/NetworkStateTestConnection.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/RcMulticastBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/RcMulticastBroadcast.cpp \
    $$PWD/GoTvCore/GoTvP2P/Network/RcMulticastListen.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetworkMonitor/NetStatusAccum.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetworkMonitor/NetworkMonitor.cpp \
	$$PWD/GoTvCore/GoTvP2P/NetworkTest/IsPortOpenTest.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetworkTest/NetworkTestBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/NetworkTest/PingResponseServer.cpp \
	$$PWD/GoTvCore/GoTvP2P/NetworkTest/QueryHostIdTest.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/BrowserHttpConnection.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/ContactList.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/EngineParams.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/EngineSettings.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/FileShareSettings.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PConnectList.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngine.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineAssetMgrCallbacks.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineConnect.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineConnections.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineContact.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineFromGui.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineIgnoredAndHackers.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineMediaProcessorCallbacks.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEnginePktAnnChanged.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEnginePktHandlers.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineRelay.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineScan.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineSearch.cpp \
    $$PWD/GoTvCore/GoTvP2P/P2PEngine/P2PEngineSktCallback.cpp \
	$$PWD/GoTvCore/GoTvP2P/PluginSettings/PluginSetting.cpp \
	$$PWD/GoTvCore/GoTvP2P/PluginSettings/PluginSettingBinary.cpp \
	$$PWD/GoTvCore/GoTvP2P/PluginSettings/PluginSettingDb.cpp \
	$$PWD/GoTvCore/GoTvP2P/PluginSettings/PluginSettingMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/AudioJitterBuffer.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileLibraryDb.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileLibraryMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileRxSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileShareXferMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileShareXferSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileToXfer.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileTxSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileXferBaseMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileXferMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/FileXferPluginSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/LibraryFileInfo.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/P2PSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseClient.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseFileXfer.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseFileXferPktHandlers.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseHostService.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseRelay.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseRelayPktHandlers.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseRelayTests.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseService.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseWebServer.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseWebServerFiles.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginBaseWebServerPktHandlers.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginClientConnectionTest.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginFileXfer.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginInvalid.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginMgrSktApi.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginMessenger.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginNetServices.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceAboutMe.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceAvatarImage.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceChatRoom.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceConnectionTest.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceFileShare.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceHostGroup.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceHostGroupListing.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceHostNetwork.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceRandomConnect.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceRandomConnectRelay.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceRelay.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceStoryboard.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginServiceWebCam.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginSessionBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginSessionMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginTruthOrDare.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginVideoPhone.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/PluginVoicePhone.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RcWebProxy.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/Relay.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RelayClientSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RelayServerSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RelaySession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/RxSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SessionMgrBase.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SharedFileInfo.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SharedFilesDb.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SharedFilesFinder.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/SharedFilesMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/TodGameSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/TxSession.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/VideoFeedMgr.cpp \
    $$PWD/GoTvCore/GoTvP2P/Plugins/VoiceFeedMgr.cpp \
	$$PWD/GoTvCore/GoTvP2P/QueryHostIdTest/QueryHostIdTest.cpp \
    $$PWD/GoTvCore/GoTvP2P/Search/RcScan.cpp \
    $$PWD/GoTvCore/GoTvP2P/Search/RcScanAction.cpp \
    $$PWD/GoTvCore/GoTvP2P/Search/RcScanMatchedConnection.cpp \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebPageBuilder.cpp \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebPageSettings.cpp \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebServer.cpp \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebServerHttp.cpp \
    $$PWD/GoTvCore/GoTvP2P/WebServer/RcWebSkt.cpp

