INCLUDEPATH += $$PWD/DependLibs/libspeex

HEADERS += 	$$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/DependLibs/libspeex/_kiss_fft_guts.h \
    $$PWD/DependLibs/libspeex/arch.h \
    $$PWD/DependLibs/libspeex/cb_search.h \
    $$PWD/DependLibs/libspeex/cb_search_arm4.h \
    $$PWD/DependLibs/libspeex/cb_search_bfin.h \
    $$PWD/DependLibs/libspeex/cb_search_sse.h \
    $$PWD/DependLibs/libspeex/config_speex.h \
    $$PWD/DependLibs/libspeex/fftwrap.h \
    $$PWD/DependLibs/libspeex/filterbank.h \
    $$PWD/DependLibs/libspeex/filters.h \
    $$PWD/DependLibs/libspeex/filters_arm4.h \
    $$PWD/DependLibs/libspeex/filters_bfin.h \
    $$PWD/DependLibs/libspeex/filters_sse.h \
    $$PWD/DependLibs/libspeex/fixed_arm4.h \
    $$PWD/DependLibs/libspeex/fixed_arm5e.h \
    $$PWD/DependLibs/libspeex/fixed_bfin.h \
    $$PWD/DependLibs/libspeex/fixed_debug.h \
    $$PWD/DependLibs/libspeex/fixed_generic.h \
    $$PWD/DependLibs/libspeex/kiss_fft.h \
    $$PWD/DependLibs/libspeex/kiss_fftr.h \
    $$PWD/DependLibs/libspeex/lpc.h \
    $$PWD/DependLibs/libspeex/lpc_bfin.h \
    $$PWD/DependLibs/libspeex/lsp.h \
    $$PWD/DependLibs/libspeex/lsp_bfin.h \
    $$PWD/DependLibs/libspeex/ltp.h \
    $$PWD/DependLibs/libspeex/ltp_arm4.h \
    $$PWD/DependLibs/libspeex/ltp_bfin.h \
    $$PWD/DependLibs/libspeex/ltp_sse.h \
    $$PWD/DependLibs/libspeex/math_approx.h \
    $$PWD/DependLibs/libspeex/misc_bfin.h \
    $$PWD/DependLibs/libspeex/modes.h \
    $$PWD/DependLibs/libspeex/nb_celp.h \
    $$PWD/DependLibs/libspeex/os_support.h \
    $$PWD/DependLibs/libspeex/pseudofloat.h \
    $$PWD/DependLibs/libspeex/quant_lsp.h \
    $$PWD/DependLibs/libspeex/quant_lsp_bfin.h \
    $$PWD/DependLibs/libspeex/resample_sse.h \
    $$PWD/DependLibs/libspeex/sb_celp.h \
    $$PWD/DependLibs/libspeex/smallft.h \
    $$PWD/DependLibs/libspeex/speex/speex.h \
    $$PWD/DependLibs/libspeex/speex/speex_bits.h \
    $$PWD/DependLibs/libspeex/speex/speex_buffer.h \
    $$PWD/DependLibs/libspeex/speex/speex_callbacks.h \
    $$PWD/DependLibs/libspeex/speex/speex_echo.h \
    $$PWD/DependLibs/libspeex/speex/speex_header.h \
    $$PWD/DependLibs/libspeex/speex/speex_jitter.h \
    $$PWD/DependLibs/libspeex/speex/speex_preprocess.h \
    $$PWD/DependLibs/libspeex/speex/speex_resampler.h \
    $$PWD/DependLibs/libspeex/speex/speex_stereo.h \
    $$PWD/DependLibs/libspeex/speex/speex_types.h \
    $$PWD/DependLibs/libspeex/stack_alloc.h \
    $$PWD/DependLibs/libspeex/vbr.h \
    $$PWD/DependLibs/libspeex/vorbis_psy.h \
    $$PWD/DependLibs/libspeex/vq.h \
    $$PWD/DependLibs/libspeex/vq_arm4.h \
    $$PWD/DependLibs/libspeex/vq_bfin.h \
    $$PWD/DependLibs/libspeex/vq_sse.h

SOURCES += 	\
    $$PWD/DependLibs/libspeex/bits_speex.c \
    $$PWD/DependLibs/libspeex/buffer_speex.c \
    $$PWD/DependLibs/libspeex/cb_search_speex.c \
    $$PWD/DependLibs/libspeex/exc_10_16_table_speex.c \
    $$PWD/DependLibs/libspeex/exc_10_32_table_speex.c \
    $$PWD/DependLibs/libspeex/exc_20_32_table_speex.c \
    $$PWD/DependLibs/libspeex/exc_5_256_table_speex.c \
    $$PWD/DependLibs/libspeex/exc_5_64_table_speex.c \
    $$PWD/DependLibs/libspeex/exc_8_128_table_speex.c \
    $$PWD/DependLibs/libspeex/fftwrap_speex.c \
    $$PWD/DependLibs/libspeex/filterbank_speex.c \
    $$PWD/DependLibs/libspeex/filters_speex.c \
    $$PWD/DependLibs/libspeex/gain_table_speex.c \
    $$PWD/DependLibs/libspeex/gain_table_lbr_speex.c \
    $$PWD/DependLibs/libspeex/hexc_10_32_table_speex.c \
    $$PWD/DependLibs/libspeex/hexc_table_speex.c \
    $$PWD/DependLibs/libspeex/high_lsp_tables_speex.c \
    $$PWD/DependLibs/libspeex/jitter_speex.c \
    $$PWD/DependLibs/libspeex/kiss_fft_speex.c \
    $$PWD/DependLibs/libspeex/kiss_fftr_speex.c \
    $$PWD/DependLibs/libspeex/lpc_speex.c \
    $$PWD/DependLibs/libspeex/lsp_speex.c \
    $$PWD/DependLibs/libspeex/lsp_tables_nb_speex.c \
    $$PWD/DependLibs/libspeex/ltp_speex.c \
    $$PWD/DependLibs/libspeex/mdf_speex.c \
    $$PWD/DependLibs/libspeex/modes_speex.c \
    $$PWD/DependLibs/libspeex/modes_wb_speex.c \
    $$PWD/DependLibs/libspeex/nb_celp_speex.c \
    $$PWD/DependLibs/libspeex/preprocess_speex.c \
    $$PWD/DependLibs/libspeex/quant_lsp_speex.c \
    $$PWD/DependLibs/libspeex/resample_speex.c \
    $$PWD/DependLibs/libspeex/sb_celp_speex.c \
    $$PWD/DependLibs/libspeex/scal_speex.c \
    $$PWD/DependLibs/libspeex/smallft_speex.c \
    $$PWD/DependLibs/libspeex/speex_speex.c \
    $$PWD/DependLibs/libspeex/speex_callbacks_speex.c \
    $$PWD/DependLibs/libspeex/speex_header_speex.c \
    $$PWD/DependLibs/libspeex/speex_window_speex.c \
    $$PWD/DependLibs/libspeex/stereo_speex.c \
    $$PWD/DependLibs/libspeex/vbr_speex.c \
    $$PWD/DependLibs/libspeex/vq_speex.c

