DEFINES += LIBSSH_STATIC

INCLUDEPATH += $$PWD/DependLibs/libssh/

HEADERS += 	$$PWD/DependLibs/libssh/agent.h \
    $$PWD/DependLibs/libssh/auth.h \
    $$PWD/DependLibs/libssh/bignum.h \
    $$PWD/DependLibs/libssh/bind.h \
    $$PWD/DependLibs/libssh/blf.h \
    $$PWD/DependLibs/libssh/buffer.h \
    $$PWD/DependLibs/libssh/callbacks.h \
    $$PWD/DependLibs/libssh/channels.h \
    $$PWD/DependLibs/libssh/config_libssh.h \
    $$PWD/DependLibs/libssh/crc32.h \
    $$PWD/DependLibs/libssh/crypto.h \
    $$PWD/DependLibs/libssh/curve25519.h \
    $$PWD/DependLibs/libssh/dh.h \
    $$PWD/DependLibs/libssh/ecdh.h \
    $$PWD/DependLibs/libssh/ed25519.h \
    $$PWD/DependLibs/libssh/fe25519.h \
    $$PWD/DependLibs/libssh/ge25519.h \
    $$PWD/DependLibs/libssh/gssapi.h \
    $$PWD/DependLibs/libssh/kex.h \
    $$PWD/DependLibs/libssh/keys.h \
    $$PWD/DependLibs/libssh/knownhosts.h \
    $$PWD/DependLibs/libssh/legacy.h \
    $$PWD/DependLibs/libssh/libcrypto.h \
    $$PWD/DependLibs/libssh/libgcrypt.h \
    $$PWD/DependLibs/libssh/libssh.h \
    $$PWD/DependLibs/libssh/libssh_priv.h \
    $$PWD/DependLibs/libssh/libssh_string.h \
    $$PWD/DependLibs/libssh/libsshpp.hpp \
    $$PWD/DependLibs/libssh/messages.h \
    $$PWD/DependLibs/libssh/misc.h \
    $$PWD/DependLibs/libssh/options.h \
    $$PWD/DependLibs/libssh/packet.h \
    $$PWD/DependLibs/libssh/pcap.h \
    $$PWD/DependLibs/libssh/pki.h \
    $$PWD/DependLibs/libssh/pki_priv.h \
    $$PWD/DependLibs/libssh/poll_ssh.h \
    $$PWD/DependLibs/libssh/sc25519.h \
    $$PWD/DependLibs/libssh/scp.h \
    $$PWD/DependLibs/libssh/server.h \
    $$PWD/DependLibs/libssh/session.h \
    $$PWD/DependLibs/libssh/sftp.h \
    $$PWD/DependLibs/libssh/socket.h \
    $$PWD/DependLibs/libssh/ssh1.h \
    $$PWD/DependLibs/libssh/ssh2.h \
    $$PWD/DependLibs/libssh/threads.h \
    $$PWD/DependLibs/libssh/wrapper.h \
    $$PWD/DependLibs/libssh/poll_ssh.h

SOURCES += 	\
    $$PWD/DependLibs/libssh/poll_ssh.c \
    $$PWD/DependLibs/libssh/options_ssh.c \
    $$PWD/DependLibs/libssh/error_ssh.c \
    $$PWD/DependLibs/libssh/external/bcrypt_pbkdf_ssh.c \
    $$PWD/DependLibs/libssh/external/blowfish_ssh.c \
    $$PWD/DependLibs/libssh/external/curve25519_ref_ssh.c \
    $$PWD/DependLibs/libssh/external/ed25519_ssh.c \
    $$PWD/DependLibs/libssh/external/fe25519_ssh.c \
    $$PWD/DependLibs/libssh/external/ge25519_ssh.c \
    $$PWD/DependLibs/libssh/external/sc25519_ssh.c \
    $$PWD/DependLibs/libssh/threads/pthread_ssh.c \
    $$PWD/DependLibs/libssh/agent_ssh.c \
    $$PWD/DependLibs/libssh/auth_ssh.c \
    $$PWD/DependLibs/libssh/auth1_ssh.c \
    $$PWD/DependLibs/libssh/base64_ssh.c \
    $$PWD/DependLibs/libssh/bignum_ssh.c \
    $$PWD/DependLibs/libssh/bind_ssh.c \
    $$PWD/DependLibs/libssh/buffer_ssh.c \
    $$PWD/DependLibs/libssh/callbacks_ssh.c \
    $$PWD/DependLibs/libssh/channels_ssh.c \
    $$PWD/DependLibs/libssh/channels1_ssh.c \
    $$PWD/DependLibs/libssh/client_ssh.c \
    $$PWD/DependLibs/libssh/config_ssh.c \
    $$PWD/DependLibs/libssh/connect_ssh.c \
    $$PWD/DependLibs/libssh/crc32_ssh.c \
    $$PWD/DependLibs/libssh/curve25519_ssh.c \
    $$PWD/DependLibs/libssh/dh_ssh.c \
    $$PWD/DependLibs/libssh/ecdh_ssh.c \
    $$PWD/DependLibs/libssh/gcrypt_missing_ssh.c \
    $$PWD/DependLibs/libssh/getpass_ssh.c \
    $$PWD/DependLibs/libssh/gssapi_ssh.c \
    $$PWD/DependLibs/libssh/gzip_ssh.c \
    $$PWD/DependLibs/libssh/init_ssh.c \
    $$PWD/DependLibs/libssh/kex_ssh.c \
    $$PWD/DependLibs/libssh/kex1_ssh.c \
    $$PWD/DependLibs/libssh/known_hosts_ssh.c \
    $$PWD/DependLibs/libssh/legacy_ssh.c \
    $$PWD/DependLibs/libssh/libcrypto_ssh.c \
    $$PWD/DependLibs/libssh/libgcrypt_ssh.c \
    $$PWD/DependLibs/libssh/libssh_string_ssh.c \
    $$PWD/DependLibs/libssh/log_ssh.c \
    $$PWD/DependLibs/libssh/match_ssh.c \
    $$PWD/DependLibs/libssh/messages_ssh.c \
    $$PWD/DependLibs/libssh/misc_ssh.c \
    $$PWD/DependLibs/libssh/packet_ssh.c \
    $$PWD/DependLibs/libssh/packet1_ssh.c \
    $$PWD/DependLibs/libssh/packet_cb_ssh.c \
    $$PWD/DependLibs/libssh/packet_crypt_ssh.c \
    $$PWD/DependLibs/libssh/pcap_ssh.c \
    $$PWD/DependLibs/libssh/pki_ssh.c \
    $$PWD/DependLibs/libssh/pki_container_openssh_ssh.c \
    $$PWD/DependLibs/libssh/pki_crypto_ssh.c \
    $$PWD/DependLibs/libssh/pki_ed25519_ssh.c \
    $$PWD/DependLibs/libssh/pki_gcrypt_ssh.c \
    $$PWD/DependLibs/libssh/scp_ssh.c \
    $$PWD/DependLibs/libssh/server_ssh.c \
    $$PWD/DependLibs/libssh/session_ssh.c \
    $$PWD/DependLibs/libssh/sftp_ssh.c \
    $$PWD/DependLibs/libssh/sftpserver_ssh.c \
    $$PWD/DependLibs/libssh/socket_ssh.c \
    $$PWD/DependLibs/libssh/threads_ssh.c \
    $$PWD/DependLibs/libssh/wrapper_ssh.c

