
INCLUDEPATH += $$PWD/DependLibs/libtag/

HEADERS += 	$$PWD/DependLibs/libtag/ape/apefile.h \
    $$PWD/DependLibs/libtag/ape/apefooter.h \
    $$PWD/DependLibs/libtag/ape/apeitem.h \
    $$PWD/DependLibs/libtag/ape/apeproperties.h \
    $$PWD/DependLibs/libtag/ape/apetag.h \
    $$PWD/DependLibs/libtag/asf/asfattribute.h \
    $$PWD/DependLibs/libtag/asf/asffile.h \
    $$PWD/DependLibs/libtag/asf/asfpicture.h \
    $$PWD/DependLibs/libtag/asf/asfproperties.h \
    $$PWD/DependLibs/libtag/asf/asftag.h \
    $$PWD/DependLibs/libtag/asf/asfutils.h \
    $$PWD/DependLibs/libtag/audioproperties.h \
    $$PWD/DependLibs/libtag/config_libtag.h \
    $$PWD/DependLibs/libtag/fileref.h \
    $$PWD/DependLibs/libtag/flac/flacfile.h \
    $$PWD/DependLibs/libtag/flac/flacmetadatablock.h \
    $$PWD/DependLibs/libtag/flac/flacpicture.h \
    $$PWD/DependLibs/libtag/flac/flacproperties.h \
    $$PWD/DependLibs/libtag/flac/flacunknownmetadatablock.h \
    $$PWD/DependLibs/libtag/it/itfile.h \
    $$PWD/DependLibs/libtag/it/itproperties.h \
    $$PWD/DependLibs/libtag/mod/modfile.h \
    $$PWD/DependLibs/libtag/mod/modfilebase.h \
    $$PWD/DependLibs/libtag/mod/modfileprivate.h \
    $$PWD/DependLibs/libtag/mod/modproperties.h \
    $$PWD/DependLibs/libtag/mod/modtag.h \
    $$PWD/DependLibs/libtag/mp4/mp4atom.h \
    $$PWD/DependLibs/libtag/mp4/mp4coverart.h \
    $$PWD/DependLibs/libtag/mp4/mp4file.h \
    $$PWD/DependLibs/libtag/mp4/mp4item.h \
    $$PWD/DependLibs/libtag/mp4/mp4properties.h \
    $$PWD/DependLibs/libtag/mp4/mp4tag.h \
    $$PWD/DependLibs/libtag/mpc/mpcfile.h \
    $$PWD/DependLibs/libtag/mpc/mpcproperties.h \
    $$PWD/DependLibs/libtag/mpeg/id3v1/id3v1genres.h \
    $$PWD/DependLibs/libtag/mpeg/id3v1/id3v1tag.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/attachedpictureframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/chapterframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/commentsframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/eventtimingcodesframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/generalencapsulatedobjectframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/ownershipframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/podcastframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/popularimeterframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/privateframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/relativevolumeframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/synchronizedlyricsframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/tableofcontentsframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/textidentificationframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/uniquefileidentifierframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/unknownframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/unsynchronizedlyricsframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/urllinkframe.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2extendedheader.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2footer.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2frame.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2framefactory.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2header.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2synchdata.h \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2tag.h \
    $$PWD/DependLibs/libtag/mpeg/mpegfile.h \
    $$PWD/DependLibs/libtag/mpeg/mpegheader.h \
    $$PWD/DependLibs/libtag/mpeg/mpegproperties.h \
    $$PWD/DependLibs/libtag/mpeg/mpegutils.h \
    $$PWD/DependLibs/libtag/mpeg/xingheader.h \
    $$PWD/DependLibs/libtag/ogg/flac/oggflacfile.h \
    $$PWD/DependLibs/libtag/ogg/oggfile.h \
    $$PWD/DependLibs/libtag/ogg/oggpage.h \
    $$PWD/DependLibs/libtag/ogg/oggpageheader.h \
    $$PWD/DependLibs/libtag/ogg/opus/opusfile.h \
    $$PWD/DependLibs/libtag/ogg/opus/opusproperties.h \
    $$PWD/DependLibs/libtag/ogg/speex/speexfile.h \
    $$PWD/DependLibs/libtag/ogg/speex/speexproperties.h \
    $$PWD/DependLibs/libtag/ogg/vorbis/vorbisfile.h \
    $$PWD/DependLibs/libtag/ogg/vorbis/vorbisproperties.h \
    $$PWD/DependLibs/libtag/ogg/xiphcomment.h \
    $$PWD/DependLibs/libtag/riff/aiff/aifffile.h \
    $$PWD/DependLibs/libtag/riff/aiff/aiffproperties.h \
    $$PWD/DependLibs/libtag/riff/rifffile.h \
    $$PWD/DependLibs/libtag/riff/riffutils.h \
    $$PWD/DependLibs/libtag/riff/wav/infotag.h \
    $$PWD/DependLibs/libtag/riff/wav/wavfile.h \
    $$PWD/DependLibs/libtag/riff/wav/wavproperties.h \
    $$PWD/DependLibs/libtag/s3m/s3mfile.h \
    $$PWD/DependLibs/libtag/s3m/s3mproperties.h \
    $$PWD/DependLibs/libtag/tag.h \
    $$PWD/DependLibs/libtag/taglib.h \
    $$PWD/DependLibs/libtag/taglib_export.h \
    $$PWD/DependLibs/libtag/tagunion.h \
    $$PWD/DependLibs/libtag/tagutils.h \
    $$PWD/DependLibs/libtag/toolkit/tbytevector.h \
    $$PWD/DependLibs/libtag/toolkit/tbytevectorlist.h \
    $$PWD/DependLibs/libtag/toolkit/tbytevectorstream.h \
    $$PWD/DependLibs/libtag/toolkit/tdebug.h \
    $$PWD/DependLibs/libtag/toolkit/tdebuglistener.h \
    $$PWD/DependLibs/libtag/toolkit/tfile.h \
    $$PWD/DependLibs/libtag/toolkit/tfilestream.h \
    $$PWD/DependLibs/libtag/toolkit/tiostream.h \
    $$PWD/DependLibs/libtag/toolkit/tlist.h \
    $$PWD/DependLibs/libtag/toolkit/tmap.h \
    $$PWD/DependLibs/libtag/toolkit/tpropertymap.h \
    $$PWD/DependLibs/libtag/toolkit/trefcounter.h \
    $$PWD/DependLibs/libtag/toolkit/tstring.h \
    $$PWD/DependLibs/libtag/toolkit/tstringlist.h \
    $$PWD/DependLibs/libtag/toolkit/tutils.h \
    $$PWD/DependLibs/libtag/toolkit/tzlib.h \
    $$PWD/DependLibs/libtag/toolkit/unicode.h \
    $$PWD/DependLibs/libtag/trueaudio/trueaudiofile.h \
    $$PWD/DependLibs/libtag/trueaudio/trueaudioproperties.h \
    $$PWD/DependLibs/libtag/wavpack/wavpackfile.h \
    $$PWD/DependLibs/libtag/wavpack/wavpackproperties.h \
    $$PWD/DependLibs/libtag/xm/xmfile.h \
    $$PWD/DependLibs/libtag/xm/xmproperties.h

SOURCES += 	$$PWD/DependLibs/libtag/ape/apefile.cpp \
    $$PWD/DependLibs/libtag/ape/apefooter.cpp \
    $$PWD/DependLibs/libtag/ape/apeitem.cpp \
    $$PWD/DependLibs/libtag/ape/apeproperties.cpp \
    $$PWD/DependLibs/libtag/ape/apetag.cpp \
    $$PWD/DependLibs/libtag/asf/asfattribute.cpp \
    $$PWD/DependLibs/libtag/asf/asffile.cpp \
    $$PWD/DependLibs/libtag/asf/asfpicture.cpp \
    $$PWD/DependLibs/libtag/asf/asfproperties.cpp \
    $$PWD/DependLibs/libtag/asf/asftag.cpp \
    $$PWD/DependLibs/libtag/audioproperties.cpp \
    $$PWD/DependLibs/libtag/fileref.cpp \
    $$PWD/DependLibs/libtag/flac/flacfile.cpp \
    $$PWD/DependLibs/libtag/flac/flacmetadatablock.cpp \
    $$PWD/DependLibs/libtag/flac/flacpicture.cpp \
    $$PWD/DependLibs/libtag/flac/flacproperties.cpp \
    $$PWD/DependLibs/libtag/flac/flacunknownmetadatablock.cpp \
    $$PWD/DependLibs/libtag/it/itfile.cpp \
    $$PWD/DependLibs/libtag/it/itproperties.cpp \
    $$PWD/DependLibs/libtag/mod/modfile.cpp \
    $$PWD/DependLibs/libtag/mod/modfilebase.cpp \
    $$PWD/DependLibs/libtag/mod/modproperties.cpp \
    $$PWD/DependLibs/libtag/mod/modtag.cpp \
    $$PWD/DependLibs/libtag/mp4/mp4atom.cpp \
    $$PWD/DependLibs/libtag/mp4/mp4coverart.cpp \
    $$PWD/DependLibs/libtag/mp4/mp4file.cpp \
    $$PWD/DependLibs/libtag/mp4/mp4item.cpp \
    $$PWD/DependLibs/libtag/mp4/mp4properties.cpp \
    $$PWD/DependLibs/libtag/mp4/mp4tag.cpp \
    $$PWD/DependLibs/libtag/mpc/mpcfile.cpp \
    $$PWD/DependLibs/libtag/mpc/mpcproperties.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v1/id3v1genres.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v1/id3v1tag.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/attachedpictureframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/chapterframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/commentsframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/eventtimingcodesframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/generalencapsulatedobjectframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/ownershipframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/podcastframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/popularimeterframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/privateframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/relativevolumeframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/synchronizedlyricsframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/tableofcontentsframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/textidentificationframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/uniquefileidentifierframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/unknownframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/unsynchronizedlyricsframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/frames/urllinkframe.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2extendedheader.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2footer.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2frame.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2framefactory.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2header.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2synchdata.cpp \
    $$PWD/DependLibs/libtag/mpeg/id3v2/id3v2tag.cpp \
    $$PWD/DependLibs/libtag/mpeg/mpegfile.cpp \
    $$PWD/DependLibs/libtag/mpeg/mpegheader.cpp \
    $$PWD/DependLibs/libtag/mpeg/mpegproperties.cpp \
    $$PWD/DependLibs/libtag/mpeg/xingheader.cpp \
    $$PWD/DependLibs/libtag/ogg/flac/oggflacfile.cpp \
    $$PWD/DependLibs/libtag/ogg/oggfile.cpp \
    $$PWD/DependLibs/libtag/ogg/oggpage.cpp \
    $$PWD/DependLibs/libtag/ogg/oggpageheader.cpp \
    $$PWD/DependLibs/libtag/ogg/opus/opusfile.cpp \
    $$PWD/DependLibs/libtag/ogg/opus/opusproperties.cpp \
    $$PWD/DependLibs/libtag/ogg/speex/speexfile.cpp \
    $$PWD/DependLibs/libtag/ogg/speex/speexproperties.cpp \
    $$PWD/DependLibs/libtag/ogg/vorbis/vorbisfile.cpp \
    $$PWD/DependLibs/libtag/ogg/vorbis/vorbisproperties.cpp \
    $$PWD/DependLibs/libtag/ogg/xiphcomment.cpp \
    $$PWD/DependLibs/libtag/riff/aiff/aifffile.cpp \
    $$PWD/DependLibs/libtag/riff/aiff/aiffproperties.cpp \
    $$PWD/DependLibs/libtag/riff/rifffile.cpp \
    $$PWD/DependLibs/libtag/riff/wav/infotag.cpp \
    $$PWD/DependLibs/libtag/riff/wav/wavfile.cpp \
    $$PWD/DependLibs/libtag/riff/wav/wavproperties.cpp \
    $$PWD/DependLibs/libtag/s3m/s3mfile.cpp \
    $$PWD/DependLibs/libtag/s3m/s3mproperties.cpp \
    $$PWD/DependLibs/libtag/tag.cpp \
    $$PWD/DependLibs/libtag/tagunion.cpp \
    $$PWD/DependLibs/libtag/tagutils.cpp \
    $$PWD/DependLibs/libtag/toolkit/tbytevector.cpp \
    $$PWD/DependLibs/libtag/toolkit/tbytevectorlist.cpp \
    $$PWD/DependLibs/libtag/toolkit/tbytevectorstream.cpp \
    $$PWD/DependLibs/libtag/toolkit/tdebug.cpp \
    $$PWD/DependLibs/libtag/toolkit/tdebuglistener.cpp \
    $$PWD/DependLibs/libtag/toolkit/tfile.cpp \
    $$PWD/DependLibs/libtag/toolkit/tfilestream.cpp \
    $$PWD/DependLibs/libtag/toolkit/tiostream.cpp \
    $$PWD/DependLibs/libtag/toolkit/tpropertymap.cpp \
    $$PWD/DependLibs/libtag/toolkit/trefcounter.cpp \
    $$PWD/DependLibs/libtag/toolkit/tstring.cpp \
    $$PWD/DependLibs/libtag/toolkit/tstringlist.cpp \
    $$PWD/DependLibs/libtag/toolkit/tzlib.cpp \
    $$PWD/DependLibs/libtag/toolkit/unicode.cpp \
    $$PWD/DependLibs/libtag/trueaudio/trueaudiofile.cpp \
    $$PWD/DependLibs/libtag/trueaudio/trueaudioproperties.cpp \
    $$PWD/DependLibs/libtag/wavpack/wavpackfile.cpp \
    $$PWD/DependLibs/libtag/wavpack/wavpackproperties.cpp \
    $$PWD/DependLibs/libtag/xm/xmfile.cpp \
    $$PWD/DependLibs/libtag/xm/xmproperties.cpp

