
QMAKE_CXXFLAGS += -mmmx
QMAKE_CXXFLAGS += -msse2
QMAKE_CXXFLAGS += -msse3
QMAKE_CXXFLAGS += -msse4.1
QMAKE_CXXFLAGS += -mavx
QMAKE_CXXFLAGS += -mavx2

QMAKE_CFLAGS += -mmmx
QMAKE_CFLAGS += -msse2
QMAKE_CFLAGS += -msse3
QMAKE_CFLAGS += -msse4.1
QMAKE_CFLAGS += -mavx
QMAKE_CFLAGS += -mavx2

INCLUDEPATH += $$PWD/DependLibs/libvpx/

INCLUDEPATH += $$PWD/DependLibs/libvpx/
INCLUDEPATH += $$PWD/DependLibs/libvpx/vpx
INCLUDEPATH += $$PWD/DependLibs/libvpx/vpx_dsp

HEADERS += 	$$PWD/GoTvAppConfig.h \
    $$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvTargetOsConfig.h \
    $$PWD/DependLibs/libvpx/vp8/common/alloccommon.h \
    $$PWD/DependLibs/libvpx/vp8/common/blockd.h \
    $$PWD/DependLibs/libvpx/vp8/common/coefupdateprobs.h \
    $$PWD/DependLibs/libvpx/vp8/common/common.h \
    $$PWD/DependLibs/libvpx/vp8/common/default_coef_probs.h \
    $$PWD/DependLibs/libvpx/vp8/common/entropy.h \
    $$PWD/DependLibs/libvpx/vp8/common/entropymode.h \
    $$PWD/DependLibs/libvpx/vp8/common/entropymv.h \
    $$PWD/DependLibs/libvpx/vp8/common/extend.h \
    $$PWD/DependLibs/libvpx/vp8/common/filter.h \
    $$PWD/DependLibs/libvpx/vp8/common/findnearmv.h \
    $$PWD/DependLibs/libvpx/vp8/common/header.h \
    $$PWD/DependLibs/libvpx/vp8/common/invtrans.h \
    $$PWD/DependLibs/libvpx/vp8/common/loopfilter.h \
    $$PWD/DependLibs/libvpx/vp8/common/modecont.h \
    $$PWD/DependLibs/libvpx/vp8/common/mv.h \
    $$PWD/DependLibs/libvpx/vp8/common/onyx.h \
    $$PWD/DependLibs/libvpx/vp8/common/onyxc_int.h \
    $$PWD/DependLibs/libvpx/vp8/common/onyxd.h \
    $$PWD/DependLibs/libvpx/vp8/common/postproc.h \
    $$PWD/DependLibs/libvpx/vp8/common/ppflags.h \
    $$PWD/DependLibs/libvpx/vp8/common/quant_common.h \
    $$PWD/DependLibs/libvpx/vp8/common/reconinter.h \
    $$PWD/DependLibs/libvpx/vp8/common/reconintra.h \
    $$PWD/DependLibs/libvpx/vp8/common/reconintra4x4.h \
    $$PWD/DependLibs/libvpx/vp8/common/setupintrarecon.h \
    $$PWD/DependLibs/libvpx/vp8/common/swapyv12buffer.h \
    $$PWD/DependLibs/libvpx/vp8/common/systemdependent.h \
    $$PWD/DependLibs/libvpx/vp8/common/threading.h \
    $$PWD/DependLibs/libvpx/vp8/common/treecoder.h \
    $$PWD/DependLibs/libvpx/vp8/common/vp8_entropymodedata.h \
    $$PWD/DependLibs/libvpx/vp8/common/vp8_skin_detection.h \
    $$PWD/DependLibs/libvpx/vp8/common/x86/filter_x86.h \
    $$PWD/DependLibs/libvpx/vp8/decoder/dboolhuff.h \
    $$PWD/DependLibs/libvpx/vp8/decoder/decodemv.h \
    $$PWD/DependLibs/libvpx/vp8/decoder/decoderthreading.h \
    $$PWD/DependLibs/libvpx/vp8/decoder/detokenize.h \
    $$PWD/DependLibs/libvpx/vp8/decoder/onyxd_int.h \
    $$PWD/DependLibs/libvpx/vp8/decoder/treereader.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/bitstream.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/block.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/boolhuff.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/dct_value_cost.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/dct_value_tokens.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/defaultcoefcounts.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/denoising.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/encodeframe.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/encodeintra.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/encodemb.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/encodemv.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/ethreading.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/firstpass.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/lookahead.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/mcomp.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/modecosts.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/onyx_int.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/pickinter.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/picklpf.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/quantize.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/ratectrl.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/rdopt.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/segmentation.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/temporal_filter.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/tokenize.h \
    $$PWD/DependLibs/libvpx/vp8/encoder/treewriter.h \
    $$PWD/DependLibs/libvpx/vp8_rtcd.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_alloccommon.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_blockd.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_common.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_common_data.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_entropy.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_entropymode.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_entropymv.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_enums.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_filter.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_frame_buffers.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_idct.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_loopfilter.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_mv.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_mvref_common.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_onyxc_int.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_ppflags.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_pred_common.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_quant_common.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_reconinter.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_reconintra.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_scale.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_scan.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_seg_common.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_thread_common.h \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_tile_common.h \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_decodeframe.h \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_decodemv.h \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_decoder.h \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_detokenize.h \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_dsubexp.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_alt_ref_aq.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_aq_360.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_aq_complexity.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_aq_cyclicrefresh.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_aq_variance.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_bitstream.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_block.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_context_tree.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_cost.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_encodeframe.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_encodemb.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_encodemv.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_encoder.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_ethread.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_extend.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_firstpass.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_job_queue.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_lookahead.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_mbgraph.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_mcomp.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_multi_thread.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_noise_estimate.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_picklpf.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_pickmode.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_quantize.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_ratectrl.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_rd.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_rdopt.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_resize.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_segmentation.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_skin_detection.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_speed_features.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_subexp.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_svc_layercontext.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_temporal_filter.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_tokenize.h \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_treewriter.h \
    $$PWD/DependLibs/libvpx/vp9/vp9_dx_iface.h \
    $$PWD/DependLibs/libvpx/vp9/vp9_iface_common.h \
    $$PWD/DependLibs/libvpx/vp9_rtcd.h \
    $$PWD/DependLibs/libvpx/vpx/internal/vpx_codec_internal.h \
    $$PWD/DependLibs/libvpx/vpx/vp8.h \
    $$PWD/DependLibs/libvpx/vpx/vp8cx.h \
    $$PWD/DependLibs/libvpx/vpx/vp8dx.h \
    $$PWD/DependLibs/libvpx/vpx/vpx_codec.h \
    $$PWD/DependLibs/libvpx/vpx/vpx_decoder.h \
    $$PWD/DependLibs/libvpx/vpx/vpx_encoder.h \
    $$PWD/DependLibs/libvpx/vpx/vpx_frame_buffer.h \
    $$PWD/DependLibs/libvpx/vpx/vpx_image.h \
    $$PWD/DependLibs/libvpx/vpx/vpx_integer.h \
    $$PWD/DependLibs/libvpx/vpx_config.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/bitreader.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/bitreader_buffer.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/bitwriter.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/bitwriter_buffer.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/fwd_txfm.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/inv_txfm.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/postproc.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/prob.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/psnr.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/quantize.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/skin_detection.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/txfm_common.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/variance.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/vpx_convolve.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/vpx_dsp_common.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/vpx_filter.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/bitdepth_conversion_avx2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/bitdepth_conversion_sse2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/convolve.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/fwd_dct32x32_impl_avx2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/fwd_dct32x32_impl_sse2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/fwd_txfm_impl_sse2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/fwd_txfm_sse2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/inv_txfm_sse2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/inv_txfm_ssse3.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/transpose_sse2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/txfm_common_sse2.h \
    $$PWD/DependLibs/libvpx/vpx_dsp_rtcd.h \
    $$PWD/DependLibs/libvpx/vpx_mem/include/vpx_mem_intrnl.h \
    $$PWD/DependLibs/libvpx/vpx_mem/vpx_mem.h \
    $$PWD/DependLibs/libvpx/vpx_ports/bitops.h \
    $$PWD/DependLibs/libvpx/vpx_ports/emmintrin_compat.h \
    $$PWD/DependLibs/libvpx/vpx_ports/mem.h \
    $$PWD/DependLibs/libvpx/vpx_ports/mem_ops.h \
    $$PWD/DependLibs/libvpx/vpx_ports/mem_ops_aligned.h \
    $$PWD/DependLibs/libvpx/vpx_ports/msvc.h \
    $$PWD/DependLibs/libvpx/vpx_ports/system_state.h \
    $$PWD/DependLibs/libvpx/vpx_ports/vpx_once.h \
    $$PWD/DependLibs/libvpx/vpx_ports/vpx_timer.h \
    $$PWD/DependLibs/libvpx/vpx_ports/x86.h \
    $$PWD/DependLibs/libvpx/vpx_scale/vpx_scale.h \
    $$PWD/DependLibs/libvpx/vpx_scale/yv12config.h \
    $$PWD/DependLibs/libvpx/vpx_scale_rtcd.h \
    $$PWD/DependLibs/libvpx/vpx_util/endian_inl.h \
    $$PWD/DependLibs/libvpx/vpx_util/vpx_atomics.h \
    $$PWD/DependLibs/libvpx/vpx_util/vpx_thread.h \
    $$PWD/DependLibs/libvpx/vpx_util/vpx_write_yuv_frame.h \
    $$PWD/DependLibs/libvpx/config_libvpx.h \
    $$PWD/DependLibs/libvpx/vpx_config.h \
    $$PWD/DependLibs/libvpx/vpx_config_linux.h \
    $$PWD/DependLibs/libvpx/vpx_dsp_rtcd.h \
    $$PWD/DependLibs/libvpx/vpx_dsp_rtcd_linux.h \
    $$PWD/DependLibs/libvpx/vpx_dsp_rtcd_win.h \
    $$PWD/DependLibs/libvpx/vpx_scale_rtcd.h \
    $$PWD/DependLibs/libvpx/vpx_scale_rtcd_linux.h \
    $$PWD/DependLibs/libvpx/vpx_scale_rtcd_win.h

SOURCES += 	\
    $$PWD/DependLibs/libvpx/vp8/common/vp8_loopfilter.c \
    $$PWD/DependLibs/libvpx/vp8/common/vp8_skin_detection.c \
    $$PWD/DependLibs/libvpx/vp8/common/x86/vp8_asm_stubs.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/vp8_quantize.c \
    $$PWD/DependLibs/libvpx/vp8/vp8_cx_iface.c \
    $$PWD/DependLibs/libvpx/vp8/vp8_dx_iface.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_alloccommon.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_blockd.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_common_data.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_entropy.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_entropymode.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_entropymv.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_filter.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_frame_buffers.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_idct.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_loopfilter.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_mvref_common.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_pred_common.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_quant_common.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_reconinter.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_reconintra.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_rtcd.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_scale.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_scan.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_seg_common.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_thread_common.c \
    $$PWD/DependLibs/libvpx/vp9/common/vp9_tile_common.c \
    $$PWD/DependLibs/libvpx/vp9/common/x86/vp9_idct_intrin_sse2.c \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_decodeframe.c \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_decodemv.c \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_decoder.c \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_detokenize.c \
    $$PWD/DependLibs/libvpx/vp9/decoder/vp9_dsubexp.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_alt_ref_aq.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_aq_360.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_aq_complexity.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_aq_cyclicrefresh.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_aq_variance.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_bitstream.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_context_tree.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_cost.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_dct.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_encodeframe.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_encodemb.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_encodemv.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_encoder.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_ethread.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_extend.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_firstpass.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_frame_scale.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_lookahead.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_mbgraph.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_mcomp.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_multi_thread.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_noise_estimate.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_picklpf.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_pickmode.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_quantize.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_ratectrl.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_rd.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_rdopt.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_resize.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_segmentation.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_skin_detection.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_speed_features.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_subexp.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_svc_layercontext.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_temporal_filter.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_tokenize.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/vp9_treewriter.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/x86/vp9_dct_intrin_sse2.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/x86/vp9_dct_ssse3.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/x86/vp9_diamond_search_sad_avx.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/x86/vp9_error_avx2.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/x86/vp9_frame_scale_ssse3.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/x86/vp9_quantize_sse2.c \
    $$PWD/DependLibs/libvpx/vp9/vp9_cx_iface.c \
    $$PWD/DependLibs/libvpx/vp9/vp9_dx_iface.c \
    $$PWD/DependLibs/libvpx/vpx/src/vpx_codec.c \
    $$PWD/DependLibs/libvpx/vpx/src/vpx_decoder.c \
    $$PWD/DependLibs/libvpx/vpx/src/vpx_encoder.c \
    $$PWD/DependLibs/libvpx/vpx/src/vpx_image.c \
    $$PWD/DependLibs/libvpx/vpx_config.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/vpx_convolve.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/vpx_dsp_rtcd.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/vpx_asm_stubs.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/vpx_subpixel_8t_intrin_avx2.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/vpx_subpixel_8t_intrin_ssse3.c \
    $$PWD/DependLibs/libvpx/vpx_mem/vpx_mem.c \
    $$PWD/DependLibs/libvpx/vpx_scale/generic/vpx_scale.c \
    $$PWD/DependLibs/libvpx/vpx_scale/vpx_scale_rtcd.c \
    $$PWD/DependLibs/libvpx/vpx_util/vpx_thread.c \
    $$PWD/DependLibs/libvpx/vpx_util/vpx_write_yuv_frame.c \
    $$PWD/DependLibs/libvpx/vp8/common/arm/loopfilter_arm_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/generic/systemdependent_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/x86/filter_x86_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/x86/idct_blk_mmx_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/x86/idct_blk_sse2_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/x86/loopfilter_x86_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/alloccommon_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/blockd_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/copy_c_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/dequantize_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/entropy_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/entropymode_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/entropymv_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/extend_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/filter_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/findnearmv_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/idct_blk_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/idctllm_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/loopfilter_filters_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/mbpitch_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/mfqe_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/modecont_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/postproc_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/quant_common_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/reconinter_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/reconintra_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/rtcd_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/reconintra4x4_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/setupintrarecon_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/swapyv12buffer_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/common/treecoder_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/decoder/dboolhuff_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/decoder/decodeframe_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/decoder/decodemv_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/decoder/detokenize_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/decoder/onyxd_if_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/decoder/threading_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/x86/denoising_sse2_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/x86/quantize_sse4_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/x86/vp8_enc_stubs_sse2_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/x86/vp8_quantize_sse2_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/x86/vp8_quantize_ssse3_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/bitstream_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/boolhuff_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/dct_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/denoising_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/encodeframe_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/encodeintra_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/encodemb_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/encodemv_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/ethreading_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/firstpass_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/lookahead_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/mcomp_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/modecosts_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/onyx_if_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/pickinter_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/picklpf_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/ratectrl_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/rdopt_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/segmentation_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/temporal_filter_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/tokenize_vp8.c \
    $$PWD/DependLibs/libvpx/vp8/encoder/treewriter_vp8.c \
    $$PWD/DependLibs/libvpx/vp9/encoder/x86/temporal_filter_sse4_vp9.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/avg_intrin_sse2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/avg_pred_sse2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/fwd_txfm_avx2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/fwd_txfm_sse2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/inv_txfm_sse2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/inv_txfm_ssse3_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/loopfilter_avx2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/loopfilter_sse2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/quantize_avx_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/quantize_sse2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/quantize_ssse3_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/sad4d_avx2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/sad_avx2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/sum_squares_sse2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/variance_avx2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/x86/variance_sse2_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/add_noise_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/avg_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/bitreader_vpx_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/bitwriter_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/bitwriter_buffer_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/bitreader_buffer_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/deblock_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/fwd_txfm_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/intrapred_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/inv_txfm_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/loopfilter_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/prob_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/psnr_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/quantize_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/sad_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/skin_detection_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/subtract_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/sum_squares_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_dsp/variance_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_scale/generic/gen_scalers_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_scale/generic/yv12config_vpx.c \
    $$PWD/DependLibs/libvpx/vpx_scale/generic/yv12extend_vpx.c

