
INCLUDEPATH += $$PWD/DependLibs/libzip/

HEADERS += 	$$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvTargetOsConfig.h \
    $$PWD/DependLibs/libzip/config_libzip.h \
    $$PWD/DependLibs/libzip/zip.h \
    $$PWD/DependLibs/libzip/zipint.h \
    $$PWD/DependLibs/libzip/zipwin32.h

SOURCES += 	$$PWD/DependLibs/libzip/mkstemp.c \
    $$PWD/DependLibs/libzip/zip_add.c \
    $$PWD/DependLibs/libzip/zip_add_dir.c \
    $$PWD/DependLibs/libzip/zip_add_entry.c \
    $$PWD/DependLibs/libzip/zip_buffer.c \
    $$PWD/DependLibs/libzip/zip_close.c \
    $$PWD/DependLibs/libzip/zip_delete.c \
    $$PWD/DependLibs/libzip/zip_dir_add.c \
    $$PWD/DependLibs/libzip/zip_dirent.c \
    $$PWD/DependLibs/libzip/zip_discard.c \
    $$PWD/DependLibs/libzip/zip_entry.c \
    $$PWD/DependLibs/libzip/zip_err_str.c \
    $$PWD/DependLibs/libzip/zip_error.c \
    $$PWD/DependLibs/libzip/zip_error_clear.c \
    $$PWD/DependLibs/libzip/zip_error_get.c \
    $$PWD/DependLibs/libzip/zip_error_get_sys_type.c \
    $$PWD/DependLibs/libzip/zip_error_strerror.c \
    $$PWD/DependLibs/libzip/zip_error_to_str.c \
    $$PWD/DependLibs/libzip/zip_extra_field.c \
    $$PWD/DependLibs/libzip/zip_extra_field_api.c \
    $$PWD/DependLibs/libzip/zip_fclose.c \
    $$PWD/DependLibs/libzip/zip_fdopen.c \
    $$PWD/DependLibs/libzip/zip_file_add.c \
    $$PWD/DependLibs/libzip/zip_file_error_clear.c \
    $$PWD/DependLibs/libzip/zip_file_error_get.c \
    $$PWD/DependLibs/libzip/zip_file_get_comment.c \
    $$PWD/DependLibs/libzip/zip_file_get_external_attributes.c \
    $$PWD/DependLibs/libzip/zip_file_get_offset.c \
    $$PWD/DependLibs/libzip/zip_file_rename.c \
    $$PWD/DependLibs/libzip/zip_file_replace.c \
    $$PWD/DependLibs/libzip/zip_file_set_comment.c \
    $$PWD/DependLibs/libzip/zip_file_set_external_attributes.c \
    $$PWD/DependLibs/libzip/zip_file_set_mtime.c \
    $$PWD/DependLibs/libzip/zip_file_strerror.c \
    $$PWD/DependLibs/libzip/zip_filerange_crc.c \
    $$PWD/DependLibs/libzip/zip_fopen.c \
    $$PWD/DependLibs/libzip/zip_fopen_encrypted.c \
    $$PWD/DependLibs/libzip/zip_fopen_index.c \
    $$PWD/DependLibs/libzip/zip_fopen_index_encrypted.c \
    $$PWD/DependLibs/libzip/zip_fread.c \
    $$PWD/DependLibs/libzip/zip_get_archive_comment.c \
    $$PWD/DependLibs/libzip/zip_get_archive_flag.c \
    $$PWD/DependLibs/libzip/zip_get_compression_implementation.c \
    $$PWD/DependLibs/libzip/zip_get_encryption_implementation.c \
    $$PWD/DependLibs/libzip/zip_get_file_comment.c \
    $$PWD/DependLibs/libzip/zip_get_name.c \
    $$PWD/DependLibs/libzip/zip_get_num_entries.c \
    $$PWD/DependLibs/libzip/zip_get_num_files.c \
    $$PWD/DependLibs/libzip/zip_hash.c \
    $$PWD/DependLibs/libzip/zip_io_util.c \
    $$PWD/DependLibs/libzip/zip_memdup.c \
    $$PWD/DependLibs/libzip/zip_name_locate.c \
    $$PWD/DependLibs/libzip/zip_new.c \
    $$PWD/DependLibs/libzip/zip_open.c \
    $$PWD/DependLibs/libzip/zip_rename.c \
    $$PWD/DependLibs/libzip/zip_replace.c \
    $$PWD/DependLibs/libzip/zip_set_archive_comment.c \
    $$PWD/DependLibs/libzip/zip_set_archive_flag.c \
    $$PWD/DependLibs/libzip/zip_set_default_password.c \
    $$PWD/DependLibs/libzip/zip_set_file_comment.c \
    $$PWD/DependLibs/libzip/zip_set_file_compression.c \
    $$PWD/DependLibs/libzip/zip_set_name.c \
    $$PWD/DependLibs/libzip/zip_source_begin_write.c \
    $$PWD/DependLibs/libzip/zip_source_buffer.c \
    $$PWD/DependLibs/libzip/zip_source_call.c \
    $$PWD/DependLibs/libzip/zip_source_close.c \
    $$PWD/DependLibs/libzip/zip_source_commit_write.c \
    $$PWD/DependLibs/libzip/zip_source_crc.c \
    $$PWD/DependLibs/libzip/zip_source_deflate.c \
    $$PWD/DependLibs/libzip/zip_source_error.c \
    $$PWD/DependLibs/libzip/zip_source_file.c \
    $$PWD/DependLibs/libzip/zip_source_filep.c \
    $$PWD/DependLibs/libzip/zip_source_free.c \
    $$PWD/DependLibs/libzip/zip_source_function.c \
    $$PWD/DependLibs/libzip/zip_source_is_deleted.c \
    $$PWD/DependLibs/libzip/zip_source_layered.c \
    $$PWD/DependLibs/libzip/zip_source_open.c \
    $$PWD/DependLibs/libzip/zip_source_pkware.c \
    $$PWD/DependLibs/libzip/zip_source_read.c \
    $$PWD/DependLibs/libzip/zip_source_remove.c \
    $$PWD/DependLibs/libzip/zip_source_rollback_write.c \
    $$PWD/DependLibs/libzip/zip_source_seek.c \
    $$PWD/DependLibs/libzip/zip_source_seek_write.c \
    $$PWD/DependLibs/libzip/zip_source_stat.c \
    $$PWD/DependLibs/libzip/zip_source_supports.c \
    $$PWD/DependLibs/libzip/zip_source_tell.c \
    $$PWD/DependLibs/libzip/zip_source_tell_write.c \
    $$PWD/DependLibs/libzip/zip_source_win32a.c \
    $$PWD/DependLibs/libzip/zip_source_win32handle.c \
    $$PWD/DependLibs/libzip/zip_source_win32utf8.c \
    $$PWD/DependLibs/libzip/zip_source_win32w.c \
    $$PWD/DependLibs/libzip/zip_source_window.c \
    $$PWD/DependLibs/libzip/zip_source_write.c \
    $$PWD/DependLibs/libzip/zip_source_zip.c \
    $$PWD/DependLibs/libzip/zip_source_zip_new.c \
    $$PWD/DependLibs/libzip/zip_stat.c \
    $$PWD/DependLibs/libzip/zip_stat_index.c \
    $$PWD/DependLibs/libzip/zip_stat_init.c \
    $$PWD/DependLibs/libzip/zip_strerror.c \
    $$PWD/DependLibs/libzip/zip_string.c \
    $$PWD/DependLibs/libzip/zip_unchange.c \
    $$PWD/DependLibs/libzip/zip_unchange_all.c \
    $$PWD/DependLibs/libzip/zip_unchange_archive.c \
    $$PWD/DependLibs/libzip/zip_unchange_data.c \
    $$PWD/DependLibs/libzip/zip_utf-8.c

