

INCLUDEPATH += $$PWD/DependLibs/libzvbi/src
INCLUDEPATH += $$PWD/DependLibs/libzvbi

HEADERS += 	$$PWD/GoTvCompilerConfig.h \
    $$PWD/GoTvCpuArchDefines.h \
    $$PWD/GoTvDependLibrariesConfig.h \
    $$PWD/GoTvTargetOsConfig.h \
    $$PWD/DependLibs/libzvbi/config_libzvbi.h \
    $$PWD/DependLibs/libzvbi/contrib/dvbsubs.h \
    $$PWD/DependLibs/libzvbi/site_def.h \
    $$PWD/DependLibs/libzvbi/src/_videodev.h \
    $$PWD/DependLibs/libzvbi/src/_videodev2.h \
    $$PWD/DependLibs/libzvbi/src/_videodev2k.h \
    $$PWD/DependLibs/libzvbi/src/bcd.h \
    $$PWD/DependLibs/libzvbi/src/bit_slicer.h \
    $$PWD/DependLibs/libzvbi/src/cache-priv.h \
    $$PWD/DependLibs/libzvbi/src/cache.h \
    $$PWD/DependLibs/libzvbi/src/cc.h \
    $$PWD/DependLibs/libzvbi/src/cc608_decoder.h \
    $$PWD/DependLibs/libzvbi/src/conv.h \
    $$PWD/DependLibs/libzvbi/src/decoder.h \
    $$PWD/DependLibs/libzvbi/src/dlist.h \
    $$PWD/DependLibs/libzvbi/src/dvb.h \
    $$PWD/DependLibs/libzvbi/src/dvb_demux.h \
    $$PWD/DependLibs/libzvbi/src/dvb_mux.h \
    $$PWD/DependLibs/libzvbi/src/event-priv.h \
    $$PWD/DependLibs/libzvbi/src/event.h \
    $$PWD/DependLibs/libzvbi/src/exp-gfx.h \
    $$PWD/DependLibs/libzvbi/src/exp-txt.h \
    $$PWD/DependLibs/libzvbi/src/export_zvbi.h \
    $$PWD/DependLibs/libzvbi/src/format.h \
    $$PWD/DependLibs/libzvbi/src/hamm-tables.h \
    $$PWD/DependLibs/libzvbi/src/hamm.h \
    $$PWD/DependLibs/libzvbi/src/idl_demux.h \
    $$PWD/DependLibs/libzvbi/src/intl-priv.h \
    $$PWD/DependLibs/libzvbi/src/io-sim.h \
    $$PWD/DependLibs/libzvbi/src/io_zvbi_capture.h \
    $$PWD/DependLibs/libzvbi/src/lang.h \
    $$PWD/DependLibs/libzvbi/src/libzvbi.h \
    $$PWD/DependLibs/libzvbi/src/macros.h \
    $$PWD/DependLibs/libzvbi/src/misc.h \
    $$PWD/DependLibs/libzvbi/src/network-table.h \
    $$PWD/DependLibs/libzvbi/src/network.h \
    $$PWD/DependLibs/libzvbi/src/packet-830.h \
    $$PWD/DependLibs/libzvbi/src/page_table.h \
    $$PWD/DependLibs/libzvbi/src/pdc.h \
    $$PWD/DependLibs/libzvbi/src/pfc_demux.h \
    $$PWD/DependLibs/libzvbi/src/proxy-client.h \
    $$PWD/DependLibs/libzvbi/src/proxy-msg.h \
    $$PWD/DependLibs/libzvbi/src/raw_decoder.h \
    $$PWD/DependLibs/libzvbi/src/sampling_par.h \
    $$PWD/DependLibs/libzvbi/src/sliced.h \
    $$PWD/DependLibs/libzvbi/src/sliced_filter.h \
    $$PWD/DependLibs/libzvbi/src/tables.h \
    $$PWD/DependLibs/libzvbi/src/teletext_decoder.h \
    $$PWD/DependLibs/libzvbi/src/trigger.h \
    $$PWD/DependLibs/libzvbi/src/ure.h \
    $$PWD/DependLibs/libzvbi/src/vbi.h \
    $$PWD/DependLibs/libzvbi/src/version.h \
    $$PWD/DependLibs/libzvbi/src/videodev.h \
    $$PWD/DependLibs/libzvbi/src/videodev2.h \
    $$PWD/DependLibs/libzvbi/src/videodev2k.h \
    $$PWD/DependLibs/libzvbi/src/vps.h \
    $$PWD/DependLibs/libzvbi/src/vt.h \
    $$PWD/DependLibs/libzvbi/src/wss.h \
    $$PWD/DependLibs/libzvbi/src/xds_demux.h \
    $$PWD/DependLibs/libzvbi/src/search_zvbi.h

SOURCES += 	$$PWD/DependLibs/libzvbi/contrib/atsc-cc.c \
    $$PWD/DependLibs/libzvbi/contrib/dvbsubs.c \
    $$PWD/DependLibs/libzvbi/contrib/ntsc-cc.c \
    $$PWD/DependLibs/libzvbi/contrib/x11font.c \
    $$PWD/DependLibs/libzvbi/src/bit_slicer.c \
    $$PWD/DependLibs/libzvbi/src/cache.c \
    $$PWD/DependLibs/libzvbi/src/caption.c \
    $$PWD/DependLibs/libzvbi/src/cc608_decoder.c \
    $$PWD/DependLibs/libzvbi/src/chains.c \
    $$PWD/DependLibs/libzvbi/src/conv.c \
    $$PWD/DependLibs/libzvbi/src/decoder.c \
    $$PWD/DependLibs/libzvbi/src/dvb_demux.c \
    $$PWD/DependLibs/libzvbi/src/dvb_mux.c \
    $$PWD/DependLibs/libzvbi/src/event.c \
    $$PWD/DependLibs/libzvbi/src/exp-gfx.c \
    $$PWD/DependLibs/libzvbi/src/exp-html.c \
    $$PWD/DependLibs/libzvbi/src/exp-templ.c \
    $$PWD/DependLibs/libzvbi/src/exp-txt.c \
    $$PWD/DependLibs/libzvbi/src/exp-vtx.c \
    $$PWD/DependLibs/libzvbi/src/export_zvbi.c \
    $$PWD/DependLibs/libzvbi/src/hamm.c \
    $$PWD/DependLibs/libzvbi/src/hammgen.c \
    $$PWD/DependLibs/libzvbi/src/idl_demux.c \
    $$PWD/DependLibs/libzvbi/src/io-bktr.c \
    $$PWD/DependLibs/libzvbi/src/io-dvb.c \
    $$PWD/DependLibs/libzvbi/src/io-sim.c \
    $$PWD/DependLibs/libzvbi/src/io-v4l.c \
    $$PWD/DependLibs/libzvbi/src/io-v4l2.c \
    $$PWD/DependLibs/libzvbi/src/io-v4l2k.c \
    $$PWD/DependLibs/libzvbi/src/io_zvbi_capture.c \
    $$PWD/DependLibs/libzvbi/src/lang.c \
    $$PWD/DependLibs/libzvbi/src/misc.c \
    $$PWD/DependLibs/libzvbi/src/packet-830.c \
    $$PWD/DependLibs/libzvbi/src/packet.c \
    $$PWD/DependLibs/libzvbi/src/page_table.c \
    $$PWD/DependLibs/libzvbi/src/pdc.c \
    $$PWD/DependLibs/libzvbi/src/pfc_demux.c \
    $$PWD/DependLibs/libzvbi/src/proxy-client.c \
    $$PWD/DependLibs/libzvbi/src/proxy-msg.c \
    $$PWD/DependLibs/libzvbi/src/raw_decoder.c \
    $$PWD/DependLibs/libzvbi/src/sampling_par.c \
    $$PWD/DependLibs/libzvbi/src/sliced_filter.c \
    $$PWD/DependLibs/libzvbi/src/tables.c \
    $$PWD/DependLibs/libzvbi/src/teletext.c \
    $$PWD/DependLibs/libzvbi/src/trigger.c \
    $$PWD/DependLibs/libzvbi/src/ure.c \
    $$PWD/DependLibs/libzvbi/src/vbi.c \
    $$PWD/DependLibs/libzvbi/src/vps.c \
    $$PWD/DependLibs/libzvbi/src/wss.c \
    $$PWD/DependLibs/libzvbi/src/xds_demux.c \
    $$PWD/DependLibs/libzvbi/src/search_zvbi.c

