rem @ECHO OFF

SET cur_dir=%CD%
echo " SWIG Current Directory =%cur_dir%" 

SET base_dir=%cur_dir%\..\..\..
SET groovy_dir=%base_dir%\tools\codegenerator\groovy
SET generator_dir=%base_dir%\tools\codegenerator
SET bin_dir=%base_dir%\tools\bin\Win32
SET java_exe=java.exe
echo " SWIG base_dir %base_dir%" 

SET python_dir=%base_dir%\GoTvCore\xbmc\xbmc\interfaces\python
echo " SWIG python_dir %python_dir%" 

rem go into xbmc/interfaces/python
cd "%python_dir%"

SET python_generated_dir=%python_dir%\generated
SET swig_dir=%python_dir%\..\swig
echo "SWIG setting generated dir %python_generated_dir%"

rem make sure all necessary directories exist and delete any old generated files
echo "SWIG checking generated dir"

IF NOT EXIST "%python_generated_dir%" md "%python_generated_dir%"
IF EXIST "%python_generated_dir%\%2.xml" del "%python_generated_dir%\%2.xml"
IF EXIST "%python_generated_dir%\%2.cpp" del "%python_generated_dir%\%2.cpp"
echo "checking doxygen dir"
IF NOT EXIST "%doxygen_dir%" md "%doxygen_dir%"
echo "setting java exe "
IF EXIST "%JAVA_HOME%\bin\java.exe" set java_exe=%JAVA_HOME%\bin\java.exe

echo " running doxygen dir %doxygen_dir%"

rem run doxygen
"%bin_dir%\doxygen\doxygen.exe" > NUL 2>&1

echo " running swig including %base_dir%\GoTvCore\xbmc\xbmc\"
rem run swig to generate the XML used by groovy to generate the python bindings
"%bin_dir%\swig\swig.exe" -w401 -c++ -outdir "%python_generated_dir%" -o "%python_generated_dir%\%2.xml" -xml -I"%base_dir%\GoTvCore\xbmc\xbmc" -xmllang python "%swig_dir%\%2.i"
echo " running groovy "
rem run groovy to generate the python bindings
"%java_exe%" -cp "%groovy_dir%\groovy-all-2.4.4.jar;%groovy_dir%\commons-lang-2.6.jar;%generator_dir%;%python_dir%" groovy.ui.GroovyMain "%generator_dir%\Generator.groovy" "%python_generated_dir%\%2.xml" "%python_dir%\PythonSwig.cpp.template" "%python_generated_dir%\%2.cpp" "%doxygen_dir%"

rem delete the XML file generated by SWIG as it's not needed anymore
del "%python_generated_dir%\%2.xml" > NUL
rem delete the generated doxygen files
rmdir "%doxygen_dir%" /S /Q > NUL

rem go back to the initial directory
cd "%cur_dir%"
