#pragma once
#include <GoTvDependLibrariesConfig.h>

#define HAVE_PTHREAD_H			1

#define CONFIG_VP8_DECODER		1 
#define CONFIG_VP7_DECODER		1
#define CONFIG_VP8_DECODER		1
#define CONFIG_VP9_DECODER		1
#define CONFIG_VQA_DECODER		1
#define CONFIG_WEBP_DECODER		1

#define CONFIG_VP8_ENCODER 1
#define CONFIG_VP8_DECODER 1
#define CONFIG_VP9_ENCODER 1
#define CONFIG_VP9_DECODER 1
#define CONFIG_VP8 1
#define CONFIG_VP9 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1


#define CONFIG_VP8				1
#define CONFIG_VP9				1

#define CONFIG_VPX_POSTPROC		1
#define CONFIG_VP9_POSTPROC		1
#define CONFIG_VP9_TEMPORAL_DENOISING	1
#define CONFIG_VP9_HIGHBITDEPTH 1

#define CONFIG_OS_SUPPORT		1
#define CONFIG_MULTITHREAD		1

#define CONFIG_REALTIME_ONLY	1

#define MAX_VPX_LAG_BUFFERS (CONFIG_REALTIME_ONLY ? 1 : 25)

#define CONFIG_ERROR_CONCEALMENT	0
#define CONFIG_SHARED				0
#define CONFIG_STATIC				1
#define CONFIG_TEMPORAL_DENOISING	1
#define CONFIG_MULTI_RES_ENCODING	1
#define CONFIG_INTERNAL_STATS		0
#define CONFIG_ENCODERS				1
#define CONFIG_LIBYUV				1

// define to build apps with main
//#define BUILD_VPC_ENCODER_APP		1
//#define BUILD_VPC_DECODER_APP		1
