/* Copyright (c) 2011 The WebM project authors. All Rights Reserved. */
/*  */
/* Use of this source code is governed by a BSD-style license */
/* that can be found in the LICENSE file in the root of the source */
/* tree. An additional intellectual property rights grant can be found */
/* in the file PATENTS.  All contributing project authors may */
/* be found in the AUTHORS file in the root of the source tree. */
/* This file automatically generated by configure. Do not edit! */
#pragma once
#include <GoTvDependLibrariesConfig.h>
#ifdef TARGET_OS_WINDOWS
# include "vpx_config_win.h"
#else
# include "vpx_config_linux.h"
#endif // TARGET_OS_WINDOWS

