python prigen.py _bsddb.vcxproj python_bsddb.pri
python prigen.py _ctypes.vcxproj python_ctypes.pri
python prigen.py _ctypes_test.vcxproj python_ctypes_test.pri
python prigen.py _elementtree.vcxproj python_elementtree.pri
python prigen.py _hashlib.vcxproj python_hashlib.pri
python prigen.py _msi.vcxproj python_msi.pri
python prigen.py _multiprocessing.vcxproj python_multiprocessing.pri
python prigen.py _socket.vcxproj python_socket.pri
python prigen.py _sqlite3.vcxproj python_sqlite3.pri
python prigen.py _ssl.vcxproj python_ssl.pri
python prigen.py _testcapi.vcxproj python_testcapi.pri
python prigen.py _tkinter.vcxproj python_tkinter.pri
python prigen.py bz2.vcxproj python_bz2.pri
python prigen.py libeay.vcxproj python_libeay.pri
python prigen.py pyexpat.vcxproj python_pyexpat.pri
python prigen.py python.vcxproj python_python.pri
python prigen.py pythoncore.vcxproj python_pythoncore.pri
python prigen.py select.vcxproj python_select.pri
python prigen.py sqlite3.vcxproj python_sqlite3.pri
python prigen.py ssleay.vcxproj python_ssleay.pri
python prigen.py tcl.vcxproj python_tcl.pri
python prigen.py tix.vcxproj python_tix.pri
python prigen.py tk.vcxproj python_tk.pri
python prigen.py unicodedata.vcxproj python_unicodedata.pri
python prigen.py w9xpopen.vcxproj python_w9xpopen.pri
python prigen.py winsound.vcxproj python_winsound.pri
