/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "17.0-Krypton-89-g3deb56d"
#endif /* AVUTIL_FFVERSION_H */
