#include "crypto\cpt_err.c"
//#include "crypto\cryptlib.c"
#include "crypto\cversion.c"
#include "crypto\ebcdic.c"
//#include "crypto\ex_data.c"
#include "crypto\fips_ers.c"
#include "crypto\mem.c"
#include "crypto\mem_dbg.c"
#include "crypto\o_dir.c"
#include "crypto\o_fips.c"
#include "crypto\o_init.c"
#include "crypto\o_str.c"
#include "crypto\o_time.c"
#include "crypto\uid.c"
#include "crypto\mem_clr.c"

#include "crypto\md4\md4_dgst.c"
#include "crypto\md4\md4_one.c"
