#pragma once
#include <GoTvDependLibrariesConfig.h>

# define LZMA_API_EXPORT		GOTV_EXPORT
# define LZMA_RESTRICT			GOTV_RESTRICT

#define LZMA_API(type) LZMA_API_EXPORT type LZMA_API_CALL
#define LZMA_API_STATIC			1

#ifdef GOTV_ARCH_LITTLE_ENDIAN
# define WORDS_BIGENDIAN
#endif // GOTV_ARCH_LITTLE_ENDIAN


#define HAVE_DECODER_LZMA1		1
#define HAVE_DECODER_LZMA2		1
#define HAVE_DECODER_DELTA		1

#define HAVE_ENCODER_LZMA1		1
#define HAVE_ENCODER_LZMA2		1
#define HAVE_ENCODER_DELTA		1
#ifdef TARGET_CPU_ARM
# define HAVE_DECODER_ARM		1
# define HAVE_ENCODER_ARM		1
#endif // TARGET_CPU_ARM
#ifdef TARGET_CPU_X86
# define HAVE_DECODER_X86		1
# define HAVE_ENCODER_X86		1
#endif // TARGET_CPU_ARM

//#define BUILD_FASTPOS_TABLE_GENERATOR 1
//#define BUILD_CRC64_TABLE_GENERATOR 1
//#define BUILD_CRC32_TABLE_GENERATOR 1
